// Code generated by octoqlgen. DO NOT EDIT.

package githubapitest

import (
	"bytes"
	"encoding/json"
	"errors"
	"fmt"
	"io"
	"net/http"
	"strconv"
	"sync"
	"testing"
	"time"

	"github.com/willabides/octoql"
	"github.com/willabides/octoql/cmd/octoqlgen/internal/schema/githubapi"
)

type LatestCommitRepository = githubapi.LatestCommitRepository

type LatestCommitRepositoryDefaultBranchRef = githubapi.LatestCommitRepositoryDefaultBranchRef

type LatestCommitRepositoryDefaultBranchRefTargetCommit = githubapi.LatestCommitRepositoryDefaultBranchRefTargetCommit

type LatestCommitRepositoryDefaultBranchRefTargetCommitHistoryCommitHistoryConnection = githubapi.LatestCommitRepositoryDefaultBranchRefTargetCommitHistoryCommitHistoryConnection

type LatestCommitRepositoryDefaultBranchRefTargetCommitHistoryCommitHistoryConnectionNodesCommit = githubapi.LatestCommitRepositoryDefaultBranchRefTargetCommitHistoryCommitHistoryConnectionNodesCommit

type LatestCommitRepositoryDefaultBranchRefTargetGitObject = githubapi.LatestCommitRepositoryDefaultBranchRefTargetGitObject

type LatestCommitRepositoryDefaultBranchRefTargetGitObjectOctoqlOther = githubapi.LatestCommitRepositoryDefaultBranchRefTargetGitObjectOctoqlOther

type LatestCommitResponse = githubapi.LatestCommitResponse

type LatestCommitVariables = githubapi.LatestCommitVariables

type testTB interface {
	Cleanup(func())
	Errorf(string, ...any)
}

type graphqlRequest struct {
	OperationName string          `json:"operationName"`
	Variables     json.RawMessage `json:"variables"`
}

type operationResult[V any] func(V, http.ResponseWriter) error

type expectationOptions struct {
	remaining int
	atLeast   bool
}

type ExpectOption func(*expectationOptions)

func Times(count int) ExpectOption {
	return func(options *expectationOptions) {
		options.remaining = count
		options.atLeast = false
	}
}

func MinTimes(count int) ExpectOption {
	return func(options *expectationOptions) {
		options.remaining = count
		options.atLeast = true
	}
}

type expectation[V any] struct {
	variables    V
	variablesKey string
	result       operationResult[V]
	remaining    int
	atLeast      bool
}

type expectationSet[V any] struct {
	mu           sync.Mutex
	tb           testTB
	operation    string
	expectations []*expectation[V]
	fallback     *expectation[V]
}

func (s *expectationSet[V]) expect(
	variables V,
	options ...ExpectOption,
) *expectation[V] {
	config := expectationOptions{remaining: 1}
	for _, option := range options {
		if option != nil {
			option(&config)
		}
	}
	if config.remaining < 0 {
		s.tb.Errorf(
			"%s expectation count must not be negative: %d",
			s.operation,
			config.remaining,
		)
		config.remaining = 0
	}
	key, err := variableKey(variables)
	if err != nil {
		s.tb.Errorf("%s expectation variables: %v", s.operation, err)
		config.remaining = 0
	}

	expected := &expectation[V]{
		variables:    variables,
		variablesKey: key,
		remaining:    config.remaining,
		atLeast:      config.atLeast,
	}
	s.mu.Lock()
	s.expectations = append(s.expectations, expected)
	s.mu.Unlock()
	return expected
}

func (s *expectationSet[V]) expectDefault() *expectation[V] {
	expected := &expectation[V]{
		atLeast: true,
	}
	s.mu.Lock()
	s.fallback = expected
	s.mu.Unlock()
	return expected
}

func (s *expectationSet[V]) setResult(
	expected *expectation[V],
	result operationResult[V],
) {
	s.mu.Lock()
	expected.result = result
	s.mu.Unlock()
}

func (s *expectationSet[V]) match(
	variables V,
	rawVariables []byte,
) (operationResult[V], error) {
	key, err := variableKeyJSON(rawVariables)
	if err != nil {
		return nil, fmt.Errorf("%s variables: %w", s.operation, err)
	}

	s.mu.Lock()
	defer s.mu.Unlock()

	for _, expected := range s.expectations {
		if expected.remaining == 0 && !expected.atLeast {
			continue
		}
		if expected.variablesKey != key {
			continue
		}
		if expected.remaining > 0 {
			expected.remaining--
		}
		if expected.result == nil {
			return nil, fmt.Errorf(
				"%s expectation for variables %+v has no response",
				s.operation,
				variables,
			)
		}
		return expected.result, nil
	}

	if s.fallback != nil {
		if s.fallback.result == nil {
			return nil, fmt.Errorf(
				"%s default expectation has no response",
				s.operation,
			)
		}
		return s.fallback.result, nil
	}

	return nil, fmt.Errorf(
		"no expectation found for %s variables %+v",
		s.operation,
		variables,
	)
}

func (s *expectationSet[V]) reset(variables ...V) {
	s.mu.Lock()
	defer s.mu.Unlock()

	if len(variables) == 0 {
		for _, expected := range s.expectations {
			expected.remaining = 0
		}
		s.expectations = []*expectation[V]{}
		s.fallback = nil
		return
	}

	keys := make([]string, 0, len(variables))
	for _, variablesToReset := range variables {
		key, err := variableKey(variablesToReset)
		if err != nil {
			s.tb.Errorf("%s reset variables: %v", s.operation, err)
			continue
		}
		keys = append(keys, key)
	}

	retained := make([]*expectation[V], 0, len(s.expectations))
	for _, expected := range s.expectations {
		shouldReset := false
		for _, key := range keys {
			if expected.variablesKey == key {
				shouldReset = true
				break
			}
		}

		if shouldReset {
			expected.remaining = 0
			continue
		}
		retained = append(retained, expected)
	}
	s.expectations = retained
}

func variableKey[V any](variables V) (string, error) {
	encoded, err := json.Marshal(variables)
	if err != nil {
		return "", fmt.Errorf("encoding variables: %w", err)
	}
	return variableKeyJSON(encoded)
}

func variableKeyJSON(encoded []byte) (string, error) {
	decoder := json.NewDecoder(bytes.NewReader(encoded))
	decoder.UseNumber()
	var value any
	err := decoder.Decode(&value)
	if err != nil {
		return "", fmt.Errorf("decoding variables: %w", err)
	}
	normalized, err := json.Marshal(value)
	if err != nil {
		return "", fmt.Errorf("normalizing variables: %w", err)
	}
	return string(normalized), nil
}

func decodeVariables(encoded []byte, destination any) error {
	decoder := json.NewDecoder(bytes.NewReader(encoded))
	decoder.UseNumber()
	err := decoder.Decode(destination)
	if err != nil {
		return fmt.Errorf("decoding variables: %w", err)
	}
	return nil
}

func (s *expectationSet[V]) verify() {
	s.mu.Lock()
	defer s.mu.Unlock()

	for _, expected := range s.expectations {
		if expected.remaining > 0 {
			s.tb.Errorf(
				"unmet %s expectation for variables %+v: %d call(s) remaining",
				s.operation,
				expected.variables,
				expected.remaining,
			)
		}
	}
}

type responseOptions struct {
	status int
	header http.Header
	err    error
}

type ResponseOption func(*responseOptions)

func WithStatus(status int) ResponseOption {
	return func(options *responseOptions) {
		if status < 100 || status > 999 {
			options.err = fmt.Errorf("invalid http status %d", status)
			return
		}
		options.status = status
	}
}

func WithHeader(name string, values ...string) ResponseOption {
	canonicalName := http.CanonicalHeaderKey(name)
	clonedValues := append([]string{}, values...)
	return func(options *responseOptions) {
		options.header[canonicalName] = append([]string{}, clonedValues...)
	}
}

func WithHeaders(header http.Header) ResponseOption {
	clonedHeader := http.Header{}
	for name, values := range header {
		canonicalName := http.CanonicalHeaderKey(name)
		clonedHeader[canonicalName] = append(clonedHeader[canonicalName], values...)
	}
	return func(options *responseOptions) {
		for name, values := range clonedHeader {
			options.header[name] = append([]string{}, values...)
		}
	}
}

func WithPrimaryRateLimit(rateLimit octoql.RateLimit) ResponseOption {
	return func(options *responseOptions) {
		hasNegativeValue := rateLimit.Limit < 0 ||
			rateLimit.Remaining < 0 ||
			rateLimit.Used < 0
		if hasNegativeValue {
			options.err = fmt.Errorf("primary rate limit values must not be negative")
			return
		}

		options.header.Set("X-RateLimit-Limit", strconv.Itoa(rateLimit.Limit))
		options.header.Set("X-RateLimit-Remaining", strconv.Itoa(rateLimit.Remaining))
		options.header.Set("X-RateLimit-Used", strconv.Itoa(rateLimit.Used))
		if !rateLimit.Reset.IsZero() {
			options.header.Set(
				"X-RateLimit-Reset",
				strconv.FormatInt(rateLimit.Reset.Unix(), 10),
			)
		}
		if rateLimit.Resource != "" {
			options.header.Set("X-RateLimit-Resource", rateLimit.Resource)
		}
	}
}

func WithSecondaryRateLimit(retryAfter time.Duration) ResponseOption {
	return func(options *responseOptions) {
		if retryAfter < 0 {
			options.err = fmt.Errorf("secondary rate limit retry-after must not be negative")
			return
		}

		seconds := retryAfter / time.Second
		if retryAfter%time.Second != 0 {
			seconds++
		}
		options.header.Set(
			"Retry-After",
			strconv.FormatInt(int64(seconds), 10),
		)
	}
}

func buildResponseOptions(options ...ResponseOption) responseOptions {
	config := responseOptions{
		status: http.StatusOK,
		header: http.Header{},
	}
	for _, option := range options {
		if option != nil {
			option(&config)
		}
	}
	return config
}

func combineResponseOptions(
	base []ResponseOption,
	additional []ResponseOption,
) []ResponseOption {
	combined := make([]ResponseOption, 0, len(base)+len(additional))
	combined = append(combined, base...)
	combined = append(combined, additional...)
	return combined
}

func writeGraphQLResponse(
	writer http.ResponseWriter,
	data any,
	graphqlErrors []octoql.Error,
	options responseOptions,
) error {
	if options.err != nil {
		return options.err
	}

	for name, values := range options.header {
		writer.Header()[name] = append([]string{}, values...)
	}
	writer.Header().Set("Content-Type", "application/json")

	payload := map[string]any{}
	if data != nil {
		payload["data"] = data
	}
	if graphqlErrors != nil {
		payload["errors"] = graphqlErrors
	}
	writer.WriteHeader(options.status)
	err := json.NewEncoder(writer).Encode(payload)
	if err != nil {
		return fmt.Errorf("encoding graphql response: %w", err)
	}
	return nil
}

func writeRequestError(
	writer http.ResponseWriter,
	status int,
	message string,
) error {
	return writeGraphQLResponse(
		writer,
		nil,
		[]octoql.Error{{Message: message}},
		buildResponseOptions(WithStatus(status)),
	)
}

type TestHandler struct {
	tb         testTB
	operation0 expectationSet[LatestCommitVariables]
}

var _ http.Handler = (*TestHandler)(nil)

func NewTestHandler(testingTB testing.TB) *TestHandler {
	return newTestHandler(testingTB)
}

func newTestHandler(testingTB testTB) *TestHandler {
	h := &TestHandler{tb: testingTB}
	h.operation0 = expectationSet[LatestCommitVariables]{
		tb:           testingTB,
		operation:    "LatestCommit",
		expectations: []*expectation[LatestCommitVariables]{},
	}
	testingTB.Cleanup(h.verify)
	return h
}

func (h *TestHandler) verify() {
	h.operation0.verify()
}

func (h *TestHandler) Reset() {
	h.operation0.reset()
}

func (h *TestHandler) ServeHTTP(
	writer http.ResponseWriter,
	request *http.Request,
) {
	if request.Method != http.MethodPost {
		writer.Header().Set("Allow", http.MethodPost)
		err := writeRequestError(
			writer,
			http.StatusMethodNotAllowed,
			"graphql requests must use POST",
		)
		if err != nil {
			h.tb.Errorf("writing method error response: %v", err)
		}
		return
	}

	decoder := json.NewDecoder(
		http.MaxBytesReader(writer, request.Body, 8<<20),
	)
	var graphqlRequest graphqlRequest
	err := decoder.Decode(&graphqlRequest)
	if err != nil {
		writeErr := writeRequestError(
			writer,
			http.StatusBadRequest,
			"decoding graphql request: "+err.Error(),
		)
		if writeErr != nil {
			h.tb.Errorf("writing decode error response: %v", writeErr)
		}
		return
	}

	var extra any
	err = decoder.Decode(&extra)
	if !errors.Is(err, io.EOF) {
		if err == nil {
			err = fmt.Errorf("multiple json values")
		}
		writeErr := writeRequestError(
			writer,
			http.StatusBadRequest,
			"decoding graphql request: "+err.Error(),
		)
		if writeErr != nil {
			h.tb.Errorf("writing trailing data error response: %v", writeErr)
		}
		return
	}

	if graphqlRequest.OperationName == "" {
		err = writeRequestError(
			writer,
			http.StatusBadRequest,
			"graphql request is missing operationName",
		)
		if err != nil {
			h.tb.Errorf("writing missing operation error response: %v", err)
		}
		return
	}
	if len(graphqlRequest.Variables) == 0 {
		graphqlRequest.Variables = json.RawMessage("{}")
	}

	switch graphqlRequest.OperationName {
	case "LatestCommit":
		var variables LatestCommitVariables
		err = decodeVariables(graphqlRequest.Variables, &variables)
		if err != nil {
			h.tb.Errorf("decoding LatestCommit variables: %v", err)
			writeErr := writeRequestError(
				writer,
				http.StatusOK,
				"decoding LatestCommit variables: "+err.Error(),
			)
			if writeErr != nil {
				h.tb.Errorf("writing LatestCommit variable error response: %v", writeErr)
			}
			return
		}

		result, matchErr := h.operation0.match(
			variables,
			graphqlRequest.Variables,
		)
		if matchErr != nil {
			h.tb.Errorf("%v", matchErr)
			writeErr := writeRequestError(
				writer,
				http.StatusOK,
				matchErr.Error(),
			)
			if writeErr != nil {
				h.tb.Errorf("writing LatestCommit expectation error response: %v", writeErr)
			}
			return
		}
		err = result(variables, writer)
		if err != nil {
			h.tb.Errorf("serving LatestCommit response: %v", err)
		}
	default:
		err = writeRequestError(
			writer,
			http.StatusOK,
			"unknown operation: "+graphqlRequest.OperationName,
		)
		if err != nil {
			h.tb.Errorf("writing unknown operation response: %v", err)
		}
	}
}

type LatestCommitExpectation struct {
	set      *expectationSet[LatestCommitVariables]
	expected *expectation[LatestCommitVariables]
	options  []ResponseOption
}

func (h *TestHandler) ExpectLatestCommit(
	variables LatestCommitVariables,
	options ...ExpectOption,
) *LatestCommitExpectation {
	return &LatestCommitExpectation{
		set: &h.operation0,
		expected: h.operation0.expect(
			variables,
			options...,
		),
		options: []ResponseOption{},
	}
}

func (h *TestHandler) DefaultLatestCommit() *LatestCommitExpectation {
	return &LatestCommitExpectation{
		set:      &h.operation0,
		expected: h.operation0.expectDefault(),
		options:  []ResponseOption{},
	}
}

func (h *TestHandler) ResetLatestCommit(variables ...LatestCommitVariables) {
	h.operation0.reset(variables...)
}

func (b *LatestCommitExpectation) WithOptions(
	options ...ResponseOption,
) *LatestCommitExpectation {
	b.options = combineResponseOptions(b.options, options)
	return b
}

func (b *LatestCommitExpectation) Respond(
	data LatestCommitResponse,
	options ...ResponseOption,
) {
	combined := combineResponseOptions(b.options, options)
	responseConfig := buildResponseOptions(combined...)
	b.set.setResult(
		b.expected,
		func(_ LatestCommitVariables, writer http.ResponseWriter) error {
			return writeGraphQLResponse(writer, &data, nil, responseConfig)
		},
	)
}

func (b *LatestCommitExpectation) RespondError(
	graphqlError octoql.Error,
	options ...ResponseOption,
) {
	combined := combineResponseOptions(b.options, options)
	responseConfig := buildResponseOptions(combined...)
	b.set.setResult(
		b.expected,
		func(_ LatestCommitVariables, writer http.ResponseWriter) error {
			return writeGraphQLResponse(
				writer,
				nil,
				[]octoql.Error{graphqlError},
				responseConfig,
			)
		},
	)
}

func (b *LatestCommitExpectation) RespondDataAndErrors(
	data LatestCommitResponse,
	graphqlErrors ...octoql.Error,
) {
	responseConfig := buildResponseOptions(b.options...)
	b.set.setResult(
		b.expected,
		func(_ LatestCommitVariables, writer http.ResponseWriter) error {
			return writeGraphQLResponse(
				writer,
				&data,
				graphqlErrors,
				responseConfig,
			)
		},
	)
}

func (b *LatestCommitExpectation) Handle(
	handler func(LatestCommitVariables, http.ResponseWriter),
) {
	if handler == nil {
		b.set.tb.Errorf("LatestCommit dynamic handler must not be nil")
		b.set.setResult(
			b.expected,
			func(_ LatestCommitVariables, _ http.ResponseWriter) error {
				return fmt.Errorf("LatestCommit dynamic handler is nil")
			},
		)
		return
	}
	b.set.setResult(
		b.expected,
		func(variables LatestCommitVariables, writer http.ResponseWriter) error {
			handler(variables, writer)
			return nil
		},
	)
}
