// Code generated by octoqlgen, DO NOT EDIT.

package main

import (
	"context"
	"time"

	"github.com/willabides/octoql"
)

// __getUserInput is used internally by octoqlgen
type __getUserInput struct {
	Login string `json:"Login"`
}

// getUserResponse is returned by getUser on success.
type getUserResponse struct {
	// Lookup a user by login.
	User getUserUser `json:"user"`
}

// GetUser returns getUserResponse.User, and is useful for accessing the field via an interface.
func (v *getUserResponse) GetUser() getUserUser { return v.User }

// getUserUser includes the requested fields of the GraphQL type User.
// The GraphQL type's documentation follows.
//
// A user is an individual's account on GitHub that owns repositories and can make new content.
type getUserUser struct {
	// The user's public profile name.
	TheirName string `json:"theirName"`
	// Identifies the date and time when the object was created.
	CreatedAt time.Time `json:"createdAt"`
}

// GetTheirName returns getUserUser.TheirName, and is useful for accessing the field via an interface.
func (v *getUserUser) GetTheirName() string { return v.TheirName }

// GetCreatedAt returns getUserUser.CreatedAt, and is useful for accessing the field via an interface.
func (v *getUserUser) GetCreatedAt() time.Time { return v.CreatedAt }

// getViewerResponse is returned by getViewer on success.
type getViewerResponse struct {
	// The currently authenticated user.
	Viewer getViewerViewerUser `json:"viewer"`
}

// GetViewer returns getViewerResponse.Viewer, and is useful for accessing the field via an interface.
func (v *getViewerResponse) GetViewer() getViewerViewerUser { return v.Viewer }

// getViewerViewerUser includes the requested fields of the GraphQL type User.
// The GraphQL type's documentation follows.
//
// A user is an individual's account on GitHub that owns repositories and can make new content.
type getViewerViewerUser struct {
	// The user's public profile name.
	MyName string `json:"MyName"`
	// Identifies the date and time when the object was created.
	CreatedAt time.Time `json:"createdAt"`
}

// GetMyName returns getViewerViewerUser.MyName, and is useful for accessing the field via an interface.
func (v *getViewerViewerUser) GetMyName() string { return v.MyName }

// GetCreatedAt returns getViewerViewerUser.CreatedAt, and is useful for accessing the field via an interface.
func (v *getViewerViewerUser) GetCreatedAt() time.Time { return v.CreatedAt }

// The query executed by getUser.
const getUser_Operation = `
query getUser ($Login: String!) {
	user(login: $Login) {
		theirName: name
		createdAt
	}
}
`

// getUserPartialDataError contains partial data returned by getUser.
type getUserPartialDataError struct {
	data *getUserResponse
	err  error
}

func (err *getUserPartialDataError) Error() string {
	if err == nil || err.err == nil {
		return "graphql response contains partial data"
	}
	return err.err.Error()
}

func (err *getUserPartialDataError) Unwrap() error {
	if err == nil {
		return nil
	}
	return err.err
}

func (err *getUserPartialDataError) PartialData() *getUserResponse {
	if err == nil {
		return nil
	}
	return err.data
}

// getUser gets the given user's name from their username.
func getUser(
	ctx_ context.Context,
	client_ *octoql.Client,
	Login string,
) (*getUserResponse, error) {
	variables_ := __getUserInput{
		Login: Login,
	}
	var response_ getUserResponse
	hasData_, err_ := client_.Execute(
		ctx_,
		octoql.Payload{
			OperationName: "getUser",
			Query:         getUser_Operation,
			Variables:     &variables_,
		},
		&response_,
	)
	if !hasData_ {
		return nil, err_
	}
	if err_ != nil {
		return nil, &getUserPartialDataError{
			data: &response_,
			err:  err_,
		}
	}
	return &response_, nil
}

// The query executed by getViewer.
const getViewer_Operation = `
query getViewer {
	viewer {
		MyName: name
		createdAt
	}
}
`

// getViewerPartialDataError contains partial data returned by getViewer.
type getViewerPartialDataError struct {
	data *getViewerResponse
	err  error
}

func (err *getViewerPartialDataError) Error() string {
	if err == nil || err.err == nil {
		return "graphql response contains partial data"
	}
	return err.err.Error()
}

func (err *getViewerPartialDataError) Unwrap() error {
	if err == nil {
		return nil
	}
	return err.err
}

func (err *getViewerPartialDataError) PartialData() *getViewerResponse {
	if err == nil {
		return nil
	}
	return err.data
}

func getViewer(
	ctx_ context.Context,
	client_ *octoql.Client,
) (*getViewerResponse, error) {
	var response_ getViewerResponse
	hasData_, err_ := client_.Execute(
		ctx_,
		octoql.Payload{
			OperationName: "getViewer",
			Query:         getViewer_Operation,
			Variables:     nil,
		},
		&response_,
	)
	if !hasData_ {
		return nil, err_
	}
	if err_ != nil {
		return nil, &getViewerPartialDataError{
			data: &response_,
			err:  err_,
		}
	}
	return &response_, nil
}
