// Code generated by octoqlgen, DO NOT EDIT.

package main

import (
	"context"
	"time"

	"github.com/willabides/octoql"
)

// getUserResponse is returned by getUser on success.
type getUserResponse struct {
	// Lookup a user by login.
	User getUserUser `json:"user"`
}

// GetUser returns getUserResponse.User, and is useful for accessing the field via an interface.
func (v *getUserResponse) GetUser() getUserUser { return v.User }

// getUserUser includes the requested fields of the GraphQL type User.
// The GraphQL type's documentation follows.
//
// A user is an individual's account on GitHub that owns repositories and can make new content.
type getUserUser struct {
	// The user's public profile name.
	TheirName string `json:"theirName"`
	// Identifies the date and time when the object was created.
	CreatedAt time.Time `json:"createdAt"`
}

// GetTheirName returns getUserUser.TheirName, and is useful for accessing the field via an interface.
func (v *getUserUser) GetTheirName() string { return v.TheirName }

// GetCreatedAt returns getUserUser.CreatedAt, and is useful for accessing the field via an interface.
func (v *getUserUser) GetCreatedAt() time.Time { return v.CreatedAt }

// getUserVariables contains the variables accepted by getUser.
type getUserVariables struct {
	Login string `json:"Login"`
}

// getViewerResponse is returned by getViewer on success.
type getViewerResponse struct {
	// The currently authenticated user.
	Viewer getViewerViewerUser `json:"viewer"`
}

// GetViewer returns getViewerResponse.Viewer, and is useful for accessing the field via an interface.
func (v *getViewerResponse) GetViewer() getViewerViewerUser { return v.Viewer }

// getViewerViewerUser includes the requested fields of the GraphQL type User.
// The GraphQL type's documentation follows.
//
// A user is an individual's account on GitHub that owns repositories and can make new content.
type getViewerViewerUser struct {
	// The user's public profile name.
	MyName string `json:"MyName"`
	// Identifies the date and time when the object was created.
	CreatedAt time.Time `json:"createdAt"`
}

// GetMyName returns getViewerViewerUser.MyName, and is useful for accessing the field via an interface.
func (v *getViewerViewerUser) GetMyName() string { return v.MyName }

// GetCreatedAt returns getViewerViewerUser.CreatedAt, and is useful for accessing the field via an interface.
func (v *getViewerViewerUser) GetCreatedAt() time.Time { return v.CreatedAt }

// The query executed by getUser.
const getUser_Operation = "\nquery getUser ($Login: String!) {\n\tuser(login: $Login) {\n\t\ttheirName: name\n\t\tcreatedAt\n\t}\n}\n"

// getUserPartialDataError contains partial data returned by getUser.
type getUserPartialDataError struct {
	data *getUserResponse
	err  error
}

func (e *getUserPartialDataError) Error() string {
	if e == nil || e.err == nil {
		return "graphql response contains partial data"
	}
	return e.err.Error()
}

func (e *getUserPartialDataError) Unwrap() error {
	if e == nil {
		return nil
	}
	return e.err
}

func (e *getUserPartialDataError) PartialData() *getUserResponse {
	if e == nil {
		return nil
	}
	return e.data
}

// getUser gets the given user's name from their username.
func getUser(
	ctx context.Context,
	client *octoql.Client,
	vars getUserVariables,
) (*getUserResponse, error) {
	var response getUserResponse
	hasData, err := client.Execute(
		ctx,
		octoql.Payload{
			OperationName: "getUser",
			Query:         getUser_Operation,
			Variables:     &vars,
		},
		&response,
	)
	if !hasData {
		return nil, err
	}
	if err != nil {
		return nil, &getUserPartialDataError{
			data: &response,
			err:  err,
		}
	}
	return &response, nil
}

// The query executed by getViewer.
const getViewer_Operation = "\nquery getViewer {\n\tviewer {\n\t\tMyName: name\n\t\tcreatedAt\n\t}\n}\n"

// getViewerPartialDataError contains partial data returned by getViewer.
type getViewerPartialDataError struct {
	data *getViewerResponse
	err  error
}

func (e *getViewerPartialDataError) Error() string {
	if e == nil || e.err == nil {
		return "graphql response contains partial data"
	}
	return e.err.Error()
}

func (e *getViewerPartialDataError) Unwrap() error {
	if e == nil {
		return nil
	}
	return e.err
}

func (e *getViewerPartialDataError) PartialData() *getViewerResponse {
	if e == nil {
		return nil
	}
	return e.data
}

func getViewer(
	ctx context.Context,
	client *octoql.Client,
) (*getViewerResponse, error) {
	var response getViewerResponse
	hasData, err := client.Execute(
		ctx,
		octoql.Payload{
			OperationName: "getViewer",
			Query:         getViewer_Operation,
			Variables:     nil,
		},
		&response,
	)
	if !hasData {
		return nil, err
	}
	if err != nil {
		return nil, &getViewerPartialDataError{
			data: &response,
			err:  err,
		}
	}
	return &response, nil
}
