package main

import (
	"fmt"
	"strings"

	"gopkg.in/yaml.v3"
)

// render converts a JSON Schema document into the Markdown configuration
// reference. Properties are emitted in schema declaration order so repeated
// runs produce identical output.
func render(schema []byte) ([]byte, error) {
	var document yaml.Node
	err := yaml.Unmarshal(schema, &document)
	if err != nil {
		return nil, fmt.Errorf("parsing schema: %w", err)
	}
	if len(document.Content) == 0 {
		return nil, fmt.Errorf("schema is empty")
	}

	root := document.Content[0]
	defs := mappingValue(root, "$defs")

	rootDoc := scalarValue(root, "x-doc")
	if rootDoc == "" {
		return nil, fmt.Errorf("schema root is missing x-doc")
	}

	var out strings.Builder
	out.WriteString("<!-- Code generated by configdocgen. DO NOT EDIT. -->\n\n")
	fmt.Fprintf(&out, "# %s\n\n", scalarValue(root, "title"))
	out.WriteString(strings.TrimRight(rootDoc, "\n"))
	out.WriteString("\n")

	var missing []string
	err = renderProperties(&out, root, defs, "", 2, &missing)
	if err != nil {
		return nil, err
	}
	if len(missing) > 0 {
		return nil, fmt.Errorf("missing x-doc for: %s", strings.Join(missing, ", "))
	}

	return []byte(out.String()), nil
}

// renderProperties emits every property of node, recursing into referenced and
// nested object schemas.
func renderProperties(
	out *strings.Builder,
	node, defs *yaml.Node,
	prefix string,
	depth int,
	missing *[]string,
) error {
	properties := mappingValue(node, "properties")
	if properties == nil {
		return nil
	}
	required := stringSet(mappingValue(node, "required"))

	for i := 0; i+1 < len(properties.Content); i += 2 {
		name := properties.Content[i].Value
		value, err := resolve(properties.Content[i+1], defs)
		if err != nil {
			return err
		}

		path := name
		if prefix != "" {
			path = prefix + "." + name
		}

		doc := scalarValue(value, "x-doc")
		if doc == "" {
			*missing = append(*missing, path)
			continue
		}

		fmt.Fprintf(out, "\n%s `%s`\n\n", strings.Repeat("#", depth), path)
		out.WriteString(metadataLine(value, required[name]))
		out.WriteString("\n\n")
		out.WriteString(strings.TrimRight(doc, "\n"))
		out.WriteString("\n")

		examples := mappingValue(value, "examples")
		if examples != nil && len(examples.Content) > 0 {
			fmt.Fprintf(out, "\n%s\n", exampleLine(examples))
		}

		children, suffix, err := childSchema(value, defs)
		if err != nil {
			return err
		}
		if children == nil {
			continue
		}
		// Map and array entries resolve to a separate definition, whose own
		// prose would otherwise never reach the page.
		if suffix != "" {
			entryDoc := scalarValue(children, "x-doc")
			if entryDoc != "" {
				out.WriteString("\n")
				out.WriteString(strings.TrimRight(entryDoc, "\n"))
				out.WriteString("\n")
			}
		}
		err = renderProperties(out, children, defs, path+suffix, depth+1, missing)
		if err != nil {
			return err
		}
	}

	return nil
}

// childSchema returns the schema whose properties document the contents of
// node, covering nested objects, keyed maps, and arrays of objects. The
// returned suffix qualifies child paths so map and array entries are not
// mistaken for direct fields.
func childSchema(node, defs *yaml.Node) (*yaml.Node, string, error) {
	if mappingValue(node, "properties") != nil {
		return node, "", nil
	}

	additional := mappingValue(node, "additionalProperties")
	if additional != nil && additional.Kind == yaml.MappingNode {
		resolved, err := resolve(additional, defs)
		if err != nil {
			return nil, "", err
		}
		if mappingValue(resolved, "properties") != nil {
			return resolved, ".<name>", nil
		}
	}

	items := mappingValue(node, "items")
	if items != nil {
		resolved, err := resolve(items, defs)
		if err != nil {
			return nil, "", err
		}
		if mappingValue(resolved, "properties") != nil {
			return resolved, "[]", nil
		}
	}

	return nil, "", nil
}

// metadataLine summarizes the type, requiredness, default, and allowed values
// of a property.
func metadataLine(node *yaml.Node, required bool) string {
	parts := []string{fmt.Sprintf("Type: `%s`", propertyType(node))}

	requirement := "Optional"
	if required {
		requirement = "Required"
	}
	parts = append(parts, requirement)

	defaultValue := scalarValue(node, "default")
	if defaultValue != "" {
		parts = append(parts, fmt.Sprintf("Default: `%s`", defaultValue))
	}

	enum := mappingValue(node, "enum")
	if enum != nil && len(enum.Content) > 0 {
		values := make([]string, 0, len(enum.Content))
		for _, item := range enum.Content {
			values = append(values, fmt.Sprintf("`%s`", item.Value))
		}
		parts = append(parts, "Values: "+strings.Join(values, ", "))
	}

	return strings.Join(parts, " · ")
}

// propertyType reports the documented type of a property, defaulting to object
// for schemas that only describe properties.
func propertyType(node *yaml.Node) string {
	declared := scalarValue(node, "type")
	if declared != "" {
		return declared
	}
	return "object"
}

// exampleLine renders example values as inline code, which stays correct for
// scalar, list, and object valued properties alike.
func exampleLine(examples *yaml.Node) string {
	values := make([]string, 0, len(examples.Content))
	for _, item := range examples.Content {
		values = append(values, fmt.Sprintf("`%s`", item.Value))
	}

	label := "Example: "
	if len(values) > 1 {
		label = "Examples: "
	}
	return label + strings.Join(values, ", ")
}

// resolve follows a local $ref, returning the referenced definition.
func resolve(node, defs *yaml.Node) (*yaml.Node, error) {
	ref := scalarValue(node, "$ref")
	if ref == "" {
		return node, nil
	}

	const prefix = "#/$defs/"
	if !strings.HasPrefix(ref, prefix) {
		return nil, fmt.Errorf("unsupported $ref %q", ref)
	}

	name := strings.TrimPrefix(ref, prefix)
	target := mappingValue(defs, name)
	if target == nil {
		return nil, fmt.Errorf("unknown $ref %q", ref)
	}
	return target, nil
}

// mappingValue returns the value node for key, or nil when absent.
func mappingValue(node *yaml.Node, key string) *yaml.Node {
	if node == nil || node.Kind != yaml.MappingNode {
		return nil
	}
	for i := 0; i+1 < len(node.Content); i += 2 {
		if node.Content[i].Value == key {
			return node.Content[i+1]
		}
	}
	return nil
}

// scalarValue returns the scalar value for key, or an empty string when absent.
func scalarValue(node *yaml.Node, key string) string {
	value := mappingValue(node, key)
	if value == nil || value.Kind != yaml.ScalarNode {
		return ""
	}
	return value.Value
}

// stringSet collects the scalar entries of a sequence node.
func stringSet(node *yaml.Node) map[string]bool {
	set := map[string]bool{}
	if node == nil {
		return set
	}
	for _, item := range node.Content {
		set[item.Value] = true
	}
	return set
}
