// Package directive holds the definition of octoqlgen's @octoqlgen directive.
//
// The definition is shared between the generator, which injects it into the
// schema it loads, and the schema materializer, which writes it to a companion
// file so that editors and other GraphQL tooling can resolve it.
package directive

// Name is the directive's name, without the leading "@".
const Name = "octoqlgen"

// SDL declares @octoqlgen.
//
// Declaring it makes the options users write real ast.Directive nodes attached
// to the node they modify, checked by the ordinary GraphQL validation rules,
// rather than comments recovered by source position.
//
// It is deliberately not valid on subscriptions, fragment spreads, or inline
// fragments, so placing it there is a schema error rather than a hand-written
// check.
const SDL = `directive @` + Name + `(
  omitempty: Boolean
  pointer: Boolean
  struct: Boolean
  flatten: Boolean
  bind: String
  typename: String
  alias: String
  for: String
) repeatable on QUERY | MUTATION | FIELD | FRAGMENT_DEFINITION | VARIABLE_DEFINITION
`

// FileName is the name octoqlgen gives the companion file holding SDL.
//
// The declaration goes in its own file rather than into the schema so that a
// fetched schema stays byte-for-byte what its source served, which keeps the
// pinned checksum describing the file on disk exactly.  It also keeps the
// declaration to one file per project: GraphQL rejects a directive declared
// twice, so tooling that reads several schema files at once would fail if each
// of them carried a copy.
const FileName = "octoqlgen-directive.graphql"

// FileContents is the companion file octoqlgen writes next to a schema.
const FileContents = `# Code generated by octoqlgen. DO NOT EDIT.
#
# This file declares @` + Name + ` so editors and other GraphQL tooling can
# resolve it in your operations. It is not part of any schema you fetched, and
# the generator uses its own copy of this declaration, so editing this file
# changes nothing except what your editor reports.
#
# Point your GraphQL tooling at this file alongside your schema. Many setups
# already read every .graphql file in the project; those that take a list, such
# as graphql-config, need it added:
#
#   schema:
#     - schema.graphql
#     - ` + FileName + `
#
# Declare it in exactly one place per project. GraphQL does not allow a
# directive to be declared twice, so tooling that reads several schema files at
# once reports an error if more than one of them declares @` + Name + `.

` + SDL
