// Package directive holds the definitions of octoqlgen's directives.
//
// They are shared between the generator, which injects them into the schema it
// loads, and the schema materializer, which writes them to a companion file so
// that editors and other GraphQL tooling can resolve them.
package directive

// Name is the directive that carries options for the node it is attached to.
const Name = "octoqlgen"

// DefaultsName is the directive that carries defaults for the fields inside an
// operation or fragment.
const DefaultsName = "octoqlgenDefaults"

// ForName is the directive that carries options for a named type's field,
// wherever that field is generated.
const ForName = "octoqlgenFor"

// SDL declares octoqlgen's directives.
//
// There is one directive per scope an option can have, so the scope is visible
// where the option is written and the options each scope accepts are declared
// rather than checked by hand.  A GraphQL directive has a single argument list
// across all of its locations, so the split has to be by directive, not by
// argument.
//
// None of them are valid on subscriptions, fragment spreads, or inline
// fragments, so placing one there is a schema error rather than a hand-written
// check.
const SDL = `directive @` + Name + `(
  omitempty: Boolean
  pointer: Boolean
  struct: Boolean
  flatten: Boolean
  bind: String
  typename: String
  alias: String
) repeatable on QUERY | MUTATION | FIELD | FRAGMENT_DEFINITION | VARIABLE_DEFINITION

directive @` + DefaultsName + `(
  omitempty: Boolean
  pointer: Boolean
  struct: Boolean
) repeatable on QUERY | MUTATION | FRAGMENT_DEFINITION

directive @` + ForName + `(
  field: String!
  omitempty: Boolean
  pointer: Boolean
  bind: String
  typename: String
  alias: String
) repeatable on QUERY | MUTATION | FRAGMENT_DEFINITION
`

// FileName is the name octoqlgen gives the companion file holding SDL.
//
// The declaration goes in its own file rather than into the schema so that a
// fetched schema stays byte-for-byte what its source served, which keeps the
// pinned checksum describing the file on disk exactly.  It also keeps the
// declaration to one file per project: GraphQL rejects a directive declared
// twice, so tooling that reads several schema files at once would fail if each
// of them carried a copy.
const FileName = "octoqlgen-directive.graphql"

// FileContents is the companion file octoqlgen writes next to a schema.
const FileContents = `# Code generated by octoqlgen. DO NOT EDIT.
#
# This file declares octoqlgen's directives so editors and other GraphQL tooling
# can resolve them in your operations. It is not part of any schema you fetched, and
# the generator uses its own copy of this declaration, so editing this file
# changes nothing except what your editor reports.
#
# Point your GraphQL tooling at this file alongside your schema. Many setups
# already read every .graphql file in the project; those that take a list, such
# as graphql-config, need it added:
#
#   schema:
#     - schema.graphql
#     - ` + FileName + `
#
# Declare them in exactly one place per project. GraphQL does not allow a
# directive to be declared twice, so tooling that reads several schema files at
# once reports an error if more than one of them declares @` + Name + `.

` + SDL
