version: 2
builds:
  - main: ./cmd/octoqlgen
    binary: octoqlgen
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows
checksum:
  name_template: checksums.txt
snapshot:
  version_template: "{{ .Tag }}-next"
release:
  disable: true
