// Code generated by octoqlgen, DO NOT EDIT.

package githubdefaults

import (
	"context"
	"time"

	"github.com/willabides/octoql"
)

type octoqlExecutor interface {
	Execute(context.Context, octoql.Payload, interface{}) (bool, error)
}

// GetReviewResponse is returned by GetReview on success.
type GetReviewResponse struct {
	Review GetReviewReview `json:"review"`
}

// GetReview returns GetReviewResponse.Review, and is useful for accessing the field via an interface.
func (v *GetReviewResponse) GetReview() GetReviewReview { return v.Review }

// GetReviewReview includes the requested fields of the GraphQL type Review.
type GetReviewReview struct {
	FullDatabaseId string                      `json:"fullDatabaseId"`
	CreatedAt      time.Time                   `json:"createdAt"`
	Author         *GetReviewReviewAuthorActor `json:"author"`
	Editor         *GetReviewReviewEditorActor `json:"editor"`
}

// GetFullDatabaseId returns GetReviewReview.FullDatabaseId, and is useful for accessing the field via an interface.
func (v *GetReviewReview) GetFullDatabaseId() string { return v.FullDatabaseId }

// GetCreatedAt returns GetReviewReview.CreatedAt, and is useful for accessing the field via an interface.
func (v *GetReviewReview) GetCreatedAt() time.Time { return v.CreatedAt }

// GetAuthor returns GetReviewReview.Author, and is useful for accessing the field via an interface.
func (v *GetReviewReview) GetAuthor() *GetReviewReviewAuthorActor { return v.Author }

// GetEditor returns GetReviewReview.Editor, and is useful for accessing the field via an interface.
func (v *GetReviewReview) GetEditor() *GetReviewReviewEditorActor { return v.Editor }

// GetReviewReviewAuthorActor includes the requested fields of the GraphQL type Actor.
type GetReviewReviewAuthorActor struct {
	Typename string `json:"__typename"`
	Login    string `json:"login"`
	Url      string `json:"url"`
}

// GetTypename returns GetReviewReviewAuthorActor.Typename, and is useful for accessing the field via an interface.
func (v *GetReviewReviewAuthorActor) GetTypename() string { return v.Typename }

// GetLogin returns GetReviewReviewAuthorActor.Login, and is useful for accessing the field via an interface.
func (v *GetReviewReviewAuthorActor) GetLogin() string { return v.Login }

// GetUrl returns GetReviewReviewAuthorActor.Url, and is useful for accessing the field via an interface.
func (v *GetReviewReviewAuthorActor) GetUrl() string { return v.Url }

// GetReviewReviewEditorActor includes the requested fields of the GraphQL type Actor.
type GetReviewReviewEditorActor struct {
	Typename string `json:"__typename"`
	Login    string `json:"login"`
	Url      string `json:"url"`
}

// GetTypename returns GetReviewReviewEditorActor.Typename, and is useful for accessing the field via an interface.
func (v *GetReviewReviewEditorActor) GetTypename() string { return v.Typename }

// GetLogin returns GetReviewReviewEditorActor.Login, and is useful for accessing the field via an interface.
func (v *GetReviewReviewEditorActor) GetLogin() string { return v.Login }

// GetUrl returns GetReviewReviewEditorActor.Url, and is useful for accessing the field via an interface.
func (v *GetReviewReviewEditorActor) GetUrl() string { return v.Url }

// The query executed by GetReview.
const GetReview_Operation = "\nquery GetReview {\n\treview {\n\t\tfullDatabaseId\n\t\tcreatedAt\n\t\tauthor {\n\t\t\t__typename\n\t\t\tlogin\n\t\t\turl\n\t\t}\n\t\teditor {\n\t\t\t__typename\n\t\t\tlogin\n\t\t\turl\n\t\t}\n\t}\n}\n"

// GetReviewPartialDataError contains partial data returned by GetReview.
type GetReviewPartialDataError struct {
	data *GetReviewResponse
	err  error
}

func (e *GetReviewPartialDataError) Error() string {
	if e == nil || e.err == nil {
		return "graphql response contains partial data"
	}
	return e.err.Error()
}

func (e *GetReviewPartialDataError) Unwrap() error {
	if e == nil {
		return nil
	}
	return e.err
}

func (e *GetReviewPartialDataError) PartialData() *GetReviewResponse {
	if e == nil {
		return nil
	}
	return e.data
}

func GetReview(
	ctx context.Context,
	client octoqlExecutor,
) (*GetReviewResponse, error) {
	var response GetReviewResponse
	hasData, err := client.Execute(
		ctx,
		octoql.Payload{
			OperationName: "GetReview",
			Query:         GetReview_Operation,
			Variables:     nil,
		},
		&response,
	)
	if !hasData {
		return nil, err
	}
	if err != nil {
		return nil, &GetReviewPartialDataError{
			data: &response,
			err:  err,
		}
	}
	return &response, nil
}
