# Copyright (c) 2026 octoql contributors
# SPDX-License-Identifier: MIT

query GitHubNaming @octoqlgen(typename: "GitHubNamingResponse") {
  account {
    id @octoqlgen(bind: "string")
    login @octoqlgen(bind: "-")
  }
  first: repository(owner: "octo", name: "one") {
    nameWithOwner @octoqlgen(typename: "FirstRepository")
  }
  second: repository(owner: "octo", name: "two") {
    nameWithOwner @octoqlgen(typename: "SecondRepository")
  }
  snake_case_type {
    id
    name
  }
  object {
    snake_case_field {
      id
    }
  }
}
