// Copyright (c) 2026 octoql contributors
// SPDX-License-Identifier: MIT

// generateconfigtypes preserves the existing config API around jsonschematogo output.
package main

import (
	"fmt"
	"os"
	"strings"
)

func main() {
	err := run(os.Args[1:])
	if err != nil {
		fmt.Fprintln(os.Stderr, err)
		os.Exit(1)
	}
}

func run(args []string) error {
	if len(args) != 1 {
		return fmt.Errorf("usage: generateconfigtypes FILE")
	}

	filename := args[0]
	content, err := os.ReadFile(filename)
	if err != nil {
		return fmt.Errorf("reading %s: %w", filename, err)
	}

	replacer := strings.NewReplacer(
		"// Code generated by jsonschematogo. DO NOT EDIT.",
		"// Copyright (c) 2026 octoql contributors\n// SPDX-License-Identifier: MIT\n// Code generated by jsonschematogo for octoqlgen. DO NOT EDIT.",
		"type Revision string", "type Revision = string",
		"type Url string", "type URL = string",
		"GithubDocs", "GitHubDocs",
		"GithubRepository", "GitHubRepository",
		"Url              *Url", "URL              *URL",
		"Sha256 *string", "SHA256 string",
		"Source *Source", "Source Source",
		"Host       *string", "Host       string",
	)
	updated := replacer.Replace(string(content))
	if updated == string(content) {
		return fmt.Errorf("adapting %s: no generated fields changed", filename)
	}

	err = os.WriteFile(filename, []byte(updated), 0o644)
	if err != nil {
		return fmt.Errorf("writing %s: %w", filename, err)
	}
	return nil
}
