// Code generated by octoqlgen, DO NOT EDIT.

package nocontext

import (
	"context"

	"github.com/willabides/octoql"
)

// GetRepositoryRepository includes the requested fields of the GraphQL type Repository.
type GetRepositoryRepository struct {
	NameWithOwner string `json:"nameWithOwner"`
}

// GetNameWithOwner returns GetRepositoryRepository.NameWithOwner, and is useful for accessing the field via an interface.
func (v *GetRepositoryRepository) GetNameWithOwner() string { return v.NameWithOwner }

// GetRepositoryResponse is returned by GetRepository on success.
type GetRepositoryResponse struct {
	Repository GetRepositoryRepository `json:"repository"`
}

// GetRepository returns GetRepositoryResponse.Repository, and is useful for accessing the field via an interface.
func (v *GetRepositoryResponse) GetRepository() GetRepositoryRepository { return v.Repository }

// __GetRepositoryInput is used internally by octoqlgen
type __GetRepositoryInput struct {
	Owner string `json:"owner"`
	Name  string `json:"name"`
}

// GetOwner returns __GetRepositoryInput.Owner, and is useful for accessing the field via an interface.
func (v *__GetRepositoryInput) GetOwner() string { return v.Owner }

// GetName returns __GetRepositoryInput.Name, and is useful for accessing the field via an interface.
func (v *__GetRepositoryInput) GetName() string { return v.Name }

type __octoqlPartialDataError[T any] struct {
	data *T
	err  error
}

func (err *__octoqlPartialDataError[T]) Error() string {
	if err == nil || err.err == nil {
		return "graphql response contains partial data"
	}
	return err.err.Error()
}

func (err *__octoqlPartialDataError[T]) Unwrap() error {
	if err == nil {
		return nil
	}
	return err.err
}

func (err *__octoqlPartialDataError[T]) PartialData() *T {
	if err == nil {
		return nil
	}
	return err.data
}

func __octoqlDo[T any](
	ctx context.Context,
	client *octoql.Client,
	payload octoql.Payload,
	newPartialDataError func(*T, error) error,
) (*T, error) {
	response := new(T)
	hasData, err := client.Execute(ctx, payload, response)
	if !hasData {
		return nil, err
	}
	if err != nil {
		return nil, newPartialDataError(response, err)
	}
	return response, nil
}

// The query executed by GetRepository.
const GetRepository_Operation = `
query GetRepository ($owner: String!, $name: String!) {
	repository(owner: $owner, name: $name) {
		nameWithOwner
	}
}
`

// GetRepositoryPartialDataError contains partial data returned by GetRepository.
type GetRepositoryPartialDataError struct {
	__octoqlPartialDataError[GetRepositoryResponse]
}

func GetRepository(
	client_ *octoql.Client,
	owner string,
	name string,
) (*GetRepositoryResponse, error) {
	variables_ := __GetRepositoryInput{
		Owner: owner,
		Name:  name,
	}
	return __octoqlDo[GetRepositoryResponse](
		context.Background(),
		client_,
		octoql.Payload{
			OperationName: "GetRepository",
			Query:         GetRepository_Operation,
			Variables:     &variables_,
		},
		func(data *GetRepositoryResponse, err error) error {
			return &GetRepositoryPartialDataError{
				__octoqlPartialDataError: __octoqlPartialDataError[GetRepositoryResponse]{
					data: data,
					err:  err,
				},
			}
		},
	)
}
