// Code generated by octoqlgen, DO NOT EDIT.

package nocontext

import (
	"context"
	"errors"

	"github.com/willabides/octoql"
)

// GetRepositoryRepository includes the requested fields of the GraphQL type Repository.
type GetRepositoryRepository struct {
	NameWithOwner string `json:"nameWithOwner"`
}

// GetNameWithOwner returns GetRepositoryRepository.NameWithOwner, and is useful for accessing the field via an interface.
func (v *GetRepositoryRepository) GetNameWithOwner() string { return v.NameWithOwner }

// GetRepositoryResponse is returned by GetRepository on success.
type GetRepositoryResponse struct {
	Repository GetRepositoryRepository `json:"repository"`
}

// GetRepository returns GetRepositoryResponse.Repository, and is useful for accessing the field via an interface.
func (v *GetRepositoryResponse) GetRepository() GetRepositoryRepository { return v.Repository }

// __GetRepositoryInput is used internally by octoqlgen
type __GetRepositoryInput struct {
	Owner string `json:"owner"`
	Name  string `json:"name"`
}

// GetOwner returns __GetRepositoryInput.Owner, and is useful for accessing the field via an interface.
func (v *__GetRepositoryInput) GetOwner() string { return v.Owner }

// GetName returns __GetRepositoryInput.Name, and is useful for accessing the field via an interface.
func (v *__GetRepositoryInput) GetName() string { return v.Name }

// The query executed by GetRepository.
const GetRepository_Operation = `
query GetRepository ($owner: String!, $name: String!) {
	repository(owner: $owner, name: $name) {
		nameWithOwner
	}
}
`

func GetRepository(
	client_ *octoql.Client,
	owner string,
	name string,
) (*GetRepositoryResponse, error) {
	variables_ := __GetRepositoryInput{
		Owner: owner,
		Name:  name,
	}
	response_ := new(GetRepositoryResponse)
	err_ := octoql.Do(
		context.Background(),
		client_,
		octoql.Operation{
			Name:  "GetRepository",
			Query: GetRepository_Operation,
		},
		&variables_,
		response_,
	)
	if err_ == nil {
		return response_, nil
	}
	_, hasResponse_ := errors.AsType[*octoql.ResponseError](err_)
	if !hasResponse_ {
		return nil, err_
	}
	return response_, err_
}
