// Code generated by octoqlgen, DO NOT EDIT.

package nocontext

import (
	"context"

	"github.com/willabides/octoql"
)

// GetRepositoryRepository includes the requested fields of the GraphQL type Repository.
type GetRepositoryRepository struct {
	NameWithOwner string `json:"nameWithOwner"`
}

// GetNameWithOwner returns GetRepositoryRepository.NameWithOwner, and is useful for accessing the field via an interface.
func (v *GetRepositoryRepository) GetNameWithOwner() string { return v.NameWithOwner }

// GetRepositoryResponse is returned by GetRepository on success.
type GetRepositoryResponse struct {
	Repository GetRepositoryRepository `json:"repository"`
}

// GetRepository returns GetRepositoryResponse.Repository, and is useful for accessing the field via an interface.
func (v *GetRepositoryResponse) GetRepository() GetRepositoryRepository { return v.Repository }

// __GetRepositoryInput is used internally by octoqlgen
type __GetRepositoryInput struct {
	Owner string `json:"owner"`
	Name  string `json:"name"`
}

// The query executed by GetRepository.
const GetRepository_Operation = `
query GetRepository ($owner: String!, $name: String!) {
	repository(owner: $owner, name: $name) {
		nameWithOwner
	}
}
`

// GetRepositoryPartialDataError contains partial data returned by GetRepository.
type GetRepositoryPartialDataError struct {
	data *GetRepositoryResponse
	err  error
}

func (e *GetRepositoryPartialDataError) Error() string {
	if e == nil || e.err == nil {
		return "graphql response contains partial data"
	}
	return e.err.Error()
}

func (e *GetRepositoryPartialDataError) Unwrap() error {
	if e == nil {
		return nil
	}
	return e.err
}

func (e *GetRepositoryPartialDataError) PartialData() *GetRepositoryResponse {
	if e == nil {
		return nil
	}
	return e.data
}

func GetRepository(
	client_ *octoql.Client,
	owner string,
	name string,
) (*GetRepositoryResponse, error) {
	variables_ := __GetRepositoryInput{
		Owner: owner,
		Name:  name,
	}
	var response_ GetRepositoryResponse
	hasData_, err_ := client_.Execute(
		context.Background(),
		octoql.Payload{
			OperationName: "GetRepository",
			Query:         GetRepository_Operation,
			Variables:     &variables_,
		},
		&response_,
	)
	if !hasData_ {
		return nil, err_
	}
	if err_ != nil {
		return nil, &GetRepositoryPartialDataError{
			data: &response_,
			err:  err_,
		}
	}
	return &response_, nil
}
