// Code generated by octoqlgen. DO NOT EDIT.

package githubapitest

import (
	"bytes"
	"encoding/json"
	"errors"
	"fmt"
	"io"
	"net/http"
	"strconv"
	"sync"
	"testing"
	"time"

	"github.com/willabides/octoql"
)

// CreateRepositoryCreateRepositoryCreateRepositoryPayload includes the requested fields of the GraphQL type CreateRepositoryPayload.
type CreateRepositoryCreateRepositoryCreateRepositoryPayload struct {
	Repository       CreateRepositoryCreateRepositoryCreateRepositoryPayloadRepository `json:"repository"`
	ClientMutationId string                                                            `json:"clientMutationId"`
}

// GetRepository returns CreateRepositoryCreateRepositoryCreateRepositoryPayload.Repository, and is useful for accessing the field via an interface.
func (v *CreateRepositoryCreateRepositoryCreateRepositoryPayload) GetRepository() CreateRepositoryCreateRepositoryCreateRepositoryPayloadRepository {
	return v.Repository
}

// GetClientMutationId returns CreateRepositoryCreateRepositoryCreateRepositoryPayload.ClientMutationId, and is useful for accessing the field via an interface.
func (v *CreateRepositoryCreateRepositoryCreateRepositoryPayload) GetClientMutationId() string {
	return v.ClientMutationId
}

// CreateRepositoryCreateRepositoryCreateRepositoryPayloadRepository includes the requested fields of the GraphQL type Repository.
type CreateRepositoryCreateRepositoryCreateRepositoryPayloadRepository struct {
	Id            string                                                                                 `json:"id"`
	NameWithOwner string                                                                                 `json:"nameWithOwner"`
	UpdatedAt     time.Time                                                                              `json:"updatedAt"`
	Issues        CreateRepositoryCreateRepositoryCreateRepositoryPayloadRepositoryIssuesIssueConnection `json:"issues"`
}

// GetId returns CreateRepositoryCreateRepositoryCreateRepositoryPayloadRepository.Id, and is useful for accessing the field via an interface.
func (v *CreateRepositoryCreateRepositoryCreateRepositoryPayloadRepository) GetId() string {
	return v.Id
}

// GetNameWithOwner returns CreateRepositoryCreateRepositoryCreateRepositoryPayloadRepository.NameWithOwner, and is useful for accessing the field via an interface.
func (v *CreateRepositoryCreateRepositoryCreateRepositoryPayloadRepository) GetNameWithOwner() string {
	return v.NameWithOwner
}

// GetUpdatedAt returns CreateRepositoryCreateRepositoryCreateRepositoryPayloadRepository.UpdatedAt, and is useful for accessing the field via an interface.
func (v *CreateRepositoryCreateRepositoryCreateRepositoryPayloadRepository) GetUpdatedAt() time.Time {
	return v.UpdatedAt
}

// GetIssues returns CreateRepositoryCreateRepositoryCreateRepositoryPayloadRepository.Issues, and is useful for accessing the field via an interface.
func (v *CreateRepositoryCreateRepositoryCreateRepositoryPayloadRepository) GetIssues() CreateRepositoryCreateRepositoryCreateRepositoryPayloadRepositoryIssuesIssueConnection {
	return v.Issues
}

// CreateRepositoryCreateRepositoryCreateRepositoryPayloadRepositoryIssuesIssueConnection includes the requested fields of the GraphQL type IssueConnection.
type CreateRepositoryCreateRepositoryCreateRepositoryPayloadRepositoryIssuesIssueConnection struct {
	PageInfo CreateRepositoryCreateRepositoryCreateRepositoryPayloadRepositoryIssuesIssueConnectionPageInfo `json:"pageInfo"`
}

// GetPageInfo returns CreateRepositoryCreateRepositoryCreateRepositoryPayloadRepositoryIssuesIssueConnection.PageInfo, and is useful for accessing the field via an interface.
func (v *CreateRepositoryCreateRepositoryCreateRepositoryPayloadRepositoryIssuesIssueConnection) GetPageInfo() CreateRepositoryCreateRepositoryCreateRepositoryPayloadRepositoryIssuesIssueConnectionPageInfo {
	return v.PageInfo
}

// CreateRepositoryCreateRepositoryCreateRepositoryPayloadRepositoryIssuesIssueConnectionPageInfo includes the requested fields of the GraphQL type PageInfo.
type CreateRepositoryCreateRepositoryCreateRepositoryPayloadRepositoryIssuesIssueConnectionPageInfo struct {
	HasNextPage bool `json:"hasNextPage"`
}

// GetHasNextPage returns CreateRepositoryCreateRepositoryCreateRepositoryPayloadRepositoryIssuesIssueConnectionPageInfo.HasNextPage, and is useful for accessing the field via an interface.
func (v *CreateRepositoryCreateRepositoryCreateRepositoryPayloadRepositoryIssuesIssueConnectionPageInfo) GetHasNextPage() bool {
	return v.HasNextPage
}

type CreateRepositoryInput struct {
	Name             string               `json:"name"`
	OwnerId          string               `json:"ownerId"`
	Visibility       RepositoryVisibility `json:"visibility"`
	ClientMutationId string               `json:"clientMutationId"`
}

// GetName returns CreateRepositoryInput.Name, and is useful for accessing the field via an interface.
func (v *CreateRepositoryInput) GetName() string { return v.Name }

// GetOwnerId returns CreateRepositoryInput.OwnerId, and is useful for accessing the field via an interface.
func (v *CreateRepositoryInput) GetOwnerId() string { return v.OwnerId }

// GetVisibility returns CreateRepositoryInput.Visibility, and is useful for accessing the field via an interface.
func (v *CreateRepositoryInput) GetVisibility() RepositoryVisibility { return v.Visibility }

// GetClientMutationId returns CreateRepositoryInput.ClientMutationId, and is useful for accessing the field via an interface.
func (v *CreateRepositoryInput) GetClientMutationId() string { return v.ClientMutationId }

// CreateRepositoryResponse is returned by CreateRepository on success.
type CreateRepositoryResponse struct {
	CreateRepository CreateRepositoryCreateRepositoryCreateRepositoryPayload `json:"createRepository"`
}

// GetCreateRepository returns CreateRepositoryResponse.CreateRepository, and is useful for accessing the field via an interface.
func (v *CreateRepositoryResponse) GetCreateRepository() CreateRepositoryCreateRepositoryCreateRepositoryPayload {
	return v.CreateRepository
}

// EchoAnyResponse is returned by EchoAny on success.
type EchoAnyResponse struct {
	EchoAny any `json:"echoAny"`
}

// GetEchoAny returns EchoAnyResponse.EchoAny, and is useful for accessing the field via an interface.
func (v *EchoAnyResponse) GetEchoAny() any { return v.EchoAny }

// EchoAtResponse is returned by EchoAt on success.
type EchoAtResponse struct {
	EchoAt time.Time `json:"echoAt"`
}

// GetEchoAt returns EchoAtResponse.EchoAt, and is useful for accessing the field via an interface.
func (v *EchoAtResponse) GetEchoAt() time.Time { return v.EchoAt }

// EchoPropertyResponse is returned by EchoProperty on success.
type EchoPropertyResponse struct {
	EchoProperty json.RawMessage `json:"echoProperty"`
}

// GetEchoProperty returns EchoPropertyResponse.EchoProperty, and is useful for accessing the field via an interface.
func (v *EchoPropertyResponse) GetEchoProperty() json.RawMessage { return v.EchoProperty }

// GetNodeNode includes the requested fields of the GraphQL interface Node.
//
// GetNodeNode is implemented by the following types:
// GetNodeNodeIssue
// GetNodeNodeRepository
// GetNodeNodeOctoqlOther
type GetNodeNode interface {
	implementsGraphQLInterfaceGetNodeNode()
	// GetTypename returns the receiver's concrete GraphQL type-name (see interface doc for possible values).
	GetTypename() string
	// GetId returns the interface-field "id" from its implementation.
	GetId() string
}

func (v *GetNodeNodeIssue) implementsGraphQLInterfaceGetNodeNode()       {}
func (v *GetNodeNodeRepository) implementsGraphQLInterfaceGetNodeNode()  {}
func (v *GetNodeNodeOctoqlOther) implementsGraphQLInterfaceGetNodeNode() {}

func __unmarshalGetNodeNode(b []byte, v *GetNodeNode) error {
	if string(b) == "null" {
		return nil
	}

	var tn struct {
		TypeName string `json:"__typename"`
	}
	err := json.Unmarshal(b, &tn)
	if err != nil {
		return err
	}

	switch tn.TypeName {
	case "Issue":
		*v = new(GetNodeNodeIssue)
		return json.Unmarshal(b, *v)
	case "Repository":
		*v = new(GetNodeNodeRepository)
		return json.Unmarshal(b, *v)
	case "":
		return fmt.Errorf(
			"response was missing Node.__typename")
	default:
		*v = new(GetNodeNodeOctoqlOther)
		return json.Unmarshal(b, *v)
	}
}

func __marshalGetNodeNode(v *GetNodeNode) ([]byte, error) {

	var typename string
	switch v := (*v).(type) {
	case *GetNodeNodeIssue:
		typename = "Issue"

		result := struct {
			TypeName string `json:"__typename"`
			*GetNodeNodeIssue
		}{typename, v}
		return json.Marshal(result)
	case *GetNodeNodeRepository:
		typename = "Repository"

		result := struct {
			TypeName string `json:"__typename"`
			*GetNodeNodeRepository
		}{typename, v}
		return json.Marshal(result)
	case *GetNodeNodeOctoqlOther:
		return json.Marshal(v)
	case nil:
		return []byte("null"), nil
	default:
		return nil, fmt.Errorf(
			`unexpected concrete type for GetNodeNode: "%T"`, v)
	}
}

// GetNodeNodeIssue includes the requested fields of the GraphQL type Issue.
type GetNodeNodeIssue struct {
	Typename string `json:"__typename"`
	Id       string `json:"id"`
	Title    string `json:"title"`
}

// GetTypename returns GetNodeNodeIssue.Typename, and is useful for accessing the field via an interface.
func (v *GetNodeNodeIssue) GetTypename() string { return v.Typename }

// GetId returns GetNodeNodeIssue.Id, and is useful for accessing the field via an interface.
func (v *GetNodeNodeIssue) GetId() string { return v.Id }

// GetTitle returns GetNodeNodeIssue.Title, and is useful for accessing the field via an interface.
func (v *GetNodeNodeIssue) GetTitle() string { return v.Title }

// GetNodeNodeOctoqlOther represents GetNodeNode implementations not explicitly selected by a fragment. Use GetTypename to identify the concrete GraphQL type.
type GetNodeNodeOctoqlOther struct {
	Typename string `json:"__typename"`
	Id       string `json:"id"`
}

// GetTypename returns GetNodeNodeOctoqlOther.Typename, and is useful for accessing the field via an interface.
func (v *GetNodeNodeOctoqlOther) GetTypename() string { return v.Typename }

// GetId returns GetNodeNodeOctoqlOther.Id, and is useful for accessing the field via an interface.
func (v *GetNodeNodeOctoqlOther) GetId() string { return v.Id }

// GetNodeNodeRepository includes the requested fields of the GraphQL type Repository.
type GetNodeNodeRepository struct {
	Typename      string `json:"__typename"`
	Id            string `json:"id"`
	NameWithOwner string `json:"nameWithOwner"`
}

// GetTypename returns GetNodeNodeRepository.Typename, and is useful for accessing the field via an interface.
func (v *GetNodeNodeRepository) GetTypename() string { return v.Typename }

// GetId returns GetNodeNodeRepository.Id, and is useful for accessing the field via an interface.
func (v *GetNodeNodeRepository) GetId() string { return v.Id }

// GetNameWithOwner returns GetNodeNodeRepository.NameWithOwner, and is useful for accessing the field via an interface.
func (v *GetNodeNodeRepository) GetNameWithOwner() string { return v.NameWithOwner }

// GetNodeResponse is returned by GetNode on success.
type GetNodeResponse struct {
	Node GetNodeNode `json:"-"`
}

// GetNode returns GetNodeResponse.Node, and is useful for accessing the field via an interface.
func (v *GetNodeResponse) GetNode() GetNodeNode { return v.Node }

func (v *GetNodeResponse) UnmarshalJSON(b []byte) error {

	if string(b) == "null" {
		return nil
	}

	var firstPass struct {
		*GetNodeResponse
		Node json.RawMessage `json:"node"`
		octoql.NoUnmarshalJSON
	}
	firstPass.GetNodeResponse = v

	err := json.Unmarshal(b, &firstPass)
	if err != nil {
		return err
	}

	{
		dst := &v.Node
		src := firstPass.Node
		if len(src) != 0 && string(src) != "null" {
			err = __unmarshalGetNodeNode(
				src, dst)
			if err != nil {
				return fmt.Errorf(
					"unable to unmarshal GetNodeResponse.Node: %w", err)
			}
		}
	}
	return nil
}

type __premarshalGetNodeResponse struct {
	Node json.RawMessage `json:"node"`
}

func (v *GetNodeResponse) MarshalJSON() ([]byte, error) {
	premarshaled, err := v.__premarshalJSON()
	if err != nil {
		return nil, err
	}
	return json.Marshal(premarshaled)
}

func (v *GetNodeResponse) __premarshalJSON() (*__premarshalGetNodeResponse, error) {
	var retval __premarshalGetNodeResponse

	{

		dst := &retval.Node
		src := v.Node
		var err error
		*dst, err = __marshalGetNodeNode(
			&src)
		if err != nil {
			return nil, fmt.Errorf(
				"unable to marshal GetNodeResponse.Node: %w", err)
		}
	}
	return &retval, nil
}

// GetRepositoryRepository includes the requested fields of the GraphQL type Repository.
type GetRepositoryRepository struct {
	Id            string                                       `json:"id"`
	FullName      string                                       `json:"fullName"`
	UpdatedAt     time.Time                                    `json:"updatedAt"`
	PropertyValue json.RawMessage                              `json:"propertyValue"`
	Issues        GetRepositoryRepositoryIssuesIssueConnection `json:"issues"`
}

// GetId returns GetRepositoryRepository.Id, and is useful for accessing the field via an interface.
func (v *GetRepositoryRepository) GetId() string { return v.Id }

// GetFullName returns GetRepositoryRepository.FullName, and is useful for accessing the field via an interface.
func (v *GetRepositoryRepository) GetFullName() string { return v.FullName }

// GetUpdatedAt returns GetRepositoryRepository.UpdatedAt, and is useful for accessing the field via an interface.
func (v *GetRepositoryRepository) GetUpdatedAt() time.Time { return v.UpdatedAt }

// GetPropertyValue returns GetRepositoryRepository.PropertyValue, and is useful for accessing the field via an interface.
func (v *GetRepositoryRepository) GetPropertyValue() json.RawMessage { return v.PropertyValue }

// GetIssues returns GetRepositoryRepository.Issues, and is useful for accessing the field via an interface.
func (v *GetRepositoryRepository) GetIssues() GetRepositoryRepositoryIssuesIssueConnection {
	return v.Issues
}

// GetRepositoryRepositoryIssuesIssueConnection includes the requested fields of the GraphQL type IssueConnection.
type GetRepositoryRepositoryIssuesIssueConnection struct {
	Nodes    []GetRepositoryRepositoryIssuesIssueConnectionNodesIssue `json:"nodes"`
	PageInfo GetRepositoryRepositoryIssuesIssueConnectionPageInfo     `json:"pageInfo"`
}

// GetNodes returns GetRepositoryRepositoryIssuesIssueConnection.Nodes, and is useful for accessing the field via an interface.
func (v *GetRepositoryRepositoryIssuesIssueConnection) GetNodes() []GetRepositoryRepositoryIssuesIssueConnectionNodesIssue {
	return v.Nodes
}

// GetPageInfo returns GetRepositoryRepositoryIssuesIssueConnection.PageInfo, and is useful for accessing the field via an interface.
func (v *GetRepositoryRepositoryIssuesIssueConnection) GetPageInfo() GetRepositoryRepositoryIssuesIssueConnectionPageInfo {
	return v.PageInfo
}

// GetRepositoryRepositoryIssuesIssueConnectionNodesIssue includes the requested fields of the GraphQL type Issue.
type GetRepositoryRepositoryIssuesIssueConnectionNodesIssue struct {
	Id    string `json:"id"`
	Title string `json:"title"`
}

// GetId returns GetRepositoryRepositoryIssuesIssueConnectionNodesIssue.Id, and is useful for accessing the field via an interface.
func (v *GetRepositoryRepositoryIssuesIssueConnectionNodesIssue) GetId() string { return v.Id }

// GetTitle returns GetRepositoryRepositoryIssuesIssueConnectionNodesIssue.Title, and is useful for accessing the field via an interface.
func (v *GetRepositoryRepositoryIssuesIssueConnectionNodesIssue) GetTitle() string { return v.Title }

// GetRepositoryRepositoryIssuesIssueConnectionPageInfo includes the requested fields of the GraphQL type PageInfo.
type GetRepositoryRepositoryIssuesIssueConnectionPageInfo struct {
	HasNextPage bool   `json:"hasNextPage"`
	EndCursor   string `json:"endCursor"`
}

// GetHasNextPage returns GetRepositoryRepositoryIssuesIssueConnectionPageInfo.HasNextPage, and is useful for accessing the field via an interface.
func (v *GetRepositoryRepositoryIssuesIssueConnectionPageInfo) GetHasNextPage() bool {
	return v.HasNextPage
}

// GetEndCursor returns GetRepositoryRepositoryIssuesIssueConnectionPageInfo.EndCursor, and is useful for accessing the field via an interface.
func (v *GetRepositoryRepositoryIssuesIssueConnectionPageInfo) GetEndCursor() string {
	return v.EndCursor
}

// GetRepositoryResponse is returned by GetRepository on success.
type GetRepositoryResponse struct {
	Repository GetRepositoryRepository `json:"repository"`
}

// GetRepository returns GetRepositoryResponse.Repository, and is useful for accessing the field via an interface.
func (v *GetRepositoryResponse) GetRepository() GetRepositoryRepository { return v.Repository }

type RepositoryVisibility string

const (
	RepositoryVisibilityPrivate RepositoryVisibility = "PRIVATE"
	RepositoryVisibilityPublic  RepositoryVisibility = "PUBLIC"
)

var AllRepositoryVisibility = []RepositoryVisibility{
	RepositoryVisibilityPrivate,
	RepositoryVisibilityPublic,
}

// SearchResponse is returned by Search on success.
type SearchResponse struct {
	Search []SearchSearchSearchResultItem `json:"-"`
}

// GetSearch returns SearchResponse.Search, and is useful for accessing the field via an interface.
func (v *SearchResponse) GetSearch() []SearchSearchSearchResultItem { return v.Search }

func (v *SearchResponse) UnmarshalJSON(b []byte) error {

	if string(b) == "null" {
		return nil
	}

	var firstPass struct {
		*SearchResponse
		Search []json.RawMessage `json:"search"`
		octoql.NoUnmarshalJSON
	}
	firstPass.SearchResponse = v

	err := json.Unmarshal(b, &firstPass)
	if err != nil {
		return err
	}

	{
		dst := &v.Search
		src := firstPass.Search
		*dst = make(
			[]SearchSearchSearchResultItem,
			len(src))
		for i, src := range src {
			dst := &(*dst)[i]
			if len(src) != 0 && string(src) != "null" {
				err = __unmarshalSearchSearchSearchResultItem(
					src, dst)
				if err != nil {
					return fmt.Errorf(
						"unable to unmarshal SearchResponse.Search: %w", err)
				}
			}
		}
	}
	return nil
}

type __premarshalSearchResponse struct {
	Search []json.RawMessage `json:"search"`
}

func (v *SearchResponse) MarshalJSON() ([]byte, error) {
	premarshaled, err := v.__premarshalJSON()
	if err != nil {
		return nil, err
	}
	return json.Marshal(premarshaled)
}

func (v *SearchResponse) __premarshalJSON() (*__premarshalSearchResponse, error) {
	var retval __premarshalSearchResponse

	{

		dst := &retval.Search
		src := v.Search
		*dst = make(
			[]json.RawMessage,
			len(src))
		for i, src := range src {
			dst := &(*dst)[i]
			var err error
			*dst, err = __marshalSearchSearchSearchResultItem(
				&src)
			if err != nil {
				return nil, fmt.Errorf(
					"unable to marshal SearchResponse.Search: %w", err)
			}
		}
	}
	return &retval, nil
}

// SearchSearchIssue includes the requested fields of the GraphQL type Issue.
type SearchSearchIssue struct {
	Typename string `json:"__typename"`
	Id       string `json:"id"`
	Title    string `json:"title"`
}

// GetTypename returns SearchSearchIssue.Typename, and is useful for accessing the field via an interface.
func (v *SearchSearchIssue) GetTypename() string { return v.Typename }

// GetId returns SearchSearchIssue.Id, and is useful for accessing the field via an interface.
func (v *SearchSearchIssue) GetId() string { return v.Id }

// GetTitle returns SearchSearchIssue.Title, and is useful for accessing the field via an interface.
func (v *SearchSearchIssue) GetTitle() string { return v.Title }

// SearchSearchRepository includes the requested fields of the GraphQL type Repository.
type SearchSearchRepository struct {
	Typename      string `json:"__typename"`
	Id            string `json:"id"`
	NameWithOwner string `json:"nameWithOwner"`
}

// GetTypename returns SearchSearchRepository.Typename, and is useful for accessing the field via an interface.
func (v *SearchSearchRepository) GetTypename() string { return v.Typename }

// GetId returns SearchSearchRepository.Id, and is useful for accessing the field via an interface.
func (v *SearchSearchRepository) GetId() string { return v.Id }

// GetNameWithOwner returns SearchSearchRepository.NameWithOwner, and is useful for accessing the field via an interface.
func (v *SearchSearchRepository) GetNameWithOwner() string { return v.NameWithOwner }

// SearchSearchSearchResultItem includes the requested fields of the GraphQL interface SearchResultItem.
//
// SearchSearchSearchResultItem is implemented by the following types:
// SearchSearchIssue
// SearchSearchRepository
// SearchSearchSearchResultItemOctoqlOther
type SearchSearchSearchResultItem interface {
	implementsGraphQLInterfaceSearchSearchSearchResultItem()
	// GetTypename returns the receiver's concrete GraphQL type-name (see interface doc for possible values).
	GetTypename() string
}

func (v *SearchSearchIssue) implementsGraphQLInterfaceSearchSearchSearchResultItem()      {}
func (v *SearchSearchRepository) implementsGraphQLInterfaceSearchSearchSearchResultItem() {}
func (v *SearchSearchSearchResultItemOctoqlOther) implementsGraphQLInterfaceSearchSearchSearchResultItem() {
}

func __unmarshalSearchSearchSearchResultItem(b []byte, v *SearchSearchSearchResultItem) error {
	if string(b) == "null" {
		return nil
	}

	var tn struct {
		TypeName string `json:"__typename"`
	}
	err := json.Unmarshal(b, &tn)
	if err != nil {
		return err
	}

	switch tn.TypeName {
	case "Issue":
		*v = new(SearchSearchIssue)
		return json.Unmarshal(b, *v)
	case "Repository":
		*v = new(SearchSearchRepository)
		return json.Unmarshal(b, *v)
	case "":
		return fmt.Errorf(
			"response was missing SearchResultItem.__typename")
	default:
		*v = new(SearchSearchSearchResultItemOctoqlOther)
		return json.Unmarshal(b, *v)
	}
}

func __marshalSearchSearchSearchResultItem(v *SearchSearchSearchResultItem) ([]byte, error) {

	var typename string
	switch v := (*v).(type) {
	case *SearchSearchIssue:
		typename = "Issue"

		result := struct {
			TypeName string `json:"__typename"`
			*SearchSearchIssue
		}{typename, v}
		return json.Marshal(result)
	case *SearchSearchRepository:
		typename = "Repository"

		result := struct {
			TypeName string `json:"__typename"`
			*SearchSearchRepository
		}{typename, v}
		return json.Marshal(result)
	case *SearchSearchSearchResultItemOctoqlOther:
		return json.Marshal(v)
	case nil:
		return []byte("null"), nil
	default:
		return nil, fmt.Errorf(
			`unexpected concrete type for SearchSearchSearchResultItem: "%T"`, v)
	}
}

// SearchSearchSearchResultItemOctoqlOther represents SearchSearchSearchResultItem implementations not explicitly selected by a fragment. Use GetTypename to identify the concrete GraphQL type.
type SearchSearchSearchResultItemOctoqlOther struct {
	Typename string `json:"__typename"`
}

// GetTypename returns SearchSearchSearchResultItemOctoqlOther.Typename, and is useful for accessing the field via an interface.
func (v *SearchSearchSearchResultItemOctoqlOther) GetTypename() string { return v.Typename }

// ViewerResponse is returned by Viewer on success.
type ViewerResponse struct {
	Viewer ViewerViewerUser `json:"viewer"`
}

// GetViewer returns ViewerResponse.Viewer, and is useful for accessing the field via an interface.
func (v *ViewerResponse) GetViewer() ViewerViewerUser { return v.Viewer }

// ViewerVariables includes the GraphQL fields of User requested by the fragment ViewerVariables.
type ViewerVariables struct {
	Id    string `json:"id"`
	Login string `json:"login"`
}

// GetId returns ViewerVariables.Id, and is useful for accessing the field via an interface.
func (v *ViewerVariables) GetId() string { return v.Id }

// GetLogin returns ViewerVariables.Login, and is useful for accessing the field via an interface.
func (v *ViewerVariables) GetLogin() string { return v.Login }

// ViewerViewerUser includes the requested fields of the GraphQL type User.
type ViewerViewerUser struct {
	ViewerVariables `json:"-"`
}

// GetId returns ViewerViewerUser.Id, and is useful for accessing the field via an interface.
func (v *ViewerViewerUser) GetId() string { return v.ViewerVariables.Id }

// GetLogin returns ViewerViewerUser.Login, and is useful for accessing the field via an interface.
func (v *ViewerViewerUser) GetLogin() string { return v.ViewerVariables.Login }

func (v *ViewerViewerUser) UnmarshalJSON(b []byte) error {

	if string(b) == "null" {
		return nil
	}

	var firstPass struct {
		*ViewerViewerUser
		octoql.NoUnmarshalJSON
	}
	firstPass.ViewerViewerUser = v

	err := json.Unmarshal(b, &firstPass)
	if err != nil {
		return err
	}

	err = json.Unmarshal(
		b, &v.ViewerVariables)
	if err != nil {
		return err
	}
	return nil
}

type __premarshalViewerViewerUser struct {
	Id string `json:"id"`

	Login string `json:"login"`
}

func (v *ViewerViewerUser) MarshalJSON() ([]byte, error) {
	premarshaled, err := v.__premarshalJSON()
	if err != nil {
		return nil, err
	}
	return json.Marshal(premarshaled)
}

func (v *ViewerViewerUser) __premarshalJSON() (*__premarshalViewerViewerUser, error) {
	var retval __premarshalViewerViewerUser

	retval.Id = v.ViewerVariables.Id
	retval.Login = v.ViewerVariables.Login
	return &retval, nil
}

// __CreateRepositoryInput is used internally by octoqlgen
type __CreateRepositoryInput struct {
	Input CreateRepositoryInput `json:"input"`
}

// GetInput returns __CreateRepositoryInput.Input, and is useful for accessing the field via an interface.
func (v *__CreateRepositoryInput) GetInput() CreateRepositoryInput { return v.Input }

// __EchoAnyInput is used internally by octoqlgen
type __EchoAnyInput struct {
	Value any `json:"value"`
}

// GetValue returns __EchoAnyInput.Value, and is useful for accessing the field via an interface.
func (v *__EchoAnyInput) GetValue() any { return v.Value }

// __EchoAtInput is used internally by octoqlgen
type __EchoAtInput struct {
	Value time.Time `json:"value"`
}

// GetValue returns __EchoAtInput.Value, and is useful for accessing the field via an interface.
func (v *__EchoAtInput) GetValue() time.Time { return v.Value }

// __EchoPropertyInput is used internally by octoqlgen
type __EchoPropertyInput struct {
	Value json.RawMessage `json:"value"`
}

// GetValue returns __EchoPropertyInput.Value, and is useful for accessing the field via an interface.
func (v *__EchoPropertyInput) GetValue() json.RawMessage { return v.Value }

// __GetNodeInput is used internally by octoqlgen
type __GetNodeInput struct {
	Id string `json:"id"`
}

// GetId returns __GetNodeInput.Id, and is useful for accessing the field via an interface.
func (v *__GetNodeInput) GetId() string { return v.Id }

// __GetRepositoryInput is used internally by octoqlgen
type __GetRepositoryInput struct {
	Owner string `json:"owner"`
	Name  string `json:"name"`
	First int    `json:"first"`
	After string `json:"after"`
}

// GetOwner returns __GetRepositoryInput.Owner, and is useful for accessing the field via an interface.
func (v *__GetRepositoryInput) GetOwner() string { return v.Owner }

// GetName returns __GetRepositoryInput.Name, and is useful for accessing the field via an interface.
func (v *__GetRepositoryInput) GetName() string { return v.Name }

// GetFirst returns __GetRepositoryInput.First, and is useful for accessing the field via an interface.
func (v *__GetRepositoryInput) GetFirst() int { return v.First }

// GetAfter returns __GetRepositoryInput.After, and is useful for accessing the field via an interface.
func (v *__GetRepositoryInput) GetAfter() string { return v.After }

// __SearchInput is used internally by octoqlgen
type __SearchInput struct {
	Query string `json:"query"`
}

// GetQuery returns __SearchInput.Query, and is useful for accessing the field via an interface.
func (v *__SearchInput) GetQuery() string { return v.Query }

type CreateRepositoryVariables = __CreateRepositoryInput

type EchoAnyVariables = __EchoAnyInput

type EchoAtVariables = __EchoAtInput

type EchoPropertyVariables = __EchoPropertyInput

type GetNodeVariables = __GetNodeInput

type GetRepositoryVariables = __GetRepositoryInput

type SearchVariables = __SearchInput

type testTB interface {
	Cleanup(func())
	Errorf(string, ...any)
}

type graphqlRequest struct {
	OperationName string          `json:"operationName"`
	Variables     json.RawMessage `json:"variables"`
}

type operationResult[V any] func(V, http.ResponseWriter) error

type expectationOptions struct {
	remaining int
	atLeast   bool
}

type ExpectOption func(*expectationOptions)

func Times(count int) ExpectOption {
	return func(options *expectationOptions) {
		options.remaining = count
		options.atLeast = false
	}
}

func MinTimes(count int) ExpectOption {
	return func(options *expectationOptions) {
		options.remaining = count
		options.atLeast = true
	}
}

type expectation[V any] struct {
	variables    V
	variablesKey string
	result       operationResult[V]
	remaining    int
	atLeast      bool
}

type expectationSet[V any] struct {
	mu           sync.Mutex
	tb           testTB
	operation    string
	expectations []*expectation[V]
	fallback     *expectation[V]
}

func (set *expectationSet[V]) expect(
	variables V,
	options ...ExpectOption,
) *expectation[V] {
	config := expectationOptions{remaining: 1}
	for _, option := range options {
		if option != nil {
			option(&config)
		}
	}
	if config.remaining < 0 {
		set.tb.Errorf(
			"%s expectation count must not be negative: %d",
			set.operation,
			config.remaining,
		)
		config.remaining = 0
	}
	key, err := variableKey(variables)
	if err != nil {
		set.tb.Errorf("%s expectation variables: %v", set.operation, err)
		config.remaining = 0
	}

	expected := &expectation[V]{
		variables:    variables,
		variablesKey: key,
		remaining:    config.remaining,
		atLeast:      config.atLeast,
	}
	set.mu.Lock()
	set.expectations = append(set.expectations, expected)
	set.mu.Unlock()
	return expected
}

func (set *expectationSet[V]) expectDefault() *expectation[V] {
	expected := &expectation[V]{
		atLeast: true,
	}
	set.mu.Lock()
	set.fallback = expected
	set.mu.Unlock()
	return expected
}

func (set *expectationSet[V]) setResult(
	expected *expectation[V],
	result operationResult[V],
) {
	set.mu.Lock()
	expected.result = result
	set.mu.Unlock()
}

func (set *expectationSet[V]) match(
	variables V,
	rawVariables []byte,
) (operationResult[V], error) {
	key, err := variableKeyJSON(rawVariables)
	if err != nil {
		return nil, fmt.Errorf("%s variables: %w", set.operation, err)
	}

	set.mu.Lock()
	defer set.mu.Unlock()

	for _, expected := range set.expectations {
		if expected.remaining == 0 && !expected.atLeast {
			continue
		}
		if expected.variablesKey != key {
			continue
		}
		if expected.remaining > 0 {
			expected.remaining--
		}
		if expected.result == nil {
			return nil, fmt.Errorf(
				"%s expectation for variables %+v has no response",
				set.operation,
				variables,
			)
		}
		return expected.result, nil
	}

	if set.fallback != nil {
		if set.fallback.result == nil {
			return nil, fmt.Errorf(
				"%s default expectation has no response",
				set.operation,
			)
		}
		return set.fallback.result, nil
	}

	return nil, fmt.Errorf(
		"no expectation found for %s variables %+v",
		set.operation,
		variables,
	)
}

func (set *expectationSet[V]) reset(variables ...V) {
	set.mu.Lock()
	defer set.mu.Unlock()

	if len(variables) == 0 {
		for _, expected := range set.expectations {
			expected.remaining = 0
		}
		set.expectations = []*expectation[V]{}
		set.fallback = nil
		return
	}

	keys := make([]string, 0, len(variables))
	for _, variablesToReset := range variables {
		key, err := variableKey(variablesToReset)
		if err != nil {
			set.tb.Errorf("%s reset variables: %v", set.operation, err)
			continue
		}
		keys = append(keys, key)
	}

	retained := make([]*expectation[V], 0, len(set.expectations))
	for _, expected := range set.expectations {
		shouldReset := false
		for _, key := range keys {
			if expected.variablesKey == key {
				shouldReset = true
				break
			}
		}

		if shouldReset {
			expected.remaining = 0
			continue
		}
		retained = append(retained, expected)
	}
	set.expectations = retained
}

func variableKey[V any](variables V) (string, error) {
	encoded, err := json.Marshal(variables)
	if err != nil {
		return "", fmt.Errorf("encoding variables: %w", err)
	}
	return variableKeyJSON(encoded)
}

func variableKeyJSON(encoded []byte) (string, error) {
	decoder := json.NewDecoder(bytes.NewReader(encoded))
	decoder.UseNumber()
	var value any
	err := decoder.Decode(&value)
	if err != nil {
		return "", fmt.Errorf("decoding variables: %w", err)
	}
	normalized, err := json.Marshal(value)
	if err != nil {
		return "", fmt.Errorf("normalizing variables: %w", err)
	}
	return string(normalized), nil
}

func decodeVariables(encoded []byte, destination any) error {
	decoder := json.NewDecoder(bytes.NewReader(encoded))
	decoder.UseNumber()
	err := decoder.Decode(destination)
	if err != nil {
		return fmt.Errorf("decoding variables: %w", err)
	}
	return nil
}

func (set *expectationSet[V]) verify() {
	set.mu.Lock()
	defer set.mu.Unlock()

	for _, expected := range set.expectations {
		if expected.remaining > 0 {
			set.tb.Errorf(
				"unmet %s expectation for variables %+v: %d call(s) remaining",
				set.operation,
				expected.variables,
				expected.remaining,
			)
		}
	}
}

type responseOptions struct {
	status     int
	header     http.Header
	extensions map[string]any
	err        error
}

type ResponseOption func(*responseOptions)

func WithStatus(status int) ResponseOption {
	return func(options *responseOptions) {
		if status < 100 || status > 999 {
			options.err = fmt.Errorf("invalid http status %d", status)
			return
		}
		options.status = status
	}
}

func WithHeader(name string, values ...string) ResponseOption {
	clonedValues := append([]string{}, values...)
	return func(options *responseOptions) {
		options.header[name] = append([]string{}, clonedValues...)
	}
}

func WithHeaders(header http.Header) ResponseOption {
	clonedHeader := header.Clone()
	return func(options *responseOptions) {
		for name, values := range clonedHeader {
			options.header[name] = append([]string{}, values...)
		}
	}
}

func WithExtensions(extensions map[string]any) ResponseOption {
	clonedExtensions := make(map[string]any, len(extensions))
	for name, value := range extensions {
		clonedExtensions[name] = value
	}
	return func(options *responseOptions) {
		options.extensions = make(map[string]any, len(clonedExtensions))
		for name, value := range clonedExtensions {
			options.extensions[name] = value
		}
	}
}

func WithPrimaryRateLimit(rateLimit octoql.RateLimit) ResponseOption {
	return func(options *responseOptions) {
		hasNegativeValue := rateLimit.Limit < 0 ||
			rateLimit.Remaining < 0 ||
			rateLimit.Used < 0
		if hasNegativeValue {
			options.err = fmt.Errorf("primary rate limit values must not be negative")
			return
		}

		options.header.Set("X-RateLimit-Limit", strconv.Itoa(rateLimit.Limit))
		options.header.Set("X-RateLimit-Remaining", strconv.Itoa(rateLimit.Remaining))
		options.header.Set("X-RateLimit-Used", strconv.Itoa(rateLimit.Used))
		if !rateLimit.Reset.IsZero() {
			options.header.Set(
				"X-RateLimit-Reset",
				strconv.FormatInt(rateLimit.Reset.Unix(), 10),
			)
		}
		if rateLimit.Resource != "" {
			options.header.Set("X-RateLimit-Resource", rateLimit.Resource)
		}
	}
}

func WithSecondaryRateLimit(retryAfter time.Duration) ResponseOption {
	return func(options *responseOptions) {
		if retryAfter < 0 {
			options.err = fmt.Errorf("secondary rate limit retry-after must not be negative")
			return
		}

		seconds := retryAfter / time.Second
		if retryAfter%time.Second != 0 {
			seconds++
		}
		options.header.Set(
			"Retry-After",
			strconv.FormatInt(int64(seconds), 10),
		)
	}
}

func buildResponseOptions(options ...ResponseOption) responseOptions {
	config := responseOptions{
		status: http.StatusOK,
		header: http.Header{},
	}
	for _, option := range options {
		if option != nil {
			option(&config)
		}
	}
	return config
}

func combineResponseOptions(
	base []ResponseOption,
	additional []ResponseOption,
) []ResponseOption {
	combined := make([]ResponseOption, 0, len(base)+len(additional))
	combined = append(combined, base...)
	combined = append(combined, additional...)
	return combined
}

func writeGraphQLResponse(
	writer http.ResponseWriter,
	data any,
	graphqlErrors []octoql.Error,
	options responseOptions,
) error {
	if options.err != nil {
		return options.err
	}

	for name, values := range options.header {
		writer.Header()[name] = append([]string{}, values...)
	}
	writer.Header().Set("Content-Type", "application/json")

	payload := map[string]any{}
	if data != nil {
		payload["data"] = data
	}
	if graphqlErrors != nil {
		payload["errors"] = graphqlErrors
	}
	if options.extensions != nil {
		payload["extensions"] = options.extensions
	}

	writer.WriteHeader(options.status)
	err := json.NewEncoder(writer).Encode(payload)
	if err != nil {
		return fmt.Errorf("encoding graphql response: %w", err)
	}
	return nil
}

func writeRequestError(
	writer http.ResponseWriter,
	status int,
	message string,
) error {
	return writeGraphQLResponse(
		writer,
		nil,
		[]octoql.Error{{Message: message}},
		buildResponseOptions(WithStatus(status)),
	)
}

type TestHandler struct {
	tb         testTB
	operation0 expectationSet[CreateRepositoryVariables]
	operation1 expectationSet[EchoAnyVariables]
	operation2 expectationSet[EchoAtVariables]
	operation3 expectationSet[EchoPropertyVariables]
	operation4 expectationSet[GetNodeVariables]
	operation5 expectationSet[GetRepositoryVariables]
	operation6 expectationSet[SearchVariables]
	operation7 expectationSet[struct{}]
}

var _ http.Handler = (*TestHandler)(nil)

func NewTestHandler(testingTB testing.TB) *TestHandler {
	return newTestHandler(testingTB)
}

func newTestHandler(testingTB testTB) *TestHandler {
	handler := &TestHandler{tb: testingTB}
	handler.operation0 = expectationSet[CreateRepositoryVariables]{
		tb:           testingTB,
		operation:    "CreateRepository",
		expectations: []*expectation[CreateRepositoryVariables]{},
	}
	handler.operation1 = expectationSet[EchoAnyVariables]{
		tb:           testingTB,
		operation:    "EchoAny",
		expectations: []*expectation[EchoAnyVariables]{},
	}
	handler.operation2 = expectationSet[EchoAtVariables]{
		tb:           testingTB,
		operation:    "EchoAt",
		expectations: []*expectation[EchoAtVariables]{},
	}
	handler.operation3 = expectationSet[EchoPropertyVariables]{
		tb:           testingTB,
		operation:    "EchoProperty",
		expectations: []*expectation[EchoPropertyVariables]{},
	}
	handler.operation4 = expectationSet[GetNodeVariables]{
		tb:           testingTB,
		operation:    "GetNode",
		expectations: []*expectation[GetNodeVariables]{},
	}
	handler.operation5 = expectationSet[GetRepositoryVariables]{
		tb:           testingTB,
		operation:    "GetRepository",
		expectations: []*expectation[GetRepositoryVariables]{},
	}
	handler.operation6 = expectationSet[SearchVariables]{
		tb:           testingTB,
		operation:    "Search",
		expectations: []*expectation[SearchVariables]{},
	}
	handler.operation7 = expectationSet[struct{}]{
		tb:           testingTB,
		operation:    "Viewer",
		expectations: []*expectation[struct{}]{},
	}
	testingTB.Cleanup(handler.verify)
	return handler
}

func (handler *TestHandler) verify() {
	handler.operation0.verify()
	handler.operation1.verify()
	handler.operation2.verify()
	handler.operation3.verify()
	handler.operation4.verify()
	handler.operation5.verify()
	handler.operation6.verify()
	handler.operation7.verify()
}

func (handler *TestHandler) Reset() {
	handler.operation0.reset()
	handler.operation1.reset()
	handler.operation2.reset()
	handler.operation3.reset()
	handler.operation4.reset()
	handler.operation5.reset()
	handler.operation6.reset()
	handler.operation7.reset()
}

func (handler *TestHandler) ServeHTTP(
	writer http.ResponseWriter,
	request *http.Request,
) {
	if request.Method != http.MethodPost {
		writer.Header().Set("Allow", http.MethodPost)
		err := writeRequestError(
			writer,
			http.StatusMethodNotAllowed,
			"graphql requests must use POST",
		)
		if err != nil {
			handler.tb.Errorf("writing method error response: %v", err)
		}
		return
	}

	decoder := json.NewDecoder(
		http.MaxBytesReader(writer, request.Body, 8<<20),
	)
	var graphqlRequest graphqlRequest
	err := decoder.Decode(&graphqlRequest)
	if err != nil {
		writeErr := writeRequestError(
			writer,
			http.StatusBadRequest,
			"decoding graphql request: "+err.Error(),
		)
		if writeErr != nil {
			handler.tb.Errorf("writing decode error response: %v", writeErr)
		}
		return
	}

	var extra any
	err = decoder.Decode(&extra)
	if !errors.Is(err, io.EOF) {
		if err == nil {
			err = fmt.Errorf("multiple json values")
		}
		writeErr := writeRequestError(
			writer,
			http.StatusBadRequest,
			"decoding graphql request: "+err.Error(),
		)
		if writeErr != nil {
			handler.tb.Errorf("writing trailing data error response: %v", writeErr)
		}
		return
	}

	if graphqlRequest.OperationName == "" {
		err = writeRequestError(
			writer,
			http.StatusBadRequest,
			"graphql request is missing operationName",
		)
		if err != nil {
			handler.tb.Errorf("writing missing operation error response: %v", err)
		}
		return
	}
	if len(graphqlRequest.Variables) == 0 {
		graphqlRequest.Variables = json.RawMessage("{}")
	}

	switch graphqlRequest.OperationName {
	case "CreateRepository":
		var variables CreateRepositoryVariables
		err = decodeVariables(graphqlRequest.Variables, &variables)
		if err != nil {
			handler.tb.Errorf("decoding CreateRepository variables: %v", err)
			writeErr := writeRequestError(
				writer,
				http.StatusOK,
				"decoding CreateRepository variables: "+err.Error(),
			)
			if writeErr != nil {
				handler.tb.Errorf("writing CreateRepository variable error response: %v", writeErr)
			}
			return
		}

		result, matchErr := handler.operation0.match(
			variables,
			graphqlRequest.Variables,
		)
		if matchErr != nil {
			handler.tb.Errorf("%v", matchErr)
			writeErr := writeRequestError(
				writer,
				http.StatusOK,
				matchErr.Error(),
			)
			if writeErr != nil {
				handler.tb.Errorf("writing CreateRepository expectation error response: %v", writeErr)
			}
			return
		}
		err = result(variables, writer)
		if err != nil {
			handler.tb.Errorf("serving CreateRepository response: %v", err)
		}
	case "EchoAny":
		var variables EchoAnyVariables
		err = decodeVariables(graphqlRequest.Variables, &variables)
		if err != nil {
			handler.tb.Errorf("decoding EchoAny variables: %v", err)
			writeErr := writeRequestError(
				writer,
				http.StatusOK,
				"decoding EchoAny variables: "+err.Error(),
			)
			if writeErr != nil {
				handler.tb.Errorf("writing EchoAny variable error response: %v", writeErr)
			}
			return
		}

		result, matchErr := handler.operation1.match(
			variables,
			graphqlRequest.Variables,
		)
		if matchErr != nil {
			handler.tb.Errorf("%v", matchErr)
			writeErr := writeRequestError(
				writer,
				http.StatusOK,
				matchErr.Error(),
			)
			if writeErr != nil {
				handler.tb.Errorf("writing EchoAny expectation error response: %v", writeErr)
			}
			return
		}
		err = result(variables, writer)
		if err != nil {
			handler.tb.Errorf("serving EchoAny response: %v", err)
		}
	case "EchoAt":
		var variables EchoAtVariables
		err = decodeVariables(graphqlRequest.Variables, &variables)
		if err != nil {
			handler.tb.Errorf("decoding EchoAt variables: %v", err)
			writeErr := writeRequestError(
				writer,
				http.StatusOK,
				"decoding EchoAt variables: "+err.Error(),
			)
			if writeErr != nil {
				handler.tb.Errorf("writing EchoAt variable error response: %v", writeErr)
			}
			return
		}

		result, matchErr := handler.operation2.match(
			variables,
			graphqlRequest.Variables,
		)
		if matchErr != nil {
			handler.tb.Errorf("%v", matchErr)
			writeErr := writeRequestError(
				writer,
				http.StatusOK,
				matchErr.Error(),
			)
			if writeErr != nil {
				handler.tb.Errorf("writing EchoAt expectation error response: %v", writeErr)
			}
			return
		}
		err = result(variables, writer)
		if err != nil {
			handler.tb.Errorf("serving EchoAt response: %v", err)
		}
	case "EchoProperty":
		var variables EchoPropertyVariables
		err = decodeVariables(graphqlRequest.Variables, &variables)
		if err != nil {
			handler.tb.Errorf("decoding EchoProperty variables: %v", err)
			writeErr := writeRequestError(
				writer,
				http.StatusOK,
				"decoding EchoProperty variables: "+err.Error(),
			)
			if writeErr != nil {
				handler.tb.Errorf("writing EchoProperty variable error response: %v", writeErr)
			}
			return
		}

		result, matchErr := handler.operation3.match(
			variables,
			graphqlRequest.Variables,
		)
		if matchErr != nil {
			handler.tb.Errorf("%v", matchErr)
			writeErr := writeRequestError(
				writer,
				http.StatusOK,
				matchErr.Error(),
			)
			if writeErr != nil {
				handler.tb.Errorf("writing EchoProperty expectation error response: %v", writeErr)
			}
			return
		}
		err = result(variables, writer)
		if err != nil {
			handler.tb.Errorf("serving EchoProperty response: %v", err)
		}
	case "GetNode":
		var variables GetNodeVariables
		err = decodeVariables(graphqlRequest.Variables, &variables)
		if err != nil {
			handler.tb.Errorf("decoding GetNode variables: %v", err)
			writeErr := writeRequestError(
				writer,
				http.StatusOK,
				"decoding GetNode variables: "+err.Error(),
			)
			if writeErr != nil {
				handler.tb.Errorf("writing GetNode variable error response: %v", writeErr)
			}
			return
		}

		result, matchErr := handler.operation4.match(
			variables,
			graphqlRequest.Variables,
		)
		if matchErr != nil {
			handler.tb.Errorf("%v", matchErr)
			writeErr := writeRequestError(
				writer,
				http.StatusOK,
				matchErr.Error(),
			)
			if writeErr != nil {
				handler.tb.Errorf("writing GetNode expectation error response: %v", writeErr)
			}
			return
		}
		err = result(variables, writer)
		if err != nil {
			handler.tb.Errorf("serving GetNode response: %v", err)
		}
	case "GetRepository":
		var variables GetRepositoryVariables
		err = decodeVariables(graphqlRequest.Variables, &variables)
		if err != nil {
			handler.tb.Errorf("decoding GetRepository variables: %v", err)
			writeErr := writeRequestError(
				writer,
				http.StatusOK,
				"decoding GetRepository variables: "+err.Error(),
			)
			if writeErr != nil {
				handler.tb.Errorf("writing GetRepository variable error response: %v", writeErr)
			}
			return
		}

		result, matchErr := handler.operation5.match(
			variables,
			graphqlRequest.Variables,
		)
		if matchErr != nil {
			handler.tb.Errorf("%v", matchErr)
			writeErr := writeRequestError(
				writer,
				http.StatusOK,
				matchErr.Error(),
			)
			if writeErr != nil {
				handler.tb.Errorf("writing GetRepository expectation error response: %v", writeErr)
			}
			return
		}
		err = result(variables, writer)
		if err != nil {
			handler.tb.Errorf("serving GetRepository response: %v", err)
		}
	case "Search":
		var variables SearchVariables
		err = decodeVariables(graphqlRequest.Variables, &variables)
		if err != nil {
			handler.tb.Errorf("decoding Search variables: %v", err)
			writeErr := writeRequestError(
				writer,
				http.StatusOK,
				"decoding Search variables: "+err.Error(),
			)
			if writeErr != nil {
				handler.tb.Errorf("writing Search variable error response: %v", writeErr)
			}
			return
		}

		result, matchErr := handler.operation6.match(
			variables,
			graphqlRequest.Variables,
		)
		if matchErr != nil {
			handler.tb.Errorf("%v", matchErr)
			writeErr := writeRequestError(
				writer,
				http.StatusOK,
				matchErr.Error(),
			)
			if writeErr != nil {
				handler.tb.Errorf("writing Search expectation error response: %v", writeErr)
			}
			return
		}
		err = result(variables, writer)
		if err != nil {
			handler.tb.Errorf("serving Search response: %v", err)
		}
	case "Viewer":
		var variables struct{}
		err = decodeVariables(graphqlRequest.Variables, &variables)
		if err != nil {
			handler.tb.Errorf("decoding Viewer variables: %v", err)
			writeErr := writeRequestError(
				writer,
				http.StatusOK,
				"decoding Viewer variables: "+err.Error(),
			)
			if writeErr != nil {
				handler.tb.Errorf("writing Viewer variable error response: %v", writeErr)
			}
			return
		}

		result, matchErr := handler.operation7.match(
			variables,
			graphqlRequest.Variables,
		)
		if matchErr != nil {
			handler.tb.Errorf("%v", matchErr)
			writeErr := writeRequestError(
				writer,
				http.StatusOK,
				matchErr.Error(),
			)
			if writeErr != nil {
				handler.tb.Errorf("writing Viewer expectation error response: %v", writeErr)
			}
			return
		}
		err = result(variables, writer)
		if err != nil {
			handler.tb.Errorf("serving Viewer response: %v", err)
		}
	default:
		err = writeRequestError(
			writer,
			http.StatusOK,
			"unknown operation: "+graphqlRequest.OperationName,
		)
		if err != nil {
			handler.tb.Errorf("writing unknown operation response: %v", err)
		}
	}
}

type CreateRepositoryExpectation struct {
	set      *expectationSet[CreateRepositoryVariables]
	expected *expectation[CreateRepositoryVariables]
	options  []ResponseOption
}

func (handler *TestHandler) ExpectCreateRepository(
	variables CreateRepositoryVariables,
	options ...ExpectOption,
) *CreateRepositoryExpectation {
	return &CreateRepositoryExpectation{
		set: &handler.operation0,
		expected: handler.operation0.expect(
			variables,
			options...,
		),
		options: []ResponseOption{},
	}
}

func (handler *TestHandler) DefaultCreateRepository() *CreateRepositoryExpectation {
	return &CreateRepositoryExpectation{
		set:      &handler.operation0,
		expected: handler.operation0.expectDefault(),
		options:  []ResponseOption{},
	}
}

func (handler *TestHandler) ResetCreateRepository(variables ...CreateRepositoryVariables) {
	handler.operation0.reset(variables...)
}

func (builder *CreateRepositoryExpectation) WithOptions(
	options ...ResponseOption,
) *CreateRepositoryExpectation {
	builder.options = combineResponseOptions(builder.options, options)
	return builder
}

func (builder *CreateRepositoryExpectation) Respond(
	data CreateRepositoryResponse,
	options ...ResponseOption,
) {
	combined := combineResponseOptions(builder.options, options)
	responseConfig := buildResponseOptions(combined...)
	builder.set.setResult(
		builder.expected,
		func(_ CreateRepositoryVariables, writer http.ResponseWriter) error {
			return writeGraphQLResponse(writer, &data, nil, responseConfig)
		},
	)
}

func (builder *CreateRepositoryExpectation) RespondError(
	graphqlError octoql.Error,
	options ...ResponseOption,
) {
	combined := combineResponseOptions(builder.options, options)
	responseConfig := buildResponseOptions(combined...)
	builder.set.setResult(
		builder.expected,
		func(_ CreateRepositoryVariables, writer http.ResponseWriter) error {
			return writeGraphQLResponse(
				writer,
				nil,
				[]octoql.Error{graphqlError},
				responseConfig,
			)
		},
	)
}

func (builder *CreateRepositoryExpectation) RespondDataAndErrors(
	data CreateRepositoryResponse,
	graphqlErrors ...octoql.Error,
) {
	responseConfig := buildResponseOptions(builder.options...)
	builder.set.setResult(
		builder.expected,
		func(_ CreateRepositoryVariables, writer http.ResponseWriter) error {
			return writeGraphQLResponse(
				writer,
				&data,
				graphqlErrors,
				responseConfig,
			)
		},
	)
}

func (builder *CreateRepositoryExpectation) Handle(
	handler func(CreateRepositoryVariables, http.ResponseWriter),
) {
	if handler == nil {
		builder.set.tb.Errorf("CreateRepository dynamic handler must not be nil")
		builder.set.setResult(
			builder.expected,
			func(_ CreateRepositoryVariables, _ http.ResponseWriter) error {
				return fmt.Errorf("CreateRepository dynamic handler is nil")
			},
		)
		return
	}
	builder.set.setResult(
		builder.expected,
		func(variables CreateRepositoryVariables, writer http.ResponseWriter) error {
			handler(variables, writer)
			return nil
		},
	)
}

type EchoAnyExpectation struct {
	set      *expectationSet[EchoAnyVariables]
	expected *expectation[EchoAnyVariables]
	options  []ResponseOption
}

func (handler *TestHandler) ExpectEchoAny(
	variables EchoAnyVariables,
	options ...ExpectOption,
) *EchoAnyExpectation {
	return &EchoAnyExpectation{
		set: &handler.operation1,
		expected: handler.operation1.expect(
			variables,
			options...,
		),
		options: []ResponseOption{},
	}
}

func (handler *TestHandler) DefaultEchoAny() *EchoAnyExpectation {
	return &EchoAnyExpectation{
		set:      &handler.operation1,
		expected: handler.operation1.expectDefault(),
		options:  []ResponseOption{},
	}
}

func (handler *TestHandler) ResetEchoAny(variables ...EchoAnyVariables) {
	handler.operation1.reset(variables...)
}

func (builder *EchoAnyExpectation) WithOptions(
	options ...ResponseOption,
) *EchoAnyExpectation {
	builder.options = combineResponseOptions(builder.options, options)
	return builder
}

func (builder *EchoAnyExpectation) Respond(
	data EchoAnyResponse,
	options ...ResponseOption,
) {
	combined := combineResponseOptions(builder.options, options)
	responseConfig := buildResponseOptions(combined...)
	builder.set.setResult(
		builder.expected,
		func(_ EchoAnyVariables, writer http.ResponseWriter) error {
			return writeGraphQLResponse(writer, &data, nil, responseConfig)
		},
	)
}

func (builder *EchoAnyExpectation) RespondError(
	graphqlError octoql.Error,
	options ...ResponseOption,
) {
	combined := combineResponseOptions(builder.options, options)
	responseConfig := buildResponseOptions(combined...)
	builder.set.setResult(
		builder.expected,
		func(_ EchoAnyVariables, writer http.ResponseWriter) error {
			return writeGraphQLResponse(
				writer,
				nil,
				[]octoql.Error{graphqlError},
				responseConfig,
			)
		},
	)
}

func (builder *EchoAnyExpectation) RespondDataAndErrors(
	data EchoAnyResponse,
	graphqlErrors ...octoql.Error,
) {
	responseConfig := buildResponseOptions(builder.options...)
	builder.set.setResult(
		builder.expected,
		func(_ EchoAnyVariables, writer http.ResponseWriter) error {
			return writeGraphQLResponse(
				writer,
				&data,
				graphqlErrors,
				responseConfig,
			)
		},
	)
}

func (builder *EchoAnyExpectation) Handle(
	handler func(EchoAnyVariables, http.ResponseWriter),
) {
	if handler == nil {
		builder.set.tb.Errorf("EchoAny dynamic handler must not be nil")
		builder.set.setResult(
			builder.expected,
			func(_ EchoAnyVariables, _ http.ResponseWriter) error {
				return fmt.Errorf("EchoAny dynamic handler is nil")
			},
		)
		return
	}
	builder.set.setResult(
		builder.expected,
		func(variables EchoAnyVariables, writer http.ResponseWriter) error {
			handler(variables, writer)
			return nil
		},
	)
}

type EchoAtExpectation struct {
	set      *expectationSet[EchoAtVariables]
	expected *expectation[EchoAtVariables]
	options  []ResponseOption
}

func (handler *TestHandler) ExpectEchoAt(
	variables EchoAtVariables,
	options ...ExpectOption,
) *EchoAtExpectation {
	return &EchoAtExpectation{
		set: &handler.operation2,
		expected: handler.operation2.expect(
			variables,
			options...,
		),
		options: []ResponseOption{},
	}
}

func (handler *TestHandler) DefaultEchoAt() *EchoAtExpectation {
	return &EchoAtExpectation{
		set:      &handler.operation2,
		expected: handler.operation2.expectDefault(),
		options:  []ResponseOption{},
	}
}

func (handler *TestHandler) ResetEchoAt(variables ...EchoAtVariables) {
	handler.operation2.reset(variables...)
}

func (builder *EchoAtExpectation) WithOptions(
	options ...ResponseOption,
) *EchoAtExpectation {
	builder.options = combineResponseOptions(builder.options, options)
	return builder
}

func (builder *EchoAtExpectation) Respond(
	data EchoAtResponse,
	options ...ResponseOption,
) {
	combined := combineResponseOptions(builder.options, options)
	responseConfig := buildResponseOptions(combined...)
	builder.set.setResult(
		builder.expected,
		func(_ EchoAtVariables, writer http.ResponseWriter) error {
			return writeGraphQLResponse(writer, &data, nil, responseConfig)
		},
	)
}

func (builder *EchoAtExpectation) RespondError(
	graphqlError octoql.Error,
	options ...ResponseOption,
) {
	combined := combineResponseOptions(builder.options, options)
	responseConfig := buildResponseOptions(combined...)
	builder.set.setResult(
		builder.expected,
		func(_ EchoAtVariables, writer http.ResponseWriter) error {
			return writeGraphQLResponse(
				writer,
				nil,
				[]octoql.Error{graphqlError},
				responseConfig,
			)
		},
	)
}

func (builder *EchoAtExpectation) RespondDataAndErrors(
	data EchoAtResponse,
	graphqlErrors ...octoql.Error,
) {
	responseConfig := buildResponseOptions(builder.options...)
	builder.set.setResult(
		builder.expected,
		func(_ EchoAtVariables, writer http.ResponseWriter) error {
			return writeGraphQLResponse(
				writer,
				&data,
				graphqlErrors,
				responseConfig,
			)
		},
	)
}

func (builder *EchoAtExpectation) Handle(
	handler func(EchoAtVariables, http.ResponseWriter),
) {
	if handler == nil {
		builder.set.tb.Errorf("EchoAt dynamic handler must not be nil")
		builder.set.setResult(
			builder.expected,
			func(_ EchoAtVariables, _ http.ResponseWriter) error {
				return fmt.Errorf("EchoAt dynamic handler is nil")
			},
		)
		return
	}
	builder.set.setResult(
		builder.expected,
		func(variables EchoAtVariables, writer http.ResponseWriter) error {
			handler(variables, writer)
			return nil
		},
	)
}

type EchoPropertyExpectation struct {
	set      *expectationSet[EchoPropertyVariables]
	expected *expectation[EchoPropertyVariables]
	options  []ResponseOption
}

func (handler *TestHandler) ExpectEchoProperty(
	variables EchoPropertyVariables,
	options ...ExpectOption,
) *EchoPropertyExpectation {
	return &EchoPropertyExpectation{
		set: &handler.operation3,
		expected: handler.operation3.expect(
			variables,
			options...,
		),
		options: []ResponseOption{},
	}
}

func (handler *TestHandler) DefaultEchoProperty() *EchoPropertyExpectation {
	return &EchoPropertyExpectation{
		set:      &handler.operation3,
		expected: handler.operation3.expectDefault(),
		options:  []ResponseOption{},
	}
}

func (handler *TestHandler) ResetEchoProperty(variables ...EchoPropertyVariables) {
	handler.operation3.reset(variables...)
}

func (builder *EchoPropertyExpectation) WithOptions(
	options ...ResponseOption,
) *EchoPropertyExpectation {
	builder.options = combineResponseOptions(builder.options, options)
	return builder
}

func (builder *EchoPropertyExpectation) Respond(
	data EchoPropertyResponse,
	options ...ResponseOption,
) {
	combined := combineResponseOptions(builder.options, options)
	responseConfig := buildResponseOptions(combined...)
	builder.set.setResult(
		builder.expected,
		func(_ EchoPropertyVariables, writer http.ResponseWriter) error {
			return writeGraphQLResponse(writer, &data, nil, responseConfig)
		},
	)
}

func (builder *EchoPropertyExpectation) RespondError(
	graphqlError octoql.Error,
	options ...ResponseOption,
) {
	combined := combineResponseOptions(builder.options, options)
	responseConfig := buildResponseOptions(combined...)
	builder.set.setResult(
		builder.expected,
		func(_ EchoPropertyVariables, writer http.ResponseWriter) error {
			return writeGraphQLResponse(
				writer,
				nil,
				[]octoql.Error{graphqlError},
				responseConfig,
			)
		},
	)
}

func (builder *EchoPropertyExpectation) RespondDataAndErrors(
	data EchoPropertyResponse,
	graphqlErrors ...octoql.Error,
) {
	responseConfig := buildResponseOptions(builder.options...)
	builder.set.setResult(
		builder.expected,
		func(_ EchoPropertyVariables, writer http.ResponseWriter) error {
			return writeGraphQLResponse(
				writer,
				&data,
				graphqlErrors,
				responseConfig,
			)
		},
	)
}

func (builder *EchoPropertyExpectation) Handle(
	handler func(EchoPropertyVariables, http.ResponseWriter),
) {
	if handler == nil {
		builder.set.tb.Errorf("EchoProperty dynamic handler must not be nil")
		builder.set.setResult(
			builder.expected,
			func(_ EchoPropertyVariables, _ http.ResponseWriter) error {
				return fmt.Errorf("EchoProperty dynamic handler is nil")
			},
		)
		return
	}
	builder.set.setResult(
		builder.expected,
		func(variables EchoPropertyVariables, writer http.ResponseWriter) error {
			handler(variables, writer)
			return nil
		},
	)
}

type GetNodeExpectation struct {
	set      *expectationSet[GetNodeVariables]
	expected *expectation[GetNodeVariables]
	options  []ResponseOption
}

func (handler *TestHandler) ExpectGetNode(
	variables GetNodeVariables,
	options ...ExpectOption,
) *GetNodeExpectation {
	return &GetNodeExpectation{
		set: &handler.operation4,
		expected: handler.operation4.expect(
			variables,
			options...,
		),
		options: []ResponseOption{},
	}
}

func (handler *TestHandler) DefaultGetNode() *GetNodeExpectation {
	return &GetNodeExpectation{
		set:      &handler.operation4,
		expected: handler.operation4.expectDefault(),
		options:  []ResponseOption{},
	}
}

func (handler *TestHandler) ResetGetNode(variables ...GetNodeVariables) {
	handler.operation4.reset(variables...)
}

func (builder *GetNodeExpectation) WithOptions(
	options ...ResponseOption,
) *GetNodeExpectation {
	builder.options = combineResponseOptions(builder.options, options)
	return builder
}

func (builder *GetNodeExpectation) Respond(
	data GetNodeResponse,
	options ...ResponseOption,
) {
	combined := combineResponseOptions(builder.options, options)
	responseConfig := buildResponseOptions(combined...)
	builder.set.setResult(
		builder.expected,
		func(_ GetNodeVariables, writer http.ResponseWriter) error {
			return writeGraphQLResponse(writer, &data, nil, responseConfig)
		},
	)
}

func (builder *GetNodeExpectation) RespondError(
	graphqlError octoql.Error,
	options ...ResponseOption,
) {
	combined := combineResponseOptions(builder.options, options)
	responseConfig := buildResponseOptions(combined...)
	builder.set.setResult(
		builder.expected,
		func(_ GetNodeVariables, writer http.ResponseWriter) error {
			return writeGraphQLResponse(
				writer,
				nil,
				[]octoql.Error{graphqlError},
				responseConfig,
			)
		},
	)
}

func (builder *GetNodeExpectation) RespondDataAndErrors(
	data GetNodeResponse,
	graphqlErrors ...octoql.Error,
) {
	responseConfig := buildResponseOptions(builder.options...)
	builder.set.setResult(
		builder.expected,
		func(_ GetNodeVariables, writer http.ResponseWriter) error {
			return writeGraphQLResponse(
				writer,
				&data,
				graphqlErrors,
				responseConfig,
			)
		},
	)
}

func (builder *GetNodeExpectation) Handle(
	handler func(GetNodeVariables, http.ResponseWriter),
) {
	if handler == nil {
		builder.set.tb.Errorf("GetNode dynamic handler must not be nil")
		builder.set.setResult(
			builder.expected,
			func(_ GetNodeVariables, _ http.ResponseWriter) error {
				return fmt.Errorf("GetNode dynamic handler is nil")
			},
		)
		return
	}
	builder.set.setResult(
		builder.expected,
		func(variables GetNodeVariables, writer http.ResponseWriter) error {
			handler(variables, writer)
			return nil
		},
	)
}

type GetRepositoryExpectation struct {
	set      *expectationSet[GetRepositoryVariables]
	expected *expectation[GetRepositoryVariables]
	options  []ResponseOption
}

func (handler *TestHandler) ExpectGetRepository(
	variables GetRepositoryVariables,
	options ...ExpectOption,
) *GetRepositoryExpectation {
	return &GetRepositoryExpectation{
		set: &handler.operation5,
		expected: handler.operation5.expect(
			variables,
			options...,
		),
		options: []ResponseOption{},
	}
}

func (handler *TestHandler) DefaultGetRepository() *GetRepositoryExpectation {
	return &GetRepositoryExpectation{
		set:      &handler.operation5,
		expected: handler.operation5.expectDefault(),
		options:  []ResponseOption{},
	}
}

func (handler *TestHandler) ResetGetRepository(variables ...GetRepositoryVariables) {
	handler.operation5.reset(variables...)
}

func (builder *GetRepositoryExpectation) WithOptions(
	options ...ResponseOption,
) *GetRepositoryExpectation {
	builder.options = combineResponseOptions(builder.options, options)
	return builder
}

func (builder *GetRepositoryExpectation) Respond(
	data GetRepositoryResponse,
	options ...ResponseOption,
) {
	combined := combineResponseOptions(builder.options, options)
	responseConfig := buildResponseOptions(combined...)
	builder.set.setResult(
		builder.expected,
		func(_ GetRepositoryVariables, writer http.ResponseWriter) error {
			return writeGraphQLResponse(writer, &data, nil, responseConfig)
		},
	)
}

func (builder *GetRepositoryExpectation) RespondError(
	graphqlError octoql.Error,
	options ...ResponseOption,
) {
	combined := combineResponseOptions(builder.options, options)
	responseConfig := buildResponseOptions(combined...)
	builder.set.setResult(
		builder.expected,
		func(_ GetRepositoryVariables, writer http.ResponseWriter) error {
			return writeGraphQLResponse(
				writer,
				nil,
				[]octoql.Error{graphqlError},
				responseConfig,
			)
		},
	)
}

func (builder *GetRepositoryExpectation) RespondDataAndErrors(
	data GetRepositoryResponse,
	graphqlErrors ...octoql.Error,
) {
	responseConfig := buildResponseOptions(builder.options...)
	builder.set.setResult(
		builder.expected,
		func(_ GetRepositoryVariables, writer http.ResponseWriter) error {
			return writeGraphQLResponse(
				writer,
				&data,
				graphqlErrors,
				responseConfig,
			)
		},
	)
}

func (builder *GetRepositoryExpectation) Handle(
	handler func(GetRepositoryVariables, http.ResponseWriter),
) {
	if handler == nil {
		builder.set.tb.Errorf("GetRepository dynamic handler must not be nil")
		builder.set.setResult(
			builder.expected,
			func(_ GetRepositoryVariables, _ http.ResponseWriter) error {
				return fmt.Errorf("GetRepository dynamic handler is nil")
			},
		)
		return
	}
	builder.set.setResult(
		builder.expected,
		func(variables GetRepositoryVariables, writer http.ResponseWriter) error {
			handler(variables, writer)
			return nil
		},
	)
}

type SearchExpectation struct {
	set      *expectationSet[SearchVariables]
	expected *expectation[SearchVariables]
	options  []ResponseOption
}

func (handler *TestHandler) ExpectSearch(
	variables SearchVariables,
	options ...ExpectOption,
) *SearchExpectation {
	return &SearchExpectation{
		set: &handler.operation6,
		expected: handler.operation6.expect(
			variables,
			options...,
		),
		options: []ResponseOption{},
	}
}

func (handler *TestHandler) DefaultSearch() *SearchExpectation {
	return &SearchExpectation{
		set:      &handler.operation6,
		expected: handler.operation6.expectDefault(),
		options:  []ResponseOption{},
	}
}

func (handler *TestHandler) ResetSearch(variables ...SearchVariables) {
	handler.operation6.reset(variables...)
}

func (builder *SearchExpectation) WithOptions(
	options ...ResponseOption,
) *SearchExpectation {
	builder.options = combineResponseOptions(builder.options, options)
	return builder
}

func (builder *SearchExpectation) Respond(
	data SearchResponse,
	options ...ResponseOption,
) {
	combined := combineResponseOptions(builder.options, options)
	responseConfig := buildResponseOptions(combined...)
	builder.set.setResult(
		builder.expected,
		func(_ SearchVariables, writer http.ResponseWriter) error {
			return writeGraphQLResponse(writer, &data, nil, responseConfig)
		},
	)
}

func (builder *SearchExpectation) RespondError(
	graphqlError octoql.Error,
	options ...ResponseOption,
) {
	combined := combineResponseOptions(builder.options, options)
	responseConfig := buildResponseOptions(combined...)
	builder.set.setResult(
		builder.expected,
		func(_ SearchVariables, writer http.ResponseWriter) error {
			return writeGraphQLResponse(
				writer,
				nil,
				[]octoql.Error{graphqlError},
				responseConfig,
			)
		},
	)
}

func (builder *SearchExpectation) RespondDataAndErrors(
	data SearchResponse,
	graphqlErrors ...octoql.Error,
) {
	responseConfig := buildResponseOptions(builder.options...)
	builder.set.setResult(
		builder.expected,
		func(_ SearchVariables, writer http.ResponseWriter) error {
			return writeGraphQLResponse(
				writer,
				&data,
				graphqlErrors,
				responseConfig,
			)
		},
	)
}

func (builder *SearchExpectation) Handle(
	handler func(SearchVariables, http.ResponseWriter),
) {
	if handler == nil {
		builder.set.tb.Errorf("Search dynamic handler must not be nil")
		builder.set.setResult(
			builder.expected,
			func(_ SearchVariables, _ http.ResponseWriter) error {
				return fmt.Errorf("Search dynamic handler is nil")
			},
		)
		return
	}
	builder.set.setResult(
		builder.expected,
		func(variables SearchVariables, writer http.ResponseWriter) error {
			handler(variables, writer)
			return nil
		},
	)
}

type ViewerExpectation struct {
	set      *expectationSet[struct{}]
	expected *expectation[struct{}]
	options  []ResponseOption
}

func (handler *TestHandler) ExpectViewer(
	options ...ExpectOption,
) *ViewerExpectation {
	return &ViewerExpectation{
		set: &handler.operation7,
		expected: handler.operation7.expect(
			struct{}{},
			options...,
		),
		options: []ResponseOption{},
	}
}

func (handler *TestHandler) DefaultViewer() *ViewerExpectation {
	return &ViewerExpectation{
		set:      &handler.operation7,
		expected: handler.operation7.expectDefault(),
		options:  []ResponseOption{},
	}
}

func (handler *TestHandler) ResetViewer() {
	handler.operation7.reset()
}

func (builder *ViewerExpectation) WithOptions(
	options ...ResponseOption,
) *ViewerExpectation {
	builder.options = combineResponseOptions(builder.options, options)
	return builder
}

func (builder *ViewerExpectation) Respond(
	data ViewerResponse,
	options ...ResponseOption,
) {
	combined := combineResponseOptions(builder.options, options)
	responseConfig := buildResponseOptions(combined...)
	builder.set.setResult(
		builder.expected,
		func(_ struct{}, writer http.ResponseWriter) error {
			return writeGraphQLResponse(writer, &data, nil, responseConfig)
		},
	)
}

func (builder *ViewerExpectation) RespondError(
	graphqlError octoql.Error,
	options ...ResponseOption,
) {
	combined := combineResponseOptions(builder.options, options)
	responseConfig := buildResponseOptions(combined...)
	builder.set.setResult(
		builder.expected,
		func(_ struct{}, writer http.ResponseWriter) error {
			return writeGraphQLResponse(
				writer,
				nil,
				[]octoql.Error{graphqlError},
				responseConfig,
			)
		},
	)
}

func (builder *ViewerExpectation) RespondDataAndErrors(
	data ViewerResponse,
	graphqlErrors ...octoql.Error,
) {
	responseConfig := buildResponseOptions(builder.options...)
	builder.set.setResult(
		builder.expected,
		func(_ struct{}, writer http.ResponseWriter) error {
			return writeGraphQLResponse(
				writer,
				&data,
				graphqlErrors,
				responseConfig,
			)
		},
	)
}

func (builder *ViewerExpectation) Handle(
	handler func(http.ResponseWriter),
) {
	if handler == nil {
		builder.set.tb.Errorf("Viewer dynamic handler must not be nil")
		builder.set.setResult(
			builder.expected,
			func(_ struct{}, _ http.ResponseWriter) error {
				return fmt.Errorf("Viewer dynamic handler is nil")
			},
		)
		return
	}
	builder.set.setResult(
		builder.expected,
		func(variables struct{}, writer http.ResponseWriter) error {
			handler(writer)
			return nil
		},
	)
}
