#!/bin/sh
#/ script/cibuild runs the checks used by continuous integration.

set -e

CDPATH="" cd -- "$(dirname -- "$0")/.."
script/bindown -q install goreleaser
script/test
script/lint
script/generate --check
bin/goreleaser build --snapshot --clean
