#!/bin/sh
#/ script/lint runs Go and shell linters.

set -e

CDPATH="" cd -- "$(dirname -- "$0")/.."
script/bindown -q install golangci-lint shfmt
bin/golangci-lint run ./...
bin/shfmt -d -ci -i 2 -sr script
