// Code generated by octoqlgen, DO NOT EDIT.

package githubapi

import (
	"bytes"
	"context"
	"encoding/json"
	"errors"
	"fmt"
	"io"
	"maps"
	"math"
	"net/http"
	"slices"
	"strconv"
	"strings"
	"sync"
	"sync/atomic"
	"time"
)

// noUnmarshalJSON is for generated code only.
//
// Embedding noUnmarshalJSON alongside a type with an UnmarshalJSON method
// prevents that sibling method from being promoted.
type noUnmarshalJSON struct{}

// UnmarshalJSON should never be called. It exists only to prevent a sibling
// UnmarshalJSON method from being promoted.
func (noUnmarshalJSON) UnmarshalJSON([]byte) error {
	panic("noUnmarshalJSON.UnmarshalJSON should never be called!")
}

// noMarshalJSON is for generated code only.
//
// Embedding noMarshalJSON alongside a type with a MarshalJSON method prevents
// that sibling method from being promoted.
type noMarshalJSON struct{}

// MarshalJSON should never be called. It exists only to prevent a sibling
// MarshalJSON method from being promoted.
func (noMarshalJSON) MarshalJSON() ([]byte, error) {
	panic("noUnmarshalJSON.MarshalJSON should never be called!")
}

const maxResponseErrorRawBody = 64 * 1024

// ErrorType identifies a GitHub GraphQL error category. It is an open string
// type so values introduced by GitHub remain available to callers.
type ErrorType string

// Path is a GraphQL response path. Each segment is either a string field name
// or an integer list index.
type Path []any

// Location identifies a line and column in a GraphQL document.
type Location struct {
	Line   int `json:"line,omitempty"`
	Column int `json:"column,omitempty"`
}

// Error describes an error returned in a GraphQL response.
type Error struct {
	Type       ErrorType      `json:"type,omitempty"`
	Message    string         `json:"message"`
	Path       Path           `json:"path,omitempty"`
	Locations  []Location     `json:"locations,omitempty"`
	Extensions map[string]any `json:"extensions,omitempty"`
}

// Errors is the list of errors returned in a GraphQL response.
type Errors []*Error

// ResponseError describes a failed GraphQL HTTP response.
type ResponseError struct {
	// StatusCode is the HTTP response status.
	StatusCode int
	// RequestID is GitHub's X-GitHub-Request-ID value, when present.
	RequestID string
	// RawBody contains at most the first 64 KiB of a non-successful, over-limit,
	// or undecodable response. It is omitted for ordinary GraphQL errors.
	RawBody []byte
	// RawBodyTruncated reports whether RawBody omits trailing response bytes.
	RawBodyTruncated bool

	err error
}

// ResponseSizeLimitError reports that a GraphQL HTTP response exceeded Client's
// configured response-size limit.
type ResponseSizeLimitError struct {
	// Limit is the configured maximum response size in bytes.
	Limit int64
}

// Error reports that the response exceeded its configured limit.
func (e *ResponseSizeLimitError) Error() string {
	if e == nil {
		return "graphql response exceeds its size limit"
	}
	return fmt.Sprintf("graphql response exceeds %d-byte limit", e.Limit)
}

// MarshalJSON encodes string and integer path segments in GraphQL wire format.
func (p Path) MarshalJSON() ([]byte, error) {
	if p == nil {
		return []byte("null"), nil
	}

	segments := make([]json.RawMessage, len(p))
	for index, segment := range p {
		var encoded []byte
		var err error
		switch value := segment.(type) {
		case string:
			encoded, err = json.Marshal(value)
		case int:
			encoded, err = json.Marshal(value)
		default:
			return nil, fmt.Errorf(
				"encode graphql path segment %d: expected string or int, got %T",
				index,
				segment,
			)
		}
		if err != nil {
			return nil, fmt.Errorf("encode graphql path segment %d: %w", index, err)
		}
		segments[index] = encoded
	}

	encoded, err := json.Marshal(segments)
	if err != nil {
		return nil, fmt.Errorf("encode graphql path: %w", err)
	}
	return encoded, nil
}

// UnmarshalJSON decodes GraphQL string and integer path segments.
func (p *Path) UnmarshalJSON(data []byte) error {
	if p == nil {
		return errors.New("decode graphql path: nil destination")
	}

	var rawSegments []json.RawMessage
	err := json.Unmarshal(data, &rawSegments)
	if err != nil {
		return fmt.Errorf("decode graphql path: %w", err)
	}
	if rawSegments == nil {
		*p = nil
		return nil
	}

	segments := make(Path, len(rawSegments))
	for index, rawSegment := range rawSegments {
		trimmed := bytes.TrimSpace(rawSegment)
		if len(trimmed) > 0 && trimmed[0] == '"' {
			var field string
			err = json.Unmarshal(trimmed, &field)
			if err != nil {
				return fmt.Errorf("decode graphql path segment %d: %w", index, err)
			}
			segments[index] = field
			continue
		}

		var listIndex int
		var parsed int64
		parsed, err = strconv.ParseInt(string(trimmed), 10, strconv.IntSize)
		if err != nil {
			return fmt.Errorf(
				"decode graphql path segment %d: expected string or integer: %w",
				index,
				err,
			)
		}
		listIndex = int(parsed)
		segments[index] = listIndex
	}

	*p = segments
	return nil
}

// String formats a path using dotted fields and bracketed list indexes.
func (p Path) String() string {
	var result strings.Builder
	for _, segment := range p {
		switch value := segment.(type) {
		case string:
			if result.Len() > 0 {
				result.WriteByte('.')
			}
			result.WriteString(value)
		case int:
			result.WriteByte('[')
			result.WriteString(strconv.Itoa(value))
			result.WriteByte(']')
		default:
			if result.Len() > 0 {
				result.WriteByte('.')
			}
			result.WriteString("<invalid>")
		}
	}
	return result.String()
}

// Error returns the GraphQL error message and response path.
func (e *Error) Error() string {
	if e == nil {
		return "<nil>"
	}

	message := e.Message
	if message == "" {
		message = "graphql error"
	}
	path := e.Path.String()
	if path == "" {
		return message
	}
	return fmt.Sprintf("%s (path %s)", message, path)
}

// Error returns a stable summary of all GraphQL errors.
func (e Errors) Error() string {
	if len(e) == 0 {
		return "graphql request failed"
	}

	messages := make([]string, 0, len(e))
	for _, graphqlError := range e {
		messages = append(messages, graphqlError.Error())
	}
	if len(messages) == 1 {
		return "graphql error: " + messages[0]
	}
	return "graphql errors: " + strings.Join(messages, "; ")
}

// Unwrap exposes individual GraphQL errors to [errors.Is], [errors.As], and
// [errors.AsType].
func (e Errors) Unwrap() []error {
	unwrapped := make([]error, 0, len(e))
	for _, graphqlError := range e {
		if graphqlError != nil {
			unwrapped = append(unwrapped, graphqlError)
		}
	}
	return unwrapped
}

// Error returns a stable summary of the failed response.
func (e *ResponseError) Error() string {
	if e == nil {
		return "graphql response failed"
	}

	message := "graphql response failed"
	if !isSuccessfulStatus(e.StatusCode) {
		message = fmt.Sprintf(
			"graphql response failed with status %d",
			e.StatusCode,
		)
	}
	if e.err != nil {
		return message + ": " + e.err.Error()
	}
	return message
}

// Unwrap exposes decoded GraphQL errors and response processing failures to
// [errors.Is], [errors.As], and [errors.AsType].
func (e *ResponseError) Unwrap() error {
	if e == nil {
		return nil
	}
	return e.err
}

type responseErrorParams struct {
	statusCode    int
	requestID     string
	body          []byte
	retainBody    bool
	bodyTruncated bool
	err           error
}

func newResponseError(params responseErrorParams) *ResponseError {
	var rawBody []byte
	isTruncated := false
	if params.retainBody {
		rawBody = params.body
		isTruncated = params.bodyTruncated
		if len(rawBody) > maxResponseErrorRawBody {
			rawBody = rawBody[:maxResponseErrorRawBody]
			isTruncated = true
		}
		rawBody = bytes.Clone(rawBody)
	}

	return &ResponseError{
		StatusCode:       params.statusCode,
		RequestID:        params.requestID,
		RawBody:          rawBody,
		RawBodyTruncated: isTruncated,
		err:              params.err,
	}
}

// RateLimitKind identifies the GitHub rate limit that rejected a request.
type RateLimitKind string

const (
	// RateLimitPrimary identifies exhaustion of GitHub's primary rate limit.
	RateLimitPrimary RateLimitKind = "primary"
	// RateLimitSecondary identifies GitHub's secondary rate limit.
	RateLimitSecondary RateLimitKind = "secondary"
)

// RateLimit describes the rate-limit headers returned by GitHub.
//
// Missing or malformed response headers leave their corresponding fields at
// their zero values.
type RateLimit struct {
	Limit      int
	Remaining  int
	Used       int
	Reset      time.Time
	Resource   string
	RetryAfter time.Duration
	RetryAt    time.Time
}

type parsedRateLimit struct {
	RateLimit

	remainingValid  bool
	retryAfterValid bool
}

// RateLimitError describes a response rejected because of a GitHub rate limit.
type RateLimitError struct {
	Kind      RateLimitKind
	RateLimit RateLimit
	Err       error
}

// Error returns a summary of the rate-limit failure.
func (e *RateLimitError) Error() string {
	if e == nil {
		return "github rate limit exceeded"
	}
	if e.Err == nil {
		return fmt.Sprintf("github %s rate limit exceeded", e.Kind)
	}
	return fmt.Sprintf("github %s rate limit exceeded: %v", e.Kind, e.Err)
}

// Unwrap exposes the response failure and its GraphQL or processing causes.
func (e *RateLimitError) Unwrap() error {
	if e == nil {
		return nil
	}
	return e.Err
}

var rateLimitNow = time.Now

func maxUnixSeconds() uint64 {
	firstUnixSecond := time.Date(1, time.January, 1, 0, 0, 0, 0, time.UTC).Unix()
	return uint64(math.MaxInt64 + firstUnixSecond)
}

func rateLimitFromHeader(header http.Header, now time.Time) parsedRateLimit {
	rateLimit := parsedRateLimit{}

	limit, valid := nonnegativeHeaderInt(header, "X-RateLimit-Limit")
	if valid {
		rateLimit.Limit = limit
	}
	remaining, valid := nonnegativeHeaderInt(header, "X-RateLimit-Remaining")
	if valid {
		rateLimit.Remaining = remaining
		rateLimit.remainingValid = true
	}
	used, valid := nonnegativeHeaderInt(header, "X-RateLimit-Used")
	if valid {
		rateLimit.Used = used
	}
	reset, valid := nonnegativeHeaderUnix(header, "X-RateLimit-Reset")
	if valid {
		rateLimit.Reset = reset
	}
	rateLimit.Resource = strings.TrimSpace(headerValue(header, "X-RateLimit-Resource"))

	retryAfter, retryAt, valid := retryAfterFromHeader(header, now)
	if valid {
		rateLimit.RetryAfter = retryAfter
		rateLimit.RetryAt = retryAt
		rateLimit.retryAfterValid = true
	}

	return rateLimit
}

func (r *parsedRateLimit) primarySnapshot() RateLimit {
	snapshot := r.RateLimit
	snapshot.RetryAfter = 0
	snapshot.RetryAt = time.Time{}
	return snapshot
}

func nonnegativeHeaderInt(header http.Header, name string) (int, bool) {
	value, valid := parseNonnegativeDecimal(headerValue(header, name), strconv.IntSize)
	if !valid {
		return 0, false
	}
	return int(value), true
}

func nonnegativeHeaderUnix(header http.Header, name string) (time.Time, bool) {
	value, valid := parseNonnegativeDecimal(headerValue(header, name), 63)
	if !valid {
		return time.Time{}, false
	}
	if value > maxUnixSeconds() {
		return time.Time{}, false
	}
	return time.Unix(int64(value), 0).UTC(), true
}

func retryAfterFromHeader(header http.Header, now time.Time) (time.Duration, time.Time, bool) {
	value := strings.TrimSpace(headerValue(header, "Retry-After"))
	if value == "" {
		return 0, time.Time{}, false
	}

	seconds, valid := parseNonnegativeDecimal(value, 64)
	if valid {
		maxSeconds := uint64(math.MaxInt64 / int64(time.Second))
		if seconds > maxSeconds {
			return 0, time.Time{}, false
		}
		retryAfter := time.Duration(seconds) * time.Second
		return retryAfter, now.Add(retryAfter), true
	}

	retryAt, err := http.ParseTime(value)
	if err != nil {
		return 0, time.Time{}, false
	}
	retryAt = retryAt.UTC()
	retryAfter := retryAt.Sub(now)
	if retryAfter < 0 {
		retryAfter = 0
	}
	return retryAfter, retryAt, true
}

func parseNonnegativeDecimal(value string, bitSize int) (uint64, bool) {
	value = strings.TrimSpace(value)
	if value == "" {
		return 0, false
	}
	for _, char := range value {
		if char < '0' || char > '9' {
			return 0, false
		}
	}
	parsed, err := strconv.ParseUint(value, 10, bitSize)
	if err != nil {
		return 0, false
	}
	return parsed, true
}

func headerValue(header http.Header, name string) string {
	for headerName, values := range header {
		if strings.EqualFold(headerName, name) && len(values) > 0 {
			return values[0]
		}
	}
	return ""
}

func classifyRateLimit(statusCode int, rateLimit *parsedRateLimit, err error) error {
	if err == nil {
		return nil
	}

	isSecondaryResponse := isSecondaryRateLimitStatus(statusCode)
	if rateLimit.retryAfterValid && isSecondaryResponse {
		return &RateLimitError{
			Kind:      RateLimitSecondary,
			RateLimit: rateLimit.RateLimit,
			Err:       err,
		}
	}

	isPrimaryStatus := isPrimaryRateLimitStatus(statusCode)
	isPrimaryGraphQLError := hasGraphQLRateLimitError(err)
	hasNoRemaining := rateLimit.remainingValid && rateLimit.Remaining == 0
	hasPrimarySignal := isPrimaryStatus || isPrimaryGraphQLError
	isPrimaryLimit := hasNoRemaining && hasPrimarySignal
	if isPrimaryLimit {
		return &RateLimitError{
			Kind:      RateLimitPrimary,
			RateLimit: rateLimit.RateLimit,
			Err:       err,
		}
	}
	return err
}

func isSecondaryRateLimitStatus(statusCode int) bool {
	switch statusCode {
	case http.StatusOK, http.StatusForbidden, http.StatusTooManyRequests:
		return true
	default:
		return false
	}
}

func isPrimaryRateLimitStatus(statusCode int) bool {
	switch statusCode {
	case http.StatusForbidden, http.StatusTooManyRequests:
		return true
	default:
		return false
	}
}

func hasGraphQLRateLimitError(err error) bool {
	graphqlErrors, ok := errors.AsType[Errors](err)
	if !ok {
		return false
	}
	for _, graphqlError := range graphqlErrors {
		if graphqlError != nil && graphqlError.Type == ErrorType("RATE_LIMITED") {
			return true
		}
	}
	return false
}

// DefaultResponseSizeLimit is the maximum GraphQL HTTP response body size a
// Client accepts for decoding unless configured otherwise. It is 10 MiB.
const DefaultResponseSizeLimit int64 = 10 * 1024 * 1024

// Client executes GraphQL operations against an HTTP endpoint.
//
// Configure bearer authentication with [Client.SetBearerToken]. Other request
// behavior, including other authentication schemes, belongs on the supplied
// [http.Client] or its [http.RoundTripper]. A Client may be used concurrently
// after construction.
type Client struct {
	httpClient *http.Client
	rateLimit  *RateLimit
	endpoint   string

	bearerToken          atomic.Pointer[string]
	responseObservation  atomic.Uint64
	responseSizeLimit    atomic.Int64
	rateLimitMu          sync.RWMutex
	rateLimitObservation uint64
}

// NewClient returns a client for endpoint. A nil httpClient uses
// [http.DefaultClient].
func NewClient(endpoint string, httpClient *http.Client) *Client {
	if httpClient == nil {
		httpClient = http.DefaultClient
	}
	client := &Client{
		endpoint:   endpoint,
		httpClient: httpClient,
	}
	client.responseSizeLimit.Store(DefaultResponseSizeLimit)
	return client
}

// SetBearerToken configures the OAuth 2.0 bearer token sent with each request.
// token must use the RFC 6750 b64token syntax. It may be called concurrently
// with [Client.execute] to rotate credentials.
func (c *Client) SetBearerToken(token string) error {
	if c == nil {
		return errors.New("octoql: client is nil")
	}
	if !validBearerToken(token) {
		return errors.New("octoql: invalid bearer token")
	}

	c.bearerToken.Store(&token)
	return nil
}

// ResponseSizeLimit returns the maximum HTTP response body size Client accepts
// for decoding. A newly constructed Client uses [DefaultResponseSizeLimit].
func (c *Client) ResponseSizeLimit() int64 {
	if c == nil {
		return 0
	}

	limit := c.responseSizeLimit.Load()
	if limit > 0 {
		return limit
	}
	return DefaultResponseSizeLimit
}

// SetResponseSizeLimit configures the maximum HTTP response body size Client
// accepts for decoding. limit must be greater than zero. It may be called
// concurrently with [Client.execute].
func (c *Client) SetResponseSizeLimit(limit int64) error {
	if c == nil {
		return errors.New("octoql: client is nil")
	}
	if limit <= 0 {
		return errors.New("octoql: response size limit must be greater than zero")
	}

	c.responseSizeLimit.Store(limit)
	return nil
}

// RateLimit returns the latest valid primary rate-limit snapshot observed by
// client. The boolean is false until a response includes a valid
// X-RateLimit-Remaining header.
//
// The snapshot is advisory: other clients and processes can consume the same
// GitHub rate-limit budget after it is observed.
func (c *Client) RateLimit() (RateLimit, bool) {
	if c == nil {
		return RateLimit{}, false
	}

	c.rateLimitMu.RLock()
	defer c.rateLimitMu.RUnlock()
	if c.rateLimit == nil {
		return RateLimit{}, false
	}
	return *c.rateLimit, true
}

// payload is the GraphQL request body used by generated clients.
type payload struct {
	Query         string `json:"query"`
	OperationName string `json:"operationName"`
	Variables     any    `json:"variables,omitempty"`
}

// execute runs operation and decodes its response data into response.
//
// execute is a generated-code contract. Response must be a non-nil pointer.
// The returned boolean reports whether the GraphQL data field decoded
// successfully and response is usable, including when GraphQL errors are also
// returned.
// Every failure after the server returns an HTTP response includes
// [ResponseError]. GraphQL errors and rate limits remain discoverable in that
// error chain as [Errors] and [RateLimitError].
func (c *Client) execute(ctx context.Context, payload payload, response any) (bool, error) {
	if c == nil {
		return false, errors.New("octoql: client is nil")
	}
	body, err := json.Marshal(payload)
	if err != nil {
		return false, fmt.Errorf("encode graphql request: %w", err)
	}

	request, err := http.NewRequestWithContext(
		ctx,
		http.MethodPost,
		c.endpoint,
		bytes.NewReader(body),
	)
	if err != nil {
		return false, fmt.Errorf("create graphql request: %w", err)
	}
	request.Header.Set("Accept", "application/json")
	request.Header.Set("Content-Type", "application/json")
	bearerToken := c.bearerToken.Load()
	if bearerToken != nil {
		request.Header.Set("Authorization", "Bearer "+*bearerToken)
	}

	httpClient := c.httpClient
	if httpClient == nil {
		httpClient = http.DefaultClient
	}
	//nolint:bodyclose // readAndClose closes the body and preserves close errors.
	httpResponse, sendErr := httpClient.Do(request)
	if httpResponse == nil {
		if sendErr == nil {
			return false, errors.New("send graphql request: HTTP client returned no response")
		}
		return false, fmt.Errorf("send graphql request: %w", sendErr)
	}

	observation := c.responseObservation.Add(1)
	rateLimit := rateLimitFromHeader(httpResponse.Header, rateLimitNow())
	c.observeRateLimit(observation, &rateLimit)

	statusCode := httpResponse.StatusCode
	requestID := requestIDFromHeader(httpResponse.Header)
	if sendErr != nil {
		cause := fmt.Errorf("send graphql request: %w", sendErr)
		responseError := newResponseError(responseErrorParams{
			statusCode: statusCode,
			requestID:  requestID,
			err:        cause,
		})
		return false, classifyRateLimit(statusCode, &rateLimit, responseError)
	}

	if httpResponse.Body == nil {
		cause := errors.New("read graphql response: response body is nil")
		responseError := newResponseError(responseErrorParams{
			statusCode: statusCode,
			requestID:  requestID,
			err:        cause,
		})
		return false, classifyRateLimit(statusCode, &rateLimit, responseError)
	}

	body, readErr, closeErr := readAndClose(
		httpResponse.Body,
		c.ResponseSizeLimit(),
	)
	if readErr != nil {
		cause := errors.Join(readErr, closeErr)
		_, responseTooLarge := errors.AsType[*ResponseSizeLimitError](readErr)
		responseError := newResponseError(responseErrorParams{
			statusCode:    statusCode,
			requestID:     requestID,
			body:          body,
			retainBody:    true,
			bodyTruncated: responseTooLarge,
			err:           cause,
		})
		return false, classifyRateLimit(statusCode, &rateLimit, responseError)
	}

	data, graphqlErrors, decodeErr := decodeResponse(body)

	hasData := data != nil && !bytes.Equal(bytes.TrimSpace(data), []byte("null"))
	hasErrors := len(graphqlErrors) > 0
	hasUsableData := false
	if hasData {
		dataErr := decodeData(data, response)
		hasUsableData = dataErr == nil
		decodeErr = errors.Join(decodeErr, dataErr)
	}

	cause := decodeErr
	if len(graphqlErrors) > 0 {
		var left error = graphqlErrors
		cause = errors.Join(left, cause)
	}
	cause = errors.Join(cause, closeErr)

	isSuccessful := isSuccessfulStatus(statusCode)
	haspayload := hasData || hasErrors
	missingpayload := decodeErr == nil && !haspayload
	if isSuccessful && missingpayload {
		payloadErr := errors.New("decode graphql response: response contains neither data nor errors")
		cause = errors.Join(cause, payloadErr)
	}

	if isSuccessful && cause == nil {
		return hasUsableData, nil
	}

	hasDecodeFailure := decodeErr != nil || missingpayload
	retainBody := !isSuccessful || hasDecodeFailure
	responseError := newResponseError(responseErrorParams{
		statusCode: statusCode,
		requestID:  requestID,
		body:       body,
		retainBody: retainBody,
		err:        cause,
	})
	return hasUsableData, classifyRateLimit(statusCode, &rateLimit, responseError)
}

func (c *Client) observeRateLimit(observation uint64, parsed *parsedRateLimit) {
	if c == nil || parsed == nil || !parsed.remainingValid {
		return
	}

	rateLimit := parsed.primarySnapshot()
	c.rateLimitMu.Lock()
	defer c.rateLimitMu.Unlock()

	hasNewerObservation := c.rateLimit != nil &&
		c.rateLimitObservation >= observation
	if hasNewerObservation {
		return
	}
	c.rateLimit = &rateLimit
	c.rateLimitObservation = observation
}

func requestIDFromHeader(header http.Header) string {
	for name, values := range header {
		if strings.EqualFold(name, "X-GitHub-Request-ID") && len(values) > 0 {
			return values[0]
		}
	}
	return ""
}

func validBearerToken(token string) bool {
	if token == "" {
		return false
	}

	hasTokenCharacter := false
	padding := false
	for i := range len(token) {
		character := token[i]
		if character == '=' {
			padding = true
			continue
		}
		if padding || !validBearerTokenCharacter(character) {
			return false
		}
		hasTokenCharacter = true
	}
	return hasTokenCharacter
}

func validBearerTokenCharacter(character byte) bool {
	switch {
	case character >= 'a' && character <= 'z':
		return true
	case character >= 'A' && character <= 'Z':
		return true
	case character >= '0' && character <= '9':
		return true
	case strings.ContainsRune("-._~+/", rune(character)):
		return true
	default:
		return false
	}
}

func readAndClose(body io.ReadCloser, limit int64) ([]byte, error, error) {
	payload, readErr := io.ReadAll(io.LimitReader(body, limit))
	if readErr == nil {
		var excess [1]byte
		count, excessErr := io.ReadFull(body, excess[:])
		switch {
		case count > 0:
			readErr = &ResponseSizeLimitError{Limit: limit}
		case excessErr != nil && !errors.Is(excessErr, io.EOF):
			readErr = excessErr
		}
	}
	closeErr := body.Close()
	if readErr != nil {
		readErr = fmt.Errorf("read graphql response: %w", readErr)
	}
	if closeErr != nil {
		closeErr = fmt.Errorf("close graphql response: %w", closeErr)
	}
	return payload, readErr, closeErr
}

func decodeResponse(body []byte) (json.RawMessage, Errors, error) {
	var envelope struct {
		Data   json.RawMessage `json:"data"`
		Errors json.RawMessage `json:"errors"`
	}
	err := json.Unmarshal(body, &envelope)
	if err != nil {
		return nil, nil, fmt.Errorf(
			"decode graphql response envelope: %w",
			err,
		)
	}

	var graphqlErrors Errors
	if envelope.Errors == nil {
		return envelope.Data, graphqlErrors, nil
	}

	err = json.Unmarshal(envelope.Errors, &graphqlErrors)
	if err != nil {
		err = fmt.Errorf("decode graphql response errors: %w", err)
	}
	return envelope.Data, graphqlErrors, err
}

func decodeData(data json.RawMessage, response any) error {
	err := json.Unmarshal(data, response)
	if err != nil {
		return fmt.Errorf("decode graphql response data: %w", err)
	}
	return nil
}

func isSuccessfulStatus(statusCode int) bool {
	return statusCode >= 200 && statusCode < 300
}

// HTTPStatusCode returns the failed HTTP response status.
func (e *ResponseError) HTTPStatusCode() int {
	if e == nil {
		return 0
	}
	return e.StatusCode
}

// GitHubRequestID returns the response's X-GitHub-Request-ID value.
func (e *ResponseError) GitHubRequestID() string {
	if e == nil {
		return ""
	}
	return e.RequestID
}

// ResponseSizeLimit returns the configured response-size limit.
func (e *ResponseSizeLimitError) ResponseSizeLimit() int64 {
	if e == nil {
		return 0
	}
	return e.Limit
}

// RateLimitKind returns the kind of rate limit that rejected the request.
func (e *RateLimitError) RateLimitKind() string {
	if e == nil {
		return ""
	}
	return string(e.Kind)
}

// RetryAt returns when GitHub advised retrying the request.
func (e *RateLimitError) RetryAt() time.Time {
	if e == nil {
		return time.Time{}
	}
	return e.RateLimit.RetryAt
}

// GraphQLErrorCount returns the number of GraphQL errors.
func (e Errors) GraphQLErrorCount() int {
	return len(e)
}

// GraphQLError returns one GraphQL error as a package-neutral error value.
func (e Errors) GraphQLError(index int) error {
	if index < 0 || index >= len(e) {
		return nil
	}
	return e[index]
}

// GraphQLType returns GitHub's GraphQL error category.
func (e *Error) GraphQLType() string {
	if e == nil {
		return ""
	}
	return string(e.Type)
}

// GraphQLMessage returns the GraphQL error message.
func (e *Error) GraphQLMessage() string {
	if e == nil {
		return ""
	}
	return e.Message
}

// GraphQLPath returns a defensive copy of the GraphQL response path.
func (e *Error) GraphQLPath() []any {
	if e == nil {
		return nil
	}
	return slices.Clone(e.Path)
}

// GraphQLExtensions returns a shallow clone of the GraphQL error extensions.
func (e *Error) GraphQLExtensions() map[string]any {
	if e == nil {
		return nil
	}
	return maps.Clone(e.Extensions)
}

// CreateRepositoryCreateRepositoryCreateRepositoryPayload includes the requested fields of the GraphQL type CreateRepositoryPayload.
type CreateRepositoryCreateRepositoryCreateRepositoryPayload struct {
	Repository       *CreateRepositoryCreateRepositoryCreateRepositoryPayloadRepository `json:"repository"`
	ClientMutationId *string                                                            `json:"clientMutationId"`
}

// GetRepository returns CreateRepositoryCreateRepositoryCreateRepositoryPayload.Repository, and is useful for accessing the field via an interface.
func (v *CreateRepositoryCreateRepositoryCreateRepositoryPayload) GetRepository() *CreateRepositoryCreateRepositoryCreateRepositoryPayloadRepository {
	return v.Repository
}

// GetClientMutationId returns CreateRepositoryCreateRepositoryCreateRepositoryPayload.ClientMutationId, and is useful for accessing the field via an interface.
func (v *CreateRepositoryCreateRepositoryCreateRepositoryPayload) GetClientMutationId() *string {
	return v.ClientMutationId
}

// CreateRepositoryCreateRepositoryCreateRepositoryPayloadRepository includes the requested fields of the GraphQL type Repository.
type CreateRepositoryCreateRepositoryCreateRepositoryPayloadRepository struct {
	Id            string                                                                                 `json:"id"`
	NameWithOwner string                                                                                 `json:"nameWithOwner"`
	UpdatedAt     time.Time                                                                              `json:"updatedAt"`
	Issues        CreateRepositoryCreateRepositoryCreateRepositoryPayloadRepositoryIssuesIssueConnection `json:"issues"`
}

// GetId returns CreateRepositoryCreateRepositoryCreateRepositoryPayloadRepository.Id, and is useful for accessing the field via an interface.
func (v *CreateRepositoryCreateRepositoryCreateRepositoryPayloadRepository) GetId() string {
	return v.Id
}

// GetNameWithOwner returns CreateRepositoryCreateRepositoryCreateRepositoryPayloadRepository.NameWithOwner, and is useful for accessing the field via an interface.
func (v *CreateRepositoryCreateRepositoryCreateRepositoryPayloadRepository) GetNameWithOwner() string {
	return v.NameWithOwner
}

// GetUpdatedAt returns CreateRepositoryCreateRepositoryCreateRepositoryPayloadRepository.UpdatedAt, and is useful for accessing the field via an interface.
func (v *CreateRepositoryCreateRepositoryCreateRepositoryPayloadRepository) GetUpdatedAt() time.Time {
	return v.UpdatedAt
}

// GetIssues returns CreateRepositoryCreateRepositoryCreateRepositoryPayloadRepository.Issues, and is useful for accessing the field via an interface.
func (v *CreateRepositoryCreateRepositoryCreateRepositoryPayloadRepository) GetIssues() CreateRepositoryCreateRepositoryCreateRepositoryPayloadRepositoryIssuesIssueConnection {
	return v.Issues
}

// CreateRepositoryCreateRepositoryCreateRepositoryPayloadRepositoryIssuesIssueConnection includes the requested fields of the GraphQL type IssueConnection.
type CreateRepositoryCreateRepositoryCreateRepositoryPayloadRepositoryIssuesIssueConnection struct {
	PageInfo CreateRepositoryCreateRepositoryCreateRepositoryPayloadRepositoryIssuesIssueConnectionPageInfo `json:"pageInfo"`
}

// GetPageInfo returns CreateRepositoryCreateRepositoryCreateRepositoryPayloadRepositoryIssuesIssueConnection.PageInfo, and is useful for accessing the field via an interface.
func (v *CreateRepositoryCreateRepositoryCreateRepositoryPayloadRepositoryIssuesIssueConnection) GetPageInfo() CreateRepositoryCreateRepositoryCreateRepositoryPayloadRepositoryIssuesIssueConnectionPageInfo {
	return v.PageInfo
}

// CreateRepositoryCreateRepositoryCreateRepositoryPayloadRepositoryIssuesIssueConnectionPageInfo includes the requested fields of the GraphQL type PageInfo.
type CreateRepositoryCreateRepositoryCreateRepositoryPayloadRepositoryIssuesIssueConnectionPageInfo struct {
	HasNextPage bool `json:"hasNextPage"`
}

// GetHasNextPage returns CreateRepositoryCreateRepositoryCreateRepositoryPayloadRepositoryIssuesIssueConnectionPageInfo.HasNextPage, and is useful for accessing the field via an interface.
func (v *CreateRepositoryCreateRepositoryCreateRepositoryPayloadRepositoryIssuesIssueConnectionPageInfo) GetHasNextPage() bool {
	return v.HasNextPage
}

type CreateRepositoryInput struct {
	Name             string                `json:"name"`
	OwnerId          *string               `json:"ownerId"`
	Visibility       *RepositoryVisibility `json:"visibility"`
	ClientMutationId *string               `json:"clientMutationId"`
}

// CreateRepositoryResponse is returned by CreateRepository on success.
type CreateRepositoryResponse struct {
	CreateRepository CreateRepositoryCreateRepositoryCreateRepositoryPayload `json:"createRepository"`
}

// GetCreateRepository returns CreateRepositoryResponse.CreateRepository, and is useful for accessing the field via an interface.
func (v *CreateRepositoryResponse) GetCreateRepository() CreateRepositoryCreateRepositoryCreateRepositoryPayload {
	return v.CreateRepository
}

// CreateRepositoryVariables contains the variables accepted by CreateRepository.
type CreateRepositoryVariables struct {
	Input CreateRepositoryInput `json:"input"`
}

// EchoAnyResponse is returned by EchoAny on success.
type EchoAnyResponse struct {
	EchoAny any `json:"echoAny"`
}

// GetEchoAny returns EchoAnyResponse.EchoAny, and is useful for accessing the field via an interface.
func (v *EchoAnyResponse) GetEchoAny() any { return v.EchoAny }

// EchoAnyVariables contains the variables accepted by EchoAny.
type EchoAnyVariables struct {
	Value any `json:"value"`
}

// EchoAtResponse is returned by EchoAt on success.
type EchoAtResponse struct {
	EchoAt time.Time `json:"echoAt"`
}

// GetEchoAt returns EchoAtResponse.EchoAt, and is useful for accessing the field via an interface.
func (v *EchoAtResponse) GetEchoAt() time.Time { return v.EchoAt }

// EchoAtVariables contains the variables accepted by EchoAt.
type EchoAtVariables struct {
	Value time.Time `json:"value"`
}

// EchoPropertyResponse is returned by EchoProperty on success.
type EchoPropertyResponse struct {
	EchoProperty json.RawMessage `json:"echoProperty"`
}

// GetEchoProperty returns EchoPropertyResponse.EchoProperty, and is useful for accessing the field via an interface.
func (v *EchoPropertyResponse) GetEchoProperty() json.RawMessage { return v.EchoProperty }

// EchoPropertyVariables contains the variables accepted by EchoProperty.
type EchoPropertyVariables struct {
	Value json.RawMessage `json:"value"`
}

// GetNodeNode includes the requested fields of the GraphQL interface Node.
//
// GetNodeNode is implemented by the following types:
// GetNodeNodeIssue
// GetNodeNodeRepository
// GetNodeNodeOctoqlOther
type GetNodeNode interface {
	implementsGraphQLInterfaceGetNodeNode()
	// GetTypename returns the receiver's concrete GraphQL type-name (see interface doc for possible values).
	GetTypename() string
	// GetId returns the interface-field "id" from its implementation.
	GetId() string
}

func (v *GetNodeNodeIssue) implementsGraphQLInterfaceGetNodeNode()       {}
func (v *GetNodeNodeRepository) implementsGraphQLInterfaceGetNodeNode()  {}
func (v *GetNodeNodeOctoqlOther) implementsGraphQLInterfaceGetNodeNode() {}

func __unmarshalGetNodeNode(b []byte, v *GetNodeNode) error {
	if string(b) == "null" {
		return nil
	}

	var tn struct {
		TypeName string `json:"__typename"`
	}
	err := json.Unmarshal(b, &tn)
	if err != nil {
		return err
	}

	switch tn.TypeName {
	case "Issue":
		*v = new(GetNodeNodeIssue)
		return json.Unmarshal(b, *v)
	case "Repository":
		*v = new(GetNodeNodeRepository)
		return json.Unmarshal(b, *v)
	case "":
		return fmt.Errorf(
			"response was missing Node.__typename")
	default:
		*v = new(GetNodeNodeOctoqlOther)
		return json.Unmarshal(b, *v)
	}
}

func __marshalGetNodeNode(v *GetNodeNode) ([]byte, error) {

	var typename string
	switch vv := (*v).(type) {
	case *GetNodeNodeIssue:
		if vv == nil {
			return []byte("null"), nil
		}
		typename = "Issue"

		result := struct {
			TypeName string `json:"__typename"`
			*GetNodeNodeIssue
		}{
			TypeName:         typename,
			GetNodeNodeIssue: vv,
		}
		return json.Marshal(result)
	case *GetNodeNodeRepository:
		if vv == nil {
			return []byte("null"), nil
		}
		typename = "Repository"

		result := struct {
			TypeName string `json:"__typename"`
			*GetNodeNodeRepository
		}{
			TypeName:              typename,
			GetNodeNodeRepository: vv,
		}
		return json.Marshal(result)
	case *GetNodeNodeOctoqlOther:
		if vv == nil {
			return []byte("null"), nil
		}
		return json.Marshal(vv)
	case nil:
		return []byte("null"), nil
	default:
		return nil, fmt.Errorf(
			`unexpected concrete type for GetNodeNode: "%T"`, vv)
	}
}

// GetNodeNodeIssue includes the requested fields of the GraphQL type Issue.
type GetNodeNodeIssue struct {
	Typename string `json:"__typename"`
	Id       string `json:"id"`
	Title    string `json:"title"`
}

// GetTypename returns GetNodeNodeIssue.Typename, and is useful for accessing the field via an interface.
func (v *GetNodeNodeIssue) GetTypename() string { return v.Typename }

// GetId returns GetNodeNodeIssue.Id, and is useful for accessing the field via an interface.
func (v *GetNodeNodeIssue) GetId() string { return v.Id }

// GetTitle returns GetNodeNodeIssue.Title, and is useful for accessing the field via an interface.
func (v *GetNodeNodeIssue) GetTitle() string { return v.Title }

// GetNodeNodeOctoqlOther represents GetNodeNode implementations not explicitly selected by a fragment. Use GetTypename to identify the concrete GraphQL type.
type GetNodeNodeOctoqlOther struct {
	Typename string `json:"__typename"`
	Id       string `json:"id"`
}

// GetTypename returns GetNodeNodeOctoqlOther.Typename, and is useful for accessing the field via an interface.
func (v *GetNodeNodeOctoqlOther) GetTypename() string { return v.Typename }

// GetId returns GetNodeNodeOctoqlOther.Id, and is useful for accessing the field via an interface.
func (v *GetNodeNodeOctoqlOther) GetId() string { return v.Id }

// GetNodeNodeRepository includes the requested fields of the GraphQL type Repository.
type GetNodeNodeRepository struct {
	Typename      string `json:"__typename"`
	Id            string `json:"id"`
	NameWithOwner string `json:"nameWithOwner"`
}

// GetTypename returns GetNodeNodeRepository.Typename, and is useful for accessing the field via an interface.
func (v *GetNodeNodeRepository) GetTypename() string { return v.Typename }

// GetId returns GetNodeNodeRepository.Id, and is useful for accessing the field via an interface.
func (v *GetNodeNodeRepository) GetId() string { return v.Id }

// GetNameWithOwner returns GetNodeNodeRepository.NameWithOwner, and is useful for accessing the field via an interface.
func (v *GetNodeNodeRepository) GetNameWithOwner() string { return v.NameWithOwner }

// GetNodeResponse is returned by GetNode on success.
type GetNodeResponse struct {
	Node GetNodeNode `json:"-"`
}

// GetNode returns GetNodeResponse.Node, and is useful for accessing the field via an interface.
func (v *GetNodeResponse) GetNode() GetNodeNode { return v.Node }

func (v *GetNodeResponse) UnmarshalJSON(b []byte) error {

	if string(b) == "null" {
		return nil
	}

	var firstPass struct {
		*GetNodeResponse
		Node json.RawMessage `json:"node"`
		noUnmarshalJSON
	}
	firstPass.GetNodeResponse = v

	err := json.Unmarshal(b, &firstPass)
	if err != nil {
		return err
	}

	{
		dst := &v.Node
		src := firstPass.Node
		if len(src) != 0 && string(src) == "null" {
			*dst = nil
		}
		if len(src) != 0 && string(src) != "null" {
			err = __unmarshalGetNodeNode(
				src, dst)
			if err != nil {
				return fmt.Errorf(
					"unable to unmarshal GetNodeResponse.Node: %w", err)
			}
		}
	}
	return nil
}

type __premarshalGetNodeResponse struct {
	Node json.RawMessage `json:"node"`
}

func (v *GetNodeResponse) MarshalJSON() ([]byte, error) {
	premarshaled, err := v.__premarshalJSON()
	if err != nil {
		return nil, err
	}
	return json.Marshal(premarshaled)
}

func (v *GetNodeResponse) __premarshalJSON() (*__premarshalGetNodeResponse, error) {
	var retval __premarshalGetNodeResponse

	{

		dst := &retval.Node
		src := v.Node
		var err error
		*dst, err = __marshalGetNodeNode(
			&src)
		if err != nil {
			return nil, fmt.Errorf(
				"unable to marshal GetNodeResponse.Node: %w", err)
		}
	}
	return &retval, nil
}

// GetNodeVariables contains the variables accepted by GetNode.
type GetNodeVariables struct {
	Id string `json:"id"`
}

// GetRepositoryRepository includes the requested fields of the GraphQL type Repository.
type GetRepositoryRepository struct {
	Id            string                                       `json:"id"`
	FullName      string                                       `json:"fullName"`
	UpdatedAt     time.Time                                    `json:"updatedAt"`
	PropertyValue json.RawMessage                              `json:"propertyValue"`
	Issues        GetRepositoryRepositoryIssuesIssueConnection `json:"issues"`
}

// GetId returns GetRepositoryRepository.Id, and is useful for accessing the field via an interface.
func (v *GetRepositoryRepository) GetId() string { return v.Id }

// GetFullName returns GetRepositoryRepository.FullName, and is useful for accessing the field via an interface.
func (v *GetRepositoryRepository) GetFullName() string { return v.FullName }

// GetUpdatedAt returns GetRepositoryRepository.UpdatedAt, and is useful for accessing the field via an interface.
func (v *GetRepositoryRepository) GetUpdatedAt() time.Time { return v.UpdatedAt }

// GetPropertyValue returns GetRepositoryRepository.PropertyValue, and is useful for accessing the field via an interface.
func (v *GetRepositoryRepository) GetPropertyValue() json.RawMessage { return v.PropertyValue }

// GetIssues returns GetRepositoryRepository.Issues, and is useful for accessing the field via an interface.
func (v *GetRepositoryRepository) GetIssues() GetRepositoryRepositoryIssuesIssueConnection {
	return v.Issues
}

// GetRepositoryRepositoryIssuesIssueConnection includes the requested fields of the GraphQL type IssueConnection.
type GetRepositoryRepositoryIssuesIssueConnection struct {
	Nodes    []GetRepositoryRepositoryIssuesIssueConnectionNodesIssue `json:"nodes"`
	PageInfo GetRepositoryRepositoryIssuesIssueConnectionPageInfo     `json:"pageInfo"`
}

// GetNodes returns GetRepositoryRepositoryIssuesIssueConnection.Nodes, and is useful for accessing the field via an interface.
func (v *GetRepositoryRepositoryIssuesIssueConnection) GetNodes() []GetRepositoryRepositoryIssuesIssueConnectionNodesIssue {
	return v.Nodes
}

// GetPageInfo returns GetRepositoryRepositoryIssuesIssueConnection.PageInfo, and is useful for accessing the field via an interface.
func (v *GetRepositoryRepositoryIssuesIssueConnection) GetPageInfo() GetRepositoryRepositoryIssuesIssueConnectionPageInfo {
	return v.PageInfo
}

// GetRepositoryRepositoryIssuesIssueConnectionNodesIssue includes the requested fields of the GraphQL type Issue.
type GetRepositoryRepositoryIssuesIssueConnectionNodesIssue struct {
	Id    string `json:"id"`
	Title string `json:"title"`
}

// GetId returns GetRepositoryRepositoryIssuesIssueConnectionNodesIssue.Id, and is useful for accessing the field via an interface.
func (v *GetRepositoryRepositoryIssuesIssueConnectionNodesIssue) GetId() string { return v.Id }

// GetTitle returns GetRepositoryRepositoryIssuesIssueConnectionNodesIssue.Title, and is useful for accessing the field via an interface.
func (v *GetRepositoryRepositoryIssuesIssueConnectionNodesIssue) GetTitle() string { return v.Title }

// GetRepositoryRepositoryIssuesIssueConnectionPageInfo includes the requested fields of the GraphQL type PageInfo.
type GetRepositoryRepositoryIssuesIssueConnectionPageInfo struct {
	HasNextPage bool    `json:"hasNextPage"`
	EndCursor   *string `json:"endCursor"`
}

// GetHasNextPage returns GetRepositoryRepositoryIssuesIssueConnectionPageInfo.HasNextPage, and is useful for accessing the field via an interface.
func (v *GetRepositoryRepositoryIssuesIssueConnectionPageInfo) GetHasNextPage() bool {
	return v.HasNextPage
}

// GetEndCursor returns GetRepositoryRepositoryIssuesIssueConnectionPageInfo.EndCursor, and is useful for accessing the field via an interface.
func (v *GetRepositoryRepositoryIssuesIssueConnectionPageInfo) GetEndCursor() *string {
	return v.EndCursor
}

// GetRepositoryResponse is returned by GetRepository on success.
type GetRepositoryResponse struct {
	Repository *GetRepositoryRepository `json:"repository"`
}

// GetRepository returns GetRepositoryResponse.Repository, and is useful for accessing the field via an interface.
func (v *GetRepositoryResponse) GetRepository() *GetRepositoryRepository { return v.Repository }

// GetRepositoryVariables contains the variables accepted by GetRepository.
type GetRepositoryVariables struct {
	Owner string  `json:"owner"`
	Name  string  `json:"name"`
	First int     `json:"first"`
	After *string `json:"after"`
}

type RepositoryVisibility string

const (
	RepositoryVisibilityPrivate RepositoryVisibility = "PRIVATE"
	RepositoryVisibilityPublic  RepositoryVisibility = "PUBLIC"
)

var AllRepositoryVisibility = []RepositoryVisibility{
	RepositoryVisibilityPrivate,
	RepositoryVisibilityPublic,
}

// SearchResponse is returned by Search on success.
type SearchResponse struct {
	Search []SearchSearchSearchResultItem `json:"-"`
}

// GetSearch returns SearchResponse.Search, and is useful for accessing the field via an interface.
func (v *SearchResponse) GetSearch() []SearchSearchSearchResultItem { return v.Search }

func (v *SearchResponse) UnmarshalJSON(b []byte) error {

	if string(b) == "null" {
		return nil
	}

	var firstPass struct {
		*SearchResponse
		Search json.RawMessage `json:"search"`
		noUnmarshalJSON
	}
	firstPass.SearchResponse = v

	err := json.Unmarshal(b, &firstPass)
	if err != nil {
		return err
	}

	{
		dst := &v.Search
		raw := firstPass.Search
		if len(raw) != 0 {
			if string(raw) == "null" {
				*dst = nil
			}
			if string(raw) != "null" {
				var src []json.RawMessage
				err = json.Unmarshal(raw, &src)
				if err != nil {
					return fmt.Errorf(
						"unable to unmarshal SearchResponse.Search: %w", err)
				}
				if src != nil {
					*dst = make(
						[]SearchSearchSearchResultItem,
						len(src))
					for i, src := range src {
						dst := &(*dst)[i]
						if len(src) != 0 && string(src) != "null" {
							err = __unmarshalSearchSearchSearchResultItem(
								src, dst)
							if err != nil {
								return fmt.Errorf(
									"unable to unmarshal SearchResponse.Search: %w", err)
							}
						}
					}
				}
			}
		}
	}
	return nil
}

type __premarshalSearchResponse struct {
	Search []json.RawMessage `json:"search"`
}

func (v *SearchResponse) MarshalJSON() ([]byte, error) {
	premarshaled, err := v.__premarshalJSON()
	if err != nil {
		return nil, err
	}
	return json.Marshal(premarshaled)
}

func (v *SearchResponse) __premarshalJSON() (*__premarshalSearchResponse, error) {
	var retval __premarshalSearchResponse

	{

		dst := &retval.Search
		src := v.Search
		if src != nil {
			*dst = make(
				[]json.RawMessage,
				len(src))
			for i, src := range src {
				dst := &(*dst)[i]
				var err error
				*dst, err = __marshalSearchSearchSearchResultItem(
					&src)
				if err != nil {
					return nil, fmt.Errorf(
						"unable to marshal SearchResponse.Search: %w", err)
				}
			}
		}
	}
	return &retval, nil
}

// SearchSearchIssue includes the requested fields of the GraphQL type Issue.
type SearchSearchIssue struct {
	Typename string `json:"__typename"`
	Id       string `json:"id"`
	Title    string `json:"title"`
}

// GetTypename returns SearchSearchIssue.Typename, and is useful for accessing the field via an interface.
func (v *SearchSearchIssue) GetTypename() string { return v.Typename }

// GetId returns SearchSearchIssue.Id, and is useful for accessing the field via an interface.
func (v *SearchSearchIssue) GetId() string { return v.Id }

// GetTitle returns SearchSearchIssue.Title, and is useful for accessing the field via an interface.
func (v *SearchSearchIssue) GetTitle() string { return v.Title }

// SearchSearchRepository includes the requested fields of the GraphQL type Repository.
type SearchSearchRepository struct {
	Typename      string `json:"__typename"`
	Id            string `json:"id"`
	NameWithOwner string `json:"nameWithOwner"`
}

// GetTypename returns SearchSearchRepository.Typename, and is useful for accessing the field via an interface.
func (v *SearchSearchRepository) GetTypename() string { return v.Typename }

// GetId returns SearchSearchRepository.Id, and is useful for accessing the field via an interface.
func (v *SearchSearchRepository) GetId() string { return v.Id }

// GetNameWithOwner returns SearchSearchRepository.NameWithOwner, and is useful for accessing the field via an interface.
func (v *SearchSearchRepository) GetNameWithOwner() string { return v.NameWithOwner }

// SearchSearchSearchResultItem includes the requested fields of the GraphQL interface SearchResultItem.
//
// SearchSearchSearchResultItem is implemented by the following types:
// SearchSearchIssue
// SearchSearchRepository
// SearchSearchSearchResultItemOctoqlOther
type SearchSearchSearchResultItem interface {
	implementsGraphQLInterfaceSearchSearchSearchResultItem()
	// GetTypename returns the receiver's concrete GraphQL type-name (see interface doc for possible values).
	GetTypename() string
}

func (v *SearchSearchIssue) implementsGraphQLInterfaceSearchSearchSearchResultItem()      {}
func (v *SearchSearchRepository) implementsGraphQLInterfaceSearchSearchSearchResultItem() {}
func (v *SearchSearchSearchResultItemOctoqlOther) implementsGraphQLInterfaceSearchSearchSearchResultItem() {
}

func __unmarshalSearchSearchSearchResultItem(b []byte, v *SearchSearchSearchResultItem) error {
	if string(b) == "null" {
		return nil
	}

	var tn struct {
		TypeName string `json:"__typename"`
	}
	err := json.Unmarshal(b, &tn)
	if err != nil {
		return err
	}

	switch tn.TypeName {
	case "Issue":
		*v = new(SearchSearchIssue)
		return json.Unmarshal(b, *v)
	case "Repository":
		*v = new(SearchSearchRepository)
		return json.Unmarshal(b, *v)
	case "":
		return fmt.Errorf(
			"response was missing SearchResultItem.__typename")
	default:
		*v = new(SearchSearchSearchResultItemOctoqlOther)
		return json.Unmarshal(b, *v)
	}
}

func __marshalSearchSearchSearchResultItem(v *SearchSearchSearchResultItem) ([]byte, error) {

	var typename string
	switch vv := (*v).(type) {
	case *SearchSearchIssue:
		if vv == nil {
			return []byte("null"), nil
		}
		typename = "Issue"

		result := struct {
			TypeName string `json:"__typename"`
			*SearchSearchIssue
		}{
			TypeName:          typename,
			SearchSearchIssue: vv,
		}
		return json.Marshal(result)
	case *SearchSearchRepository:
		if vv == nil {
			return []byte("null"), nil
		}
		typename = "Repository"

		result := struct {
			TypeName string `json:"__typename"`
			*SearchSearchRepository
		}{
			TypeName:               typename,
			SearchSearchRepository: vv,
		}
		return json.Marshal(result)
	case *SearchSearchSearchResultItemOctoqlOther:
		if vv == nil {
			return []byte("null"), nil
		}
		return json.Marshal(vv)
	case nil:
		return []byte("null"), nil
	default:
		return nil, fmt.Errorf(
			`unexpected concrete type for SearchSearchSearchResultItem: "%T"`, vv)
	}
}

// SearchSearchSearchResultItemOctoqlOther represents SearchSearchSearchResultItem implementations not explicitly selected by a fragment. Use GetTypename to identify the concrete GraphQL type.
type SearchSearchSearchResultItemOctoqlOther struct {
	Typename string `json:"__typename"`
}

// GetTypename returns SearchSearchSearchResultItemOctoqlOther.Typename, and is useful for accessing the field via an interface.
func (v *SearchSearchSearchResultItemOctoqlOther) GetTypename() string { return v.Typename }

// SearchVariables contains the variables accepted by Search.
type SearchVariables struct {
	Query string `json:"query"`
}

// ViewerResponse is returned by Viewer on success.
type ViewerResponse struct {
	Viewer ViewerViewerUser `json:"viewer"`
}

// GetViewer returns ViewerResponse.Viewer, and is useful for accessing the field via an interface.
func (v *ViewerResponse) GetViewer() ViewerViewerUser { return v.Viewer }

// ViewerVariables includes the GraphQL fields of User requested by the fragment ViewerVariables.
type ViewerVariables struct {
	Id    string `json:"id"`
	Login string `json:"login"`
}

// GetId returns ViewerVariables.Id, and is useful for accessing the field via an interface.
func (v *ViewerVariables) GetId() string { return v.Id }

// GetLogin returns ViewerVariables.Login, and is useful for accessing the field via an interface.
func (v *ViewerVariables) GetLogin() string { return v.Login }

// ViewerViewerUser includes the requested fields of the GraphQL type User.
type ViewerViewerUser struct {
	ViewerVariables `json:"-"`
}

// GetId returns ViewerViewerUser.Id, and is useful for accessing the field via an interface.
func (v *ViewerViewerUser) GetId() string { return v.ViewerVariables.Id }

// GetLogin returns ViewerViewerUser.Login, and is useful for accessing the field via an interface.
func (v *ViewerViewerUser) GetLogin() string { return v.ViewerVariables.Login }

func (v *ViewerViewerUser) UnmarshalJSON(b []byte) error {

	if string(b) == "null" {
		return nil
	}

	var firstPass struct {
		*ViewerViewerUser
		noUnmarshalJSON
	}
	firstPass.ViewerViewerUser = v

	err := json.Unmarshal(b, &firstPass)
	if err != nil {
		return err
	}

	err = json.Unmarshal(
		b, &v.ViewerVariables)
	if err != nil {
		return err
	}
	return nil
}

type __premarshalViewerViewerUser struct {
	Id string `json:"id"`

	Login string `json:"login"`
}

func (v *ViewerViewerUser) MarshalJSON() ([]byte, error) {
	premarshaled, err := v.__premarshalJSON()
	if err != nil {
		return nil, err
	}
	return json.Marshal(premarshaled)
}

func (v *ViewerViewerUser) __premarshalJSON() (*__premarshalViewerViewerUser, error) {
	var retval __premarshalViewerViewerUser

	retval.Id = v.ViewerVariables.Id
	retval.Login = v.ViewerVariables.Login
	return &retval, nil
}

// The mutation executed by CreateRepository.
const CreateRepository_Operation = "\nmutation CreateRepository ($input: CreateRepositoryInput!) {\n\tcreateRepository(input: $input) {\n\t\trepository {\n\t\t\tid\n\t\t\tnameWithOwner\n\t\t\tupdatedAt\n\t\t\tissues(first: 1) {\n\t\t\t\tpageInfo {\n\t\t\t\t\thasNextPage\n\t\t\t\t}\n\t\t\t}\n\t\t}\n\t\tclientMutationId\n\t}\n}\n"

// CreateRepositoryPartialDataError contains partial data returned by CreateRepository.
type CreateRepositoryPartialDataError struct {
	data *CreateRepositoryResponse
	err  error
}

func (e *CreateRepositoryPartialDataError) Error() string {
	if e == nil || e.err == nil {
		return "graphql response contains partial data"
	}
	return e.err.Error()
}

func (e *CreateRepositoryPartialDataError) Unwrap() error {
	if e == nil {
		return nil
	}
	return e.err
}

func (e *CreateRepositoryPartialDataError) PartialData() *CreateRepositoryResponse {
	if e == nil {
		return nil
	}
	return e.data
}

// PartialDataValue returns the partial response as an untyped value.
func (e *CreateRepositoryPartialDataError) PartialDataValue() any {
	return e.PartialData()
}

func (c *Client) CreateRepository(
	ctx context.Context,
	vars CreateRepositoryVariables,
) (*CreateRepositoryResponse, error) {
	var response CreateRepositoryResponse
	hasData, err := c.execute(
		ctx,
		payload{
			OperationName: "CreateRepository",
			Query:         CreateRepository_Operation,
			Variables:     &vars,
		},
		&response,
	)
	if !hasData {
		return nil, err
	}
	if err != nil {
		return nil, &CreateRepositoryPartialDataError{
			data: &response,
			err:  err,
		}
	}
	return &response, nil
}

// The query executed by EchoAny.
const EchoAny_Operation = "\nquery EchoAny ($value: ArbitraryJSON!) {\n\techoAny(value: $value)\n}\n"

// EchoAnyPartialDataError contains partial data returned by EchoAny.
type EchoAnyPartialDataError struct {
	data *EchoAnyResponse
	err  error
}

func (e *EchoAnyPartialDataError) Error() string {
	if e == nil || e.err == nil {
		return "graphql response contains partial data"
	}
	return e.err.Error()
}

func (e *EchoAnyPartialDataError) Unwrap() error {
	if e == nil {
		return nil
	}
	return e.err
}

func (e *EchoAnyPartialDataError) PartialData() *EchoAnyResponse {
	if e == nil {
		return nil
	}
	return e.data
}

// PartialDataValue returns the partial response as an untyped value.
func (e *EchoAnyPartialDataError) PartialDataValue() any {
	return e.PartialData()
}

func (c *Client) EchoAny(
	ctx context.Context,
	vars EchoAnyVariables,
) (*EchoAnyResponse, error) {
	var response EchoAnyResponse
	hasData, err := c.execute(
		ctx,
		payload{
			OperationName: "EchoAny",
			Query:         EchoAny_Operation,
			Variables:     &vars,
		},
		&response,
	)
	if !hasData {
		return nil, err
	}
	if err != nil {
		return nil, &EchoAnyPartialDataError{
			data: &response,
			err:  err,
		}
	}
	return &response, nil
}

// The query executed by EchoAt.
const EchoAt_Operation = "\nquery EchoAt ($value: DateTime!) {\n\techoAt(value: $value)\n}\n"

// EchoAtPartialDataError contains partial data returned by EchoAt.
type EchoAtPartialDataError struct {
	data *EchoAtResponse
	err  error
}

func (e *EchoAtPartialDataError) Error() string {
	if e == nil || e.err == nil {
		return "graphql response contains partial data"
	}
	return e.err.Error()
}

func (e *EchoAtPartialDataError) Unwrap() error {
	if e == nil {
		return nil
	}
	return e.err
}

func (e *EchoAtPartialDataError) PartialData() *EchoAtResponse {
	if e == nil {
		return nil
	}
	return e.data
}

// PartialDataValue returns the partial response as an untyped value.
func (e *EchoAtPartialDataError) PartialDataValue() any {
	return e.PartialData()
}

func (c *Client) EchoAt(
	ctx context.Context,
	vars EchoAtVariables,
) (*EchoAtResponse, error) {
	var response EchoAtResponse
	hasData, err := c.execute(
		ctx,
		payload{
			OperationName: "EchoAt",
			Query:         EchoAt_Operation,
			Variables:     &vars,
		},
		&response,
	)
	if !hasData {
		return nil, err
	}
	if err != nil {
		return nil, &EchoAtPartialDataError{
			data: &response,
			err:  err,
		}
	}
	return &response, nil
}

// The query executed by EchoProperty.
const EchoProperty_Operation = "\nquery EchoProperty ($value: CustomPropertyValue!) {\n\techoProperty(value: $value)\n}\n"

// EchoPropertyPartialDataError contains partial data returned by EchoProperty.
type EchoPropertyPartialDataError struct {
	data *EchoPropertyResponse
	err  error
}

func (e *EchoPropertyPartialDataError) Error() string {
	if e == nil || e.err == nil {
		return "graphql response contains partial data"
	}
	return e.err.Error()
}

func (e *EchoPropertyPartialDataError) Unwrap() error {
	if e == nil {
		return nil
	}
	return e.err
}

func (e *EchoPropertyPartialDataError) PartialData() *EchoPropertyResponse {
	if e == nil {
		return nil
	}
	return e.data
}

// PartialDataValue returns the partial response as an untyped value.
func (e *EchoPropertyPartialDataError) PartialDataValue() any {
	return e.PartialData()
}

func (c *Client) EchoProperty(
	ctx context.Context,
	vars EchoPropertyVariables,
) (*EchoPropertyResponse, error) {
	var response EchoPropertyResponse
	hasData, err := c.execute(
		ctx,
		payload{
			OperationName: "EchoProperty",
			Query:         EchoProperty_Operation,
			Variables:     &vars,
		},
		&response,
	)
	if !hasData {
		return nil, err
	}
	if err != nil {
		return nil, &EchoPropertyPartialDataError{
			data: &response,
			err:  err,
		}
	}
	return &response, nil
}

// The query executed by GetNode.
const GetNode_Operation = "\nquery GetNode ($id: ID!) {\n\tnode(id: $id) {\n\t\t__typename\n\t\tid\n\t\t... on Repository {\n\t\t\tnameWithOwner\n\t\t}\n\t\t... on Issue {\n\t\t\ttitle\n\t\t}\n\t}\n}\n"

// GetNodePartialDataError contains partial data returned by GetNode.
type GetNodePartialDataError struct {
	data *GetNodeResponse
	err  error
}

func (e *GetNodePartialDataError) Error() string {
	if e == nil || e.err == nil {
		return "graphql response contains partial data"
	}
	return e.err.Error()
}

func (e *GetNodePartialDataError) Unwrap() error {
	if e == nil {
		return nil
	}
	return e.err
}

func (e *GetNodePartialDataError) PartialData() *GetNodeResponse {
	if e == nil {
		return nil
	}
	return e.data
}

// PartialDataValue returns the partial response as an untyped value.
func (e *GetNodePartialDataError) PartialDataValue() any {
	return e.PartialData()
}

func (c *Client) GetNode(
	ctx context.Context,
	vars GetNodeVariables,
) (*GetNodeResponse, error) {
	var response GetNodeResponse
	hasData, err := c.execute(
		ctx,
		payload{
			OperationName: "GetNode",
			Query:         GetNode_Operation,
			Variables:     &vars,
		},
		&response,
	)
	if !hasData {
		return nil, err
	}
	if err != nil {
		return nil, &GetNodePartialDataError{
			data: &response,
			err:  err,
		}
	}
	return &response, nil
}

// The query executed by GetRepository.
const GetRepository_Operation = "\nquery GetRepository ($owner: String!, $name: String!, $first: Int!, $after: String) {\n\trepository(owner: $owner, name: $name, first: $first, after: $after) {\n\t\tid\n\t\tfullName: nameWithOwner\n\t\tupdatedAt\n\t\tpropertyValue\n\t\tissues(first: $first, after: $after) {\n\t\t\tnodes {\n\t\t\t\tid\n\t\t\t\ttitle\n\t\t\t}\n\t\t\tpageInfo {\n\t\t\t\thasNextPage\n\t\t\t\tendCursor\n\t\t\t}\n\t\t}\n\t}\n}\n"

// GetRepositoryPartialDataError contains partial data returned by GetRepository.
type GetRepositoryPartialDataError struct {
	data *GetRepositoryResponse
	err  error
}

func (e *GetRepositoryPartialDataError) Error() string {
	if e == nil || e.err == nil {
		return "graphql response contains partial data"
	}
	return e.err.Error()
}

func (e *GetRepositoryPartialDataError) Unwrap() error {
	if e == nil {
		return nil
	}
	return e.err
}

func (e *GetRepositoryPartialDataError) PartialData() *GetRepositoryResponse {
	if e == nil {
		return nil
	}
	return e.data
}

// PartialDataValue returns the partial response as an untyped value.
func (e *GetRepositoryPartialDataError) PartialDataValue() any {
	return e.PartialData()
}

func (c *Client) GetRepository(
	ctx context.Context,
	vars GetRepositoryVariables,
) (*GetRepositoryResponse, error) {
	var response GetRepositoryResponse
	hasData, err := c.execute(
		ctx,
		payload{
			OperationName: "GetRepository",
			Query:         GetRepository_Operation,
			Variables:     &vars,
		},
		&response,
	)
	if !hasData {
		return nil, err
	}
	if err != nil {
		return nil, &GetRepositoryPartialDataError{
			data: &response,
			err:  err,
		}
	}
	return &response, nil
}

// The query executed by Search.
const Search_Operation = "\nquery Search ($query: String!) {\n\tsearch(query: $query) {\n\t\t__typename\n\t\t... on Repository {\n\t\t\tid\n\t\t\tnameWithOwner\n\t\t}\n\t\t... on Issue {\n\t\t\tid\n\t\t\ttitle\n\t\t}\n\t}\n}\n"

// SearchPartialDataError contains partial data returned by Search.
type SearchPartialDataError struct {
	data *SearchResponse
	err  error
}

func (e *SearchPartialDataError) Error() string {
	if e == nil || e.err == nil {
		return "graphql response contains partial data"
	}
	return e.err.Error()
}

func (e *SearchPartialDataError) Unwrap() error {
	if e == nil {
		return nil
	}
	return e.err
}

func (e *SearchPartialDataError) PartialData() *SearchResponse {
	if e == nil {
		return nil
	}
	return e.data
}

// PartialDataValue returns the partial response as an untyped value.
func (e *SearchPartialDataError) PartialDataValue() any {
	return e.PartialData()
}

func (c *Client) Search(
	ctx context.Context,
	vars SearchVariables,
) (*SearchResponse, error) {
	var response SearchResponse
	hasData, err := c.execute(
		ctx,
		payload{
			OperationName: "Search",
			Query:         Search_Operation,
			Variables:     &vars,
		},
		&response,
	)
	if !hasData {
		return nil, err
	}
	if err != nil {
		return nil, &SearchPartialDataError{
			data: &response,
			err:  err,
		}
	}
	return &response, nil
}

// The query executed by Viewer.
const Viewer_Operation = "\nquery Viewer {\n\tviewer {\n\t\t... ViewerVariables\n\t}\n}\nfragment ViewerVariables on User {\n\tid\n\tlogin\n}\n"

// ViewerPartialDataError contains partial data returned by Viewer.
type ViewerPartialDataError struct {
	data *ViewerResponse
	err  error
}

func (e *ViewerPartialDataError) Error() string {
	if e == nil || e.err == nil {
		return "graphql response contains partial data"
	}
	return e.err.Error()
}

func (e *ViewerPartialDataError) Unwrap() error {
	if e == nil {
		return nil
	}
	return e.err
}

func (e *ViewerPartialDataError) PartialData() *ViewerResponse {
	if e == nil {
		return nil
	}
	return e.data
}

// PartialDataValue returns the partial response as an untyped value.
func (e *ViewerPartialDataError) PartialDataValue() any {
	return e.PartialData()
}

func (c *Client) Viewer(
	ctx context.Context,
) (*ViewerResponse, error) {
	var response ViewerResponse
	hasData, err := c.execute(
		ctx,
		payload{
			OperationName: "Viewer",
			Query:         Viewer_Operation,
			Variables:     nil,
		},
		&response,
	)
	if !hasData {
		return nil, err
	}
	if err != nil {
		return nil, &ViewerPartialDataError{
			data: &response,
			err:  err,
		}
	}
	return &response, nil
}
