// Code generated by octoqlgen, DO NOT EDIT.

package clientgetter

import (
	"context"

	"github.com/willabides/octoql"
)

// Check that context_type from octoqlgen.yaml implements context.Context.
var _ context.Context = (customContext)(nil)

// __getRepositoryInput is used internally by octoqlgen
type __getRepositoryInput struct {
	Owner string `json:"owner"`
	Name  string `json:"name"`
}

// GetOwner returns __getRepositoryInput.Owner, and is useful for accessing the field via an interface.
func (v *__getRepositoryInput) GetOwner() string { return v.Owner }

// GetName returns __getRepositoryInput.Name, and is useful for accessing the field via an interface.
func (v *__getRepositoryInput) GetName() string { return v.Name }

// getRepositoryRepository includes the requested fields of the GraphQL type Repository.
type getRepositoryRepository struct {
	NameWithOwner string `json:"nameWithOwner"`
}

// GetNameWithOwner returns getRepositoryRepository.NameWithOwner, and is useful for accessing the field via an interface.
func (v *getRepositoryRepository) GetNameWithOwner() string { return v.NameWithOwner }

// getRepositoryResponse is returned by getRepository on success.
type getRepositoryResponse struct {
	Repository getRepositoryRepository `json:"repository"`
}

// GetRepository returns getRepositoryResponse.Repository, and is useful for accessing the field via an interface.
func (v *getRepositoryResponse) GetRepository() getRepositoryRepository { return v.Repository }

// The query executed by getRepository.
const getRepository_Operation = `
query getRepository ($owner: String!, $name: String!) {
	repository(owner: $owner, name: $name) {
		nameWithOwner
	}
}
`

func getRepository(
	ctx_ customContext,
	owner string,
	name string,
) (*octoql.Response[getRepositoryResponse], error) {
	client_, err_ := getClient(ctx_)
	if err_ != nil {
		return nil, err_
	}
	variables_ := __getRepositoryInput{
		Owner: owner,
		Name:  name,
	}
	return octoql.Do[getRepositoryResponse](
		ctx_,
		client_,
		octoql.Operation{
			Name:  "getRepository",
			Query: getRepository_Operation,
		},
		&variables_,
	)
}
