// Code generated by octoqlgen, DO NOT EDIT.

package clientgetter

import (
	"context"

	"github.com/willabides/octoql"
)

// Check that context_type from octoqlgen.yaml implements context.Context.
var _ context.Context = (customContext)(nil)

// __getRepositoryInput is used internally by octoqlgen
type __getRepositoryInput struct {
	Owner string `json:"owner"`
	Name  string `json:"name"`
}

// getRepositoryRepository includes the requested fields of the GraphQL type Repository.
type getRepositoryRepository struct {
	NameWithOwner string `json:"nameWithOwner"`
}

// GetNameWithOwner returns getRepositoryRepository.NameWithOwner, and is useful for accessing the field via an interface.
func (v *getRepositoryRepository) GetNameWithOwner() string { return v.NameWithOwner }

// getRepositoryResponse is returned by getRepository on success.
type getRepositoryResponse struct {
	Repository getRepositoryRepository `json:"repository"`
}

// GetRepository returns getRepositoryResponse.Repository, and is useful for accessing the field via an interface.
func (v *getRepositoryResponse) GetRepository() getRepositoryRepository { return v.Repository }

// The query executed by getRepository.
const getRepository_Operation = `
query getRepository ($owner: String!, $name: String!) {
	repository(owner: $owner, name: $name) {
		nameWithOwner
	}
}
`

// getRepositoryPartialDataError contains partial data returned by getRepository.
type getRepositoryPartialDataError struct {
	data *getRepositoryResponse
	err  error
}

func (e *getRepositoryPartialDataError) Error() string {
	if e == nil || e.err == nil {
		return "graphql response contains partial data"
	}
	return e.err.Error()
}

func (e *getRepositoryPartialDataError) Unwrap() error {
	if e == nil {
		return nil
	}
	return e.err
}

func (e *getRepositoryPartialDataError) PartialData() *getRepositoryResponse {
	if e == nil {
		return nil
	}
	return e.data
}

func getRepository(
	ctx_ customContext,
	owner string,
	name string,
) (*getRepositoryResponse, error) {
	client_, err_ := getClient(ctx_)
	if err_ != nil {
		return nil, err_
	}
	variables_ := __getRepositoryInput{
		Owner: owner,
		Name:  name,
	}
	var response_ getRepositoryResponse
	hasData_, err_ := client_.Execute(
		ctx_,
		octoql.Payload{
			OperationName: "getRepository",
			Query:         getRepository_Operation,
			Variables:     &variables_,
		},
		&response_,
	)
	if !hasData_ {
		return nil, err_
	}
	if err_ != nil {
		return nil, &getRepositoryPartialDataError{
			data: &response_,
			err:  err_,
		}
	}
	return &response_, nil
}
