// Code generated by octoqlgen, DO NOT EDIT.

package clientgetter

import (
	"context"

	"github.com/willabides/octoql"
)

// Check that context_type from octoqlgen.yaml implements context.Context.
var _ context.Context = (customContext)(nil)

// getRepositoryRepository includes the requested fields of the GraphQL type Repository.
type getRepositoryRepository struct {
	NameWithOwner string `json:"nameWithOwner"`
}

// GetNameWithOwner returns getRepositoryRepository.NameWithOwner, and is useful for accessing the field via an interface.
func (v *getRepositoryRepository) GetNameWithOwner() string { return v.NameWithOwner }

// getRepositoryResponse is returned by getRepository on success.
type getRepositoryResponse struct {
	Repository getRepositoryRepository `json:"repository"`
}

// GetRepository returns getRepositoryResponse.Repository, and is useful for accessing the field via an interface.
func (v *getRepositoryResponse) GetRepository() getRepositoryRepository { return v.Repository }

// getRepositoryVariables contains the variables accepted by getRepository.
type getRepositoryVariables struct {
	Owner string `json:"owner"`
	Name  string `json:"name"`
}

// The query executed by getRepository.
const getRepository_Operation = "\nquery getRepository ($owner: String!, $name: String!) {\n\trepository(owner: $owner, name: $name) {\n\t\tnameWithOwner\n\t}\n}\n"

// getRepositoryPartialDataError contains partial data returned by getRepository.
type getRepositoryPartialDataError struct {
	data *getRepositoryResponse
	err  error
}

func (e *getRepositoryPartialDataError) Error() string {
	if e == nil || e.err == nil {
		return "graphql response contains partial data"
	}
	return e.err.Error()
}

func (e *getRepositoryPartialDataError) Unwrap() error {
	if e == nil {
		return nil
	}
	return e.err
}

func (e *getRepositoryPartialDataError) PartialData() *getRepositoryResponse {
	if e == nil {
		return nil
	}
	return e.data
}

func getRepository(
	ctx customContext,
	vars getRepositoryVariables,
) (*getRepositoryResponse, error) {
	client, err := getClient(ctx)
	if err != nil {
		return nil, err
	}
	var response getRepositoryResponse
	hasData, err := client.Execute(
		ctx,
		octoql.Payload{
			OperationName: "getRepository",
			Query:         getRepository_Operation,
			Variables:     &vars,
		},
		&response,
	)
	if !hasData {
		return nil, err
	}
	if err != nil {
		return nil, &getRepositoryPartialDataError{
			data: &response,
			err:  err,
		}
	}
	return &response, nil
}
