// Copyright (c) 2026 octoql contributors
// SPDX-License-Identifier: MIT
// Code generated by jsonschematogo for octoqlgen. DO NOT EDIT.

package config

type Revision = string

type GitHubDocs struct {
	Revision Revision `json:"revision"`
	Version  string   `json:"version"`
}

type GitHubRepository struct {
	Host       string   `json:"host"`
	Path       string   `json:"path"`
	Repository string   `json:"repository"`
	Revision   Revision `json:"revision"`
}

type URL = string

type Source struct {
	GitHubDocs       *GitHubDocs       `json:"github_docs"`
	GitHubRepository *GitHubRepository `json:"github_repository"`
	URL              *URL              `json:"url"`
}

type Schema struct {
	Path   string `json:"path"`
	SHA256 string `json:"sha256"`
	Source Source `json:"source"`
}

type TestHandler struct {
	Generated string `json:"generated"`
}

type ConfigModel struct {
	Generated   string      `json:"generated"`
	Operations  []string    `json:"operations"`
	Schema      Schema      `json:"schema"`
	TestHandler TestHandler `json:"test_handler"`
}
