// Code generated by jsonschematogo. DO NOT EDIT.

package config

type GitHubDocs struct {
	Revision string `json:"revision"`
	Version  string `json:"version"`
}

type GitHubRepository struct {
	Host       *string `json:"host"`
	Path       string  `json:"path"`
	Repository string  `json:"repository"`
	Revision   string  `json:"revision"`
}

type Source struct {
	GithubDocs       *GitHubDocs       `json:"github_docs"`
	GithubRepository *GitHubRepository `json:"github_repository"`
	Url              *string           `json:"url"`
}

type Schema struct {
	Path   string  `json:"path"`
	Sha256 *string `json:"sha256"`
	Source *Source `json:"source"`
}

type TestHandler struct {
	Generated string `json:"generated"`
}

type Config struct {
	Generated   string       `json:"generated"`
	Operations  []string     `json:"operations"`
	Schema      Schema       `json:"schema"`
	TestHandler *TestHandler `json:"test_handler"`
}
