// Code generated by octoqlgen, DO NOT EDIT.

package test

import (
	"context"

	"github.com/willabides/octoql"
	"github.com/willabides/octoql/internal/testutil"
)

func __octoqlExecute[T interface{}](
	ctx context.Context,
	client *octoql.Client,
	payload octoql.Payload,
	newPartialDataError func(*T, error) error,
) (*T, error) {
	var response T
	hasData, err := client.Execute(ctx, payload, &response)
	if !hasData {
		return nil, err
	}
	if err != nil {
		return nil, newPartialDataError(&response, err)
	}
	return &response, nil
}

// anyResponse is returned by any on success.
type anyResponse struct {
	Viewer anyViewerUser `json:"viewer"`
}

// GetViewer returns anyResponse.Viewer, and is useful for accessing the field via an interface.
func (v *anyResponse) GetViewer() anyViewerUser { return v.Viewer }

// anyViewerUser includes the requested fields of the GraphQL type User.
type anyViewerUser struct {
	Id testutil.ID `json:"id"`
}

// GetId returns anyViewerUser.Id, and is useful for accessing the field via an interface.
func (v *anyViewerUser) GetId() testutil.ID { return v.Id }

// newResponse is returned by new on success.
type newResponse struct {
	Viewer newViewerUser `json:"viewer"`
}

// GetViewer returns newResponse.Viewer, and is useful for accessing the field via an interface.
func (v *newResponse) GetViewer() newViewerUser { return v.Viewer }

// newViewerUser includes the requested fields of the GraphQL type User.
type newViewerUser struct {
	Id testutil.ID `json:"id"`
}

// GetId returns newViewerUser.Id, and is useful for accessing the field via an interface.
func (v *newViewerUser) GetId() testutil.ID { return v.Id }

// The query executed by any.
const any_Operation = "\nquery any {\n\tviewer {\n\t\tid\n\t}\n}\n"

// anyPartialDataError contains partial data returned by any.
type anyPartialDataError struct {
	data *anyResponse
	err  error
}

func (e *anyPartialDataError) Error() string {
	if e == nil || e.err == nil {
		return "graphql response contains partial data"
	}
	return e.err.Error()
}

func (e *anyPartialDataError) Unwrap() error {
	if e == nil {
		return nil
	}
	return e.err
}

func (e *anyPartialDataError) PartialData() *anyResponse {
	if e == nil {
		return nil
	}
	return e.data
}

func any(
	client *octoql.Client,
) (*anyResponse, error) {
	return __octoqlExecute[anyResponse](
		context.Background(),
		client,
		octoql.Payload{
			OperationName: "any",
			Query:         any_Operation,
			Variables:     nil,
		},
		func(data *anyResponse, err error) error {
			return &anyPartialDataError{
				data: data,
				err:  err,
			}
		},
	)
}

// The query executed by new.
const new_Operation = "\nquery new {\n\tviewer {\n\t\tid\n\t}\n}\n"

// newPartialDataError contains partial data returned by new.
type newPartialDataError struct {
	data *newResponse
	err  error
}

func (e *newPartialDataError) Error() string {
	if e == nil || e.err == nil {
		return "graphql response contains partial data"
	}
	return e.err.Error()
}

func (e *newPartialDataError) Unwrap() error {
	if e == nil {
		return nil
	}
	return e.err
}

func (e *newPartialDataError) PartialData() *newResponse {
	if e == nil {
		return nil
	}
	return e.data
}

func new(
	client *octoql.Client,
) (*newResponse, error) {
	return __octoqlExecute[newResponse](
		context.Background(),
		client,
		octoql.Payload{
			OperationName: "new",
			Query:         new_Operation,
			Variables:     nil,
		},
		func(data *newResponse, err error) error {
			return &newPartialDataError{
				data: data,
				err:  err,
			}
		},
	)
}
