// Code generated by octoqlgen, DO NOT EDIT.

package test

import (
	"context"

	"github.com/willabides/octoql"
	"github.com/willabides/octoql/internal/testutil"
)

// anyResponse is returned by any on success.
type anyResponse struct {
	Viewer anyViewerUser `json:"viewer"`
}

// GetViewer returns anyResponse.Viewer, and is useful for accessing the field via an interface.
func (v *anyResponse) GetViewer() anyViewerUser { return v.Viewer }

// anyViewerUser includes the requested fields of the GraphQL type User.
type anyViewerUser struct {
	Id testutil.ID `json:"id"`
}

// GetId returns anyViewerUser.Id, and is useful for accessing the field via an interface.
func (v *anyViewerUser) GetId() testutil.ID { return v.Id }

// newResponse is returned by new on success.
type newResponse struct {
	Viewer newViewerUser `json:"viewer"`
}

// GetViewer returns newResponse.Viewer, and is useful for accessing the field via an interface.
func (v *newResponse) GetViewer() newViewerUser { return v.Viewer }

// newViewerUser includes the requested fields of the GraphQL type User.
type newViewerUser struct {
	Id testutil.ID `json:"id"`
}

// GetId returns newViewerUser.Id, and is useful for accessing the field via an interface.
func (v *newViewerUser) GetId() testutil.ID { return v.Id }

// The query executed by any.
const any_Operation = `
query any {
	viewer {
		id
	}
}
`

// anyPartialDataError contains partial data returned by any.
type anyPartialDataError struct {
	data *anyResponse
	err  error
}

func (err *anyPartialDataError) Error() string {
	if err == nil || err.err == nil {
		return "graphql response contains partial data"
	}
	return err.err.Error()
}

func (err *anyPartialDataError) Unwrap() error {
	if err == nil {
		return nil
	}
	return err.err
}

func (err *anyPartialDataError) PartialData() *anyResponse {
	if err == nil {
		return nil
	}
	return err.data
}

func any(
	client_ *octoql.Client,
) (*anyResponse, error) {
	var response_ anyResponse
	hasData_, err_ := client_.Execute(
		context.Background(),
		octoql.Payload{
			OperationName: "any",
			Query:         any_Operation,
			Variables:     nil,
		},
		&response_,
	)
	if !hasData_ {
		return nil, err_
	}
	if err_ != nil {
		return nil, &anyPartialDataError{
			data: &response_,
			err:  err_,
		}
	}
	return &response_, nil
}

// The query executed by new.
const new_Operation = `
query new {
	viewer {
		id
	}
}
`

// newPartialDataError contains partial data returned by new.
type newPartialDataError struct {
	data *newResponse
	err  error
}

func (err *newPartialDataError) Error() string {
	if err == nil || err.err == nil {
		return "graphql response contains partial data"
	}
	return err.err.Error()
}

func (err *newPartialDataError) Unwrap() error {
	if err == nil {
		return nil
	}
	return err.err
}

func (err *newPartialDataError) PartialData() *newResponse {
	if err == nil {
		return nil
	}
	return err.data
}

func new(
	client_ *octoql.Client,
) (*newResponse, error) {
	var response_ newResponse
	hasData_, err_ := client_.Execute(
		context.Background(),
		octoql.Payload{
			OperationName: "new",
			Query:         new_Operation,
			Variables:     nil,
		},
		&response_,
	)
	if !hasData_ {
		return nil, err_
	}
	if err_ != nil {
		return nil, &newPartialDataError{
			data: &response_,
			err:  err_,
		}
	}
	return &response_, nil
}
