// Code generated by octoqlgen, DO NOT EDIT.

package test

import (
	"context"

	"github.com/willabides/octoql"
	"github.com/willabides/octoql/internal/testutil"
)

type octoqlExecutor interface {
	Execute(context.Context, octoql.Payload, interface{}) (bool, error)
}

type FirstRepository string

// GitHubNamingResponse is returned by GitHubNaming on success.
type GitHubNamingResponse struct {
	Account         testutil.Account                      `json:"account"`
	First           *GitHubNamingResponseFirstRepository  `json:"first"`
	Second          *GitHubNamingResponseSecondRepository `json:"second"`
	Snake_case_type *GitHubNamingResponseSnake_case_type  `json:"snake_case_type"`
	Object          GitHubNamingResponseObjectObjectType  `json:"object"`
}

// GetAccount returns GitHubNamingResponse.Account, and is useful for accessing the field via an interface.
func (v *GitHubNamingResponse) GetAccount() testutil.Account { return v.Account }

// GetFirst returns GitHubNamingResponse.First, and is useful for accessing the field via an interface.
func (v *GitHubNamingResponse) GetFirst() *GitHubNamingResponseFirstRepository { return v.First }

// GetSecond returns GitHubNamingResponse.Second, and is useful for accessing the field via an interface.
func (v *GitHubNamingResponse) GetSecond() *GitHubNamingResponseSecondRepository { return v.Second }

// GetSnake_case_type returns GitHubNamingResponse.Snake_case_type, and is useful for accessing the field via an interface.
func (v *GitHubNamingResponse) GetSnake_case_type() *GitHubNamingResponseSnake_case_type {
	return v.Snake_case_type
}

// GetObject returns GitHubNamingResponse.Object, and is useful for accessing the field via an interface.
func (v *GitHubNamingResponse) GetObject() GitHubNamingResponseObjectObjectType { return v.Object }

// GitHubNamingResponseFirstRepository includes the requested fields of the GraphQL type Repository.
type GitHubNamingResponseFirstRepository struct {
	NameWithOwner FirstRepository `json:"nameWithOwner"`
}

// GetNameWithOwner returns GitHubNamingResponseFirstRepository.NameWithOwner, and is useful for accessing the field via an interface.
func (v *GitHubNamingResponseFirstRepository) GetNameWithOwner() FirstRepository {
	return v.NameWithOwner
}

// GitHubNamingResponseObjectObjectType includes the requested fields of the GraphQL type ObjectType.
type GitHubNamingResponseObjectObjectType struct {
	Snake_case_field *GitHubNamingResponseObjectObjectTypeSnake_case_fieldSnake_case_type `json:"snake_case_field"`
}

// GetSnake_case_field returns GitHubNamingResponseObjectObjectType.Snake_case_field, and is useful for accessing the field via an interface.
func (v *GitHubNamingResponseObjectObjectType) GetSnake_case_field() *GitHubNamingResponseObjectObjectTypeSnake_case_fieldSnake_case_type {
	return v.Snake_case_field
}

// GitHubNamingResponseObjectObjectTypeSnake_case_fieldSnake_case_type includes the requested fields of the GraphQL type snake_case_type.
type GitHubNamingResponseObjectObjectTypeSnake_case_fieldSnake_case_type struct {
	Id testutil.ID `json:"id"`
}

// GetId returns GitHubNamingResponseObjectObjectTypeSnake_case_fieldSnake_case_type.Id, and is useful for accessing the field via an interface.
func (v *GitHubNamingResponseObjectObjectTypeSnake_case_fieldSnake_case_type) GetId() testutil.ID {
	return v.Id
}

// GitHubNamingResponseSecondRepository includes the requested fields of the GraphQL type Repository.
type GitHubNamingResponseSecondRepository struct {
	NameWithOwner SecondRepository `json:"nameWithOwner"`
}

// GetNameWithOwner returns GitHubNamingResponseSecondRepository.NameWithOwner, and is useful for accessing the field via an interface.
func (v *GitHubNamingResponseSecondRepository) GetNameWithOwner() SecondRepository {
	return v.NameWithOwner
}

// GitHubNamingResponseSnake_case_type includes the requested fields of the GraphQL type snake_case_type.
type GitHubNamingResponseSnake_case_type struct {
	Id   testutil.ID `json:"id"`
	Name *string     `json:"name"`
}

// GetId returns GitHubNamingResponseSnake_case_type.Id, and is useful for accessing the field via an interface.
func (v *GitHubNamingResponseSnake_case_type) GetId() testutil.ID { return v.Id }

// GetName returns GitHubNamingResponseSnake_case_type.Name, and is useful for accessing the field via an interface.
func (v *GitHubNamingResponseSnake_case_type) GetName() *string { return v.Name }

type SecondRepository string

// anyResponse is returned by any on success.
type anyResponse struct {
	Viewer anyViewerUser `json:"viewer"`
}

// GetViewer returns anyResponse.Viewer, and is useful for accessing the field via an interface.
func (v *anyResponse) GetViewer() anyViewerUser { return v.Viewer }

// anyViewerUser includes the requested fields of the GraphQL type User.
type anyViewerUser struct {
	Id testutil.ID `json:"id"`
}

// GetId returns anyViewerUser.Id, and is useful for accessing the field via an interface.
func (v *anyViewerUser) GetId() testutil.ID { return v.Id }

// newResponse is returned by new on success.
type newResponse struct {
	Viewer newViewerUser `json:"viewer"`
}

// GetViewer returns newResponse.Viewer, and is useful for accessing the field via an interface.
func (v *newResponse) GetViewer() newViewerUser { return v.Viewer }

// newViewerUser includes the requested fields of the GraphQL type User.
type newViewerUser struct {
	Id testutil.ID `json:"id"`
}

// GetId returns newViewerUser.Id, and is useful for accessing the field via an interface.
func (v *newViewerUser) GetId() testutil.ID { return v.Id }

// The query executed by GitHubNaming.
const GitHubNaming_Operation = "\nquery GitHubNaming {\n\taccount {\n\t\tid\n\t\tlogin\n\t}\n\tfirst: repository(owner: \"octo\", name: \"one\") {\n\t\tnameWithOwner\n\t}\n\tsecond: repository(owner: \"octo\", name: \"two\") {\n\t\tnameWithOwner\n\t}\n\tsnake_case_type {\n\t\tid\n\t\tname\n\t}\n\tobject {\n\t\tsnake_case_field {\n\t\t\tid\n\t\t}\n\t}\n}\n"

// GitHubNamingPartialDataError contains partial data returned by GitHubNaming.
type GitHubNamingPartialDataError struct {
	data *GitHubNamingResponse
	err  error
}

func (e *GitHubNamingPartialDataError) Error() string {
	if e == nil || e.err == nil {
		return "graphql response contains partial data"
	}
	return e.err.Error()
}

func (e *GitHubNamingPartialDataError) Unwrap() error {
	if e == nil {
		return nil
	}
	return e.err
}

func (e *GitHubNamingPartialDataError) PartialData() *GitHubNamingResponse {
	if e == nil {
		return nil
	}
	return e.data
}

func GitHubNaming(
	client octoqlExecutor,
) (*GitHubNamingResponse, error) {
	var response GitHubNamingResponse
	hasData, err := client.Execute(
		context.Background(),
		octoql.Payload{
			OperationName: "GitHubNaming",
			Query:         GitHubNaming_Operation,
			Variables:     nil,
		},
		&response,
	)
	if !hasData {
		return nil, err
	}
	if err != nil {
		return nil, &GitHubNamingPartialDataError{
			data: &response,
			err:  err,
		}
	}
	return &response, nil
}

// The query executed by any.
const any_Operation = "\nquery any {\n\tviewer {\n\t\tid\n\t}\n}\n"

// anyPartialDataError contains partial data returned by any.
type anyPartialDataError struct {
	data *anyResponse
	err  error
}

func (e *anyPartialDataError) Error() string {
	if e == nil || e.err == nil {
		return "graphql response contains partial data"
	}
	return e.err.Error()
}

func (e *anyPartialDataError) Unwrap() error {
	if e == nil {
		return nil
	}
	return e.err
}

func (e *anyPartialDataError) PartialData() *anyResponse {
	if e == nil {
		return nil
	}
	return e.data
}

func any(
	client octoqlExecutor,
) (*anyResponse, error) {
	var response anyResponse
	hasData, err := client.Execute(
		context.Background(),
		octoql.Payload{
			OperationName: "any",
			Query:         any_Operation,
			Variables:     nil,
		},
		&response,
	)
	if !hasData {
		return nil, err
	}
	if err != nil {
		return nil, &anyPartialDataError{
			data: &response,
			err:  err,
		}
	}
	return &response, nil
}

// The query executed by new.
const new_Operation = "\nquery new {\n\tviewer {\n\t\tid\n\t}\n}\n"

// newPartialDataError contains partial data returned by new.
type newPartialDataError struct {
	data *newResponse
	err  error
}

func (e *newPartialDataError) Error() string {
	if e == nil || e.err == nil {
		return "graphql response contains partial data"
	}
	return e.err.Error()
}

func (e *newPartialDataError) Unwrap() error {
	if e == nil {
		return nil
	}
	return e.err
}

func (e *newPartialDataError) PartialData() *newResponse {
	if e == nil {
		return nil
	}
	return e.data
}

func new(
	client octoqlExecutor,
) (*newResponse, error) {
	var response newResponse
	hasData, err := client.Execute(
		context.Background(),
		octoql.Payload{
			OperationName: "new",
			Query:         new_Operation,
			Variables:     nil,
		},
		&response,
	)
	if !hasData {
		return nil, err
	}
	if err != nil {
		return nil, &newPartialDataError{
			data: &response,
			err:  err,
		}
	}
	return &response, nil
}
