// Code generated by octoqlgen, DO NOT EDIT.

package test

import (
	"context"

	"github.com/willabides/octoql"
	"github.com/willabides/octoql/internal/testutil"
)

// anyResponse is returned by any on success.
type anyResponse struct {
	Viewer anyViewerUser `json:"viewer"`
}

// GetViewer returns anyResponse.Viewer, and is useful for accessing the field via an interface.
func (v *anyResponse) GetViewer() anyViewerUser { return v.Viewer }

// anyViewerUser includes the requested fields of the GraphQL type User.
type anyViewerUser struct {
	Id testutil.ID `json:"id"`
}

// GetId returns anyViewerUser.Id, and is useful for accessing the field via an interface.
func (v *anyViewerUser) GetId() testutil.ID { return v.Id }

// newResponse is returned by new on success.
type newResponse struct {
	Viewer newViewerUser `json:"viewer"`
}

// GetViewer returns newResponse.Viewer, and is useful for accessing the field via an interface.
func (v *newResponse) GetViewer() newViewerUser { return v.Viewer }

// newViewerUser includes the requested fields of the GraphQL type User.
type newViewerUser struct {
	Id testutil.ID `json:"id"`
}

// GetId returns newViewerUser.Id, and is useful for accessing the field via an interface.
func (v *newViewerUser) GetId() testutil.ID { return v.Id }

type __octoqlPartialDataError[T interface{}] struct {
	data *T
	err  error
}

func (err *__octoqlPartialDataError[T]) Error() string {
	if err == nil || err.err == nil {
		return "graphql response contains partial data"
	}
	return err.err.Error()
}

func (err *__octoqlPartialDataError[T]) Unwrap() error {
	if err == nil {
		return nil
	}
	return err.err
}

func (err *__octoqlPartialDataError[T]) PartialData() *T {
	if err == nil {
		return nil
	}
	return err.data
}

func __octoqlDo[T interface{}](
	ctx context.Context,
	client *octoql.Client,
	payload octoql.Payload,
	newPartialDataError func(*T, error) error,
) (*T, error) {
	var data T
	response := &data
	hasData, err := client.Execute(ctx, payload, response)
	if !hasData {
		return nil, err
	}
	if err != nil {
		return nil, newPartialDataError(response, err)
	}
	return response, nil
}

// The query executed by any.
const any_Operation = `
query any {
	viewer {
		id
	}
}
`

// anyPartialDataError contains partial data returned by any.
type anyPartialDataError struct {
	__octoqlPartialDataError[anyResponse]
}

func any(
	client_ *octoql.Client,
) (*anyResponse, error) {
	return __octoqlDo[anyResponse](
		context.Background(),
		client_,
		octoql.Payload{
			OperationName: "any",
			Query:         any_Operation,
			Variables:     nil,
		},
		func(data *anyResponse, err error) error {
			return &anyPartialDataError{
				__octoqlPartialDataError: __octoqlPartialDataError[anyResponse]{
					data: data,
					err:  err,
				},
			}
		},
	)
}

// The query executed by new.
const new_Operation = `
query new {
	viewer {
		id
	}
}
`

// newPartialDataError contains partial data returned by new.
type newPartialDataError struct {
	__octoqlPartialDataError[newResponse]
}

func new(
	client_ *octoql.Client,
) (*newResponse, error) {
	return __octoqlDo[newResponse](
		context.Background(),
		client_,
		octoql.Payload{
			OperationName: "new",
			Query:         new_Operation,
			Variables:     nil,
		},
		func(data *newResponse, err error) error {
			return &newPartialDataError{
				__octoqlPartialDataError: __octoqlPartialDataError[newResponse]{
					data: data,
					err:  err,
				},
			}
		},
	)
}
