// Code generated by octoqlgen. DO NOT EDIT.

package githubapitest

import (
	"bytes"
	"encoding/json"
	"errors"
	"fmt"
	"io"
	"net/http"
	"strconv"
	"sync"
	"testing"
	"time"

	"github.com/willabides/octoql"
	githubapi "github.com/willabides/octoql/internal/handlertest/client"
)

type CreateRepositoryCreateRepositoryCreateRepositoryPayload = githubapi.CreateRepositoryCreateRepositoryCreateRepositoryPayload

type CreateRepositoryCreateRepositoryCreateRepositoryPayloadRepository = githubapi.CreateRepositoryCreateRepositoryCreateRepositoryPayloadRepository

type CreateRepositoryCreateRepositoryCreateRepositoryPayloadRepositoryIssuesIssueConnection = githubapi.CreateRepositoryCreateRepositoryCreateRepositoryPayloadRepositoryIssuesIssueConnection

type CreateRepositoryCreateRepositoryCreateRepositoryPayloadRepositoryIssuesIssueConnectionPageInfo = githubapi.CreateRepositoryCreateRepositoryCreateRepositoryPayloadRepositoryIssuesIssueConnectionPageInfo

type CreateRepositoryInput = githubapi.CreateRepositoryInput

type CreateRepositoryResponse = githubapi.CreateRepositoryResponse

type CreateRepositoryVariables = githubapi.CreateRepositoryVariables

type EchoAnyResponse = githubapi.EchoAnyResponse

type EchoAnyVariables = githubapi.EchoAnyVariables

type EchoAtResponse = githubapi.EchoAtResponse

type EchoAtVariables = githubapi.EchoAtVariables

type EchoPropertyResponse = githubapi.EchoPropertyResponse

type EchoPropertyVariables = githubapi.EchoPropertyVariables

type GetNodeNode = githubapi.GetNodeNode

type GetNodeNodeIssue = githubapi.GetNodeNodeIssue

type GetNodeNodeOctoqlOther = githubapi.GetNodeNodeOctoqlOther

type GetNodeNodeRepository = githubapi.GetNodeNodeRepository

type GetNodeResponse = githubapi.GetNodeResponse

type GetNodeVariables = githubapi.GetNodeVariables

type GetRepositoryRepository = githubapi.GetRepositoryRepository

type GetRepositoryRepositoryIssuesIssueConnection = githubapi.GetRepositoryRepositoryIssuesIssueConnection

type GetRepositoryRepositoryIssuesIssueConnectionNodesIssue = githubapi.GetRepositoryRepositoryIssuesIssueConnectionNodesIssue

type GetRepositoryRepositoryIssuesIssueConnectionPageInfo = githubapi.GetRepositoryRepositoryIssuesIssueConnectionPageInfo

type GetRepositoryResponse = githubapi.GetRepositoryResponse

type GetRepositoryVariables = githubapi.GetRepositoryVariables

type RepositoryVisibility = githubapi.RepositoryVisibility

const (
	RepositoryVisibilityPrivate = githubapi.RepositoryVisibilityPrivate
	RepositoryVisibilityPublic  = githubapi.RepositoryVisibilityPublic
)

type SearchResponse = githubapi.SearchResponse

type SearchSearchIssue = githubapi.SearchSearchIssue

type SearchSearchRepository = githubapi.SearchSearchRepository

type SearchSearchSearchResultItem = githubapi.SearchSearchSearchResultItem

type SearchSearchSearchResultItemOctoqlOther = githubapi.SearchSearchSearchResultItemOctoqlOther

type SearchVariables = githubapi.SearchVariables

type ViewerResponse = githubapi.ViewerResponse

type ViewerVariables = githubapi.ViewerVariables

type ViewerViewerUser = githubapi.ViewerViewerUser

type testTB interface {
	Cleanup(func())
	Errorf(string, ...any)
}

type graphqlRequest struct {
	OperationName string          `json:"operationName"`
	Variables     json.RawMessage `json:"variables"`
}

type operationResult[V any] func(V, http.ResponseWriter) error

type expectationOptions struct {
	remaining int
	atLeast   bool
}

type ExpectOption func(*expectationOptions)

func Times(count int) ExpectOption {
	return func(options *expectationOptions) {
		options.remaining = count
		options.atLeast = false
	}
}

func MinTimes(count int) ExpectOption {
	return func(options *expectationOptions) {
		options.remaining = count
		options.atLeast = true
	}
}

type expectation[V any] struct {
	variables    V
	variablesKey string
	result       operationResult[V]
	remaining    int
	atLeast      bool
}

type expectationSet[V any] struct {
	mu           sync.Mutex
	tb           testTB
	operation    string
	expectations []*expectation[V]
	fallback     *expectation[V]
}

func (s *expectationSet[V]) expect(
	variables V,
	options ...ExpectOption,
) *expectation[V] {
	config := expectationOptions{remaining: 1}
	for _, option := range options {
		if option != nil {
			option(&config)
		}
	}
	if config.remaining < 0 {
		s.tb.Errorf(
			"%s expectation count must not be negative: %d",
			s.operation,
			config.remaining,
		)
		config.remaining = 0
	}
	key, err := variableKey(variables)
	if err != nil {
		s.tb.Errorf("%s expectation variables: %v", s.operation, err)
		config.remaining = 0
	}

	expected := &expectation[V]{
		variables:    variables,
		variablesKey: key,
		remaining:    config.remaining,
		atLeast:      config.atLeast,
	}
	s.mu.Lock()
	s.expectations = append(s.expectations, expected)
	s.mu.Unlock()
	return expected
}

func (s *expectationSet[V]) expectDefault() *expectation[V] {
	expected := &expectation[V]{
		atLeast: true,
	}
	s.mu.Lock()
	s.fallback = expected
	s.mu.Unlock()
	return expected
}

func (s *expectationSet[V]) setResult(
	expected *expectation[V],
	result operationResult[V],
) {
	s.mu.Lock()
	expected.result = result
	s.mu.Unlock()
}

func (s *expectationSet[V]) match(
	variables V,
	rawVariables []byte,
) (operationResult[V], error) {
	key, err := variableKeyJSON(rawVariables)
	if err != nil {
		return nil, fmt.Errorf("%s variables: %w", s.operation, err)
	}

	s.mu.Lock()
	defer s.mu.Unlock()

	for _, expected := range s.expectations {
		if expected.remaining == 0 && !expected.atLeast {
			continue
		}
		if expected.variablesKey != key {
			continue
		}
		if expected.remaining > 0 {
			expected.remaining--
		}
		if expected.result == nil {
			return nil, fmt.Errorf(
				"%s expectation for variables %+v has no response",
				s.operation,
				variables,
			)
		}
		return expected.result, nil
	}

	if s.fallback != nil {
		if s.fallback.result == nil {
			return nil, fmt.Errorf(
				"%s default expectation has no response",
				s.operation,
			)
		}
		return s.fallback.result, nil
	}

	return nil, fmt.Errorf(
		"no expectation found for %s variables %+v",
		s.operation,
		variables,
	)
}

func (s *expectationSet[V]) reset(variables ...V) {
	s.mu.Lock()
	defer s.mu.Unlock()

	if len(variables) == 0 {
		for _, expected := range s.expectations {
			expected.remaining = 0
		}
		s.expectations = []*expectation[V]{}
		s.fallback = nil
		return
	}

	keys := make([]string, 0, len(variables))
	for _, variablesToReset := range variables {
		key, err := variableKey(variablesToReset)
		if err != nil {
			s.tb.Errorf("%s reset variables: %v", s.operation, err)
			continue
		}
		keys = append(keys, key)
	}

	retained := make([]*expectation[V], 0, len(s.expectations))
	for _, expected := range s.expectations {
		shouldReset := false
		for _, key := range keys {
			if expected.variablesKey == key {
				shouldReset = true
				break
			}
		}

		if shouldReset {
			expected.remaining = 0
			continue
		}
		retained = append(retained, expected)
	}
	s.expectations = retained
}

func variableKey[V any](variables V) (string, error) {
	encoded, err := json.Marshal(variables)
	if err != nil {
		return "", fmt.Errorf("encoding variables: %w", err)
	}
	return variableKeyJSON(encoded)
}

func variableKeyJSON(encoded []byte) (string, error) {
	decoder := json.NewDecoder(bytes.NewReader(encoded))
	decoder.UseNumber()
	var value any
	err := decoder.Decode(&value)
	if err != nil {
		return "", fmt.Errorf("decoding variables: %w", err)
	}
	normalized, err := json.Marshal(value)
	if err != nil {
		return "", fmt.Errorf("normalizing variables: %w", err)
	}
	return string(normalized), nil
}

func decodeVariables(encoded []byte, destination any) error {
	decoder := json.NewDecoder(bytes.NewReader(encoded))
	decoder.UseNumber()
	err := decoder.Decode(destination)
	if err != nil {
		return fmt.Errorf("decoding variables: %w", err)
	}
	return nil
}

func (s *expectationSet[V]) verify() {
	s.mu.Lock()
	defer s.mu.Unlock()

	for _, expected := range s.expectations {
		if expected.remaining > 0 {
			s.tb.Errorf(
				"unmet %s expectation for variables %+v: %d call(s) remaining",
				s.operation,
				expected.variables,
				expected.remaining,
			)
		}
	}
}

type responseOptions struct {
	status int
	header http.Header
	err    error
}

type ResponseOption func(*responseOptions)

func WithStatus(status int) ResponseOption {
	return func(options *responseOptions) {
		if status < 100 || status > 999 {
			options.err = fmt.Errorf("invalid http status %d", status)
			return
		}
		options.status = status
	}
}

func WithHeader(name string, values ...string) ResponseOption {
	canonicalName := http.CanonicalHeaderKey(name)
	clonedValues := append([]string{}, values...)
	return func(options *responseOptions) {
		options.header[canonicalName] = append([]string{}, clonedValues...)
	}
}

func WithHeaders(header http.Header) ResponseOption {
	clonedHeader := http.Header{}
	for name, values := range header {
		canonicalName := http.CanonicalHeaderKey(name)
		clonedHeader[canonicalName] = append(clonedHeader[canonicalName], values...)
	}
	return func(options *responseOptions) {
		for name, values := range clonedHeader {
			options.header[name] = append([]string{}, values...)
		}
	}
}

func WithPrimaryRateLimit(rateLimit octoql.RateLimit) ResponseOption {
	return func(options *responseOptions) {
		hasNegativeValue := rateLimit.Limit < 0 ||
			rateLimit.Remaining < 0 ||
			rateLimit.Used < 0
		if hasNegativeValue {
			options.err = fmt.Errorf("primary rate limit values must not be negative")
			return
		}

		options.header.Set("X-RateLimit-Limit", strconv.Itoa(rateLimit.Limit))
		options.header.Set("X-RateLimit-Remaining", strconv.Itoa(rateLimit.Remaining))
		options.header.Set("X-RateLimit-Used", strconv.Itoa(rateLimit.Used))
		if !rateLimit.Reset.IsZero() {
			options.header.Set(
				"X-RateLimit-Reset",
				strconv.FormatInt(rateLimit.Reset.Unix(), 10),
			)
		}
		if rateLimit.Resource != "" {
			options.header.Set("X-RateLimit-Resource", rateLimit.Resource)
		}
	}
}

func WithSecondaryRateLimit(retryAfter time.Duration) ResponseOption {
	return func(options *responseOptions) {
		if retryAfter < 0 {
			options.err = fmt.Errorf("secondary rate limit retry-after must not be negative")
			return
		}

		seconds := retryAfter / time.Second
		if retryAfter%time.Second != 0 {
			seconds++
		}
		options.header.Set(
			"Retry-After",
			strconv.FormatInt(int64(seconds), 10),
		)
	}
}

func buildResponseOptions(options ...ResponseOption) responseOptions {
	config := responseOptions{
		status: http.StatusOK,
		header: http.Header{},
	}
	for _, option := range options {
		if option != nil {
			option(&config)
		}
	}
	return config
}

func combineResponseOptions(
	base []ResponseOption,
	additional []ResponseOption,
) []ResponseOption {
	combined := make([]ResponseOption, 0, len(base)+len(additional))
	combined = append(combined, base...)
	combined = append(combined, additional...)
	return combined
}

func writeGraphQLResponse(
	writer http.ResponseWriter,
	data any,
	graphqlErrors []octoql.Error,
	options responseOptions,
) error {
	if options.err != nil {
		return options.err
	}

	for name, values := range options.header {
		writer.Header()[name] = append([]string{}, values...)
	}
	writer.Header().Set("Content-Type", "application/json")

	payload := map[string]any{}
	if data != nil {
		payload["data"] = data
	}
	if graphqlErrors != nil {
		payload["errors"] = graphqlErrors
	}
	writer.WriteHeader(options.status)
	err := json.NewEncoder(writer).Encode(payload)
	if err != nil {
		return fmt.Errorf("encoding graphql response: %w", err)
	}
	return nil
}

func writeRequestError(
	writer http.ResponseWriter,
	status int,
	message string,
) error {
	return writeGraphQLResponse(
		writer,
		nil,
		[]octoql.Error{{Message: message}},
		buildResponseOptions(WithStatus(status)),
	)
}

type TestHandler struct {
	tb         testTB
	operation0 expectationSet[CreateRepositoryVariables]
	operation1 expectationSet[EchoAnyVariables]
	operation2 expectationSet[EchoAtVariables]
	operation3 expectationSet[EchoPropertyVariables]
	operation4 expectationSet[GetNodeVariables]
	operation5 expectationSet[GetRepositoryVariables]
	operation6 expectationSet[SearchVariables]
	operation7 expectationSet[struct{}]
}

var _ http.Handler = (*TestHandler)(nil)

func NewTestHandler(testingTB testing.TB) *TestHandler {
	return newTestHandler(testingTB)
}

func newTestHandler(testingTB testTB) *TestHandler {
	h := &TestHandler{tb: testingTB}
	h.operation0 = expectationSet[CreateRepositoryVariables]{
		tb:           testingTB,
		operation:    "CreateRepository",
		expectations: []*expectation[CreateRepositoryVariables]{},
	}
	h.operation1 = expectationSet[EchoAnyVariables]{
		tb:           testingTB,
		operation:    "EchoAny",
		expectations: []*expectation[EchoAnyVariables]{},
	}
	h.operation2 = expectationSet[EchoAtVariables]{
		tb:           testingTB,
		operation:    "EchoAt",
		expectations: []*expectation[EchoAtVariables]{},
	}
	h.operation3 = expectationSet[EchoPropertyVariables]{
		tb:           testingTB,
		operation:    "EchoProperty",
		expectations: []*expectation[EchoPropertyVariables]{},
	}
	h.operation4 = expectationSet[GetNodeVariables]{
		tb:           testingTB,
		operation:    "GetNode",
		expectations: []*expectation[GetNodeVariables]{},
	}
	h.operation5 = expectationSet[GetRepositoryVariables]{
		tb:           testingTB,
		operation:    "GetRepository",
		expectations: []*expectation[GetRepositoryVariables]{},
	}
	h.operation6 = expectationSet[SearchVariables]{
		tb:           testingTB,
		operation:    "Search",
		expectations: []*expectation[SearchVariables]{},
	}
	h.operation7 = expectationSet[struct{}]{
		tb:           testingTB,
		operation:    "Viewer",
		expectations: []*expectation[struct{}]{},
	}
	testingTB.Cleanup(h.verify)
	return h
}

func (h *TestHandler) verify() {
	h.operation0.verify()
	h.operation1.verify()
	h.operation2.verify()
	h.operation3.verify()
	h.operation4.verify()
	h.operation5.verify()
	h.operation6.verify()
	h.operation7.verify()
}

func (h *TestHandler) Reset() {
	h.operation0.reset()
	h.operation1.reset()
	h.operation2.reset()
	h.operation3.reset()
	h.operation4.reset()
	h.operation5.reset()
	h.operation6.reset()
	h.operation7.reset()
}

func (h *TestHandler) ServeHTTP(
	writer http.ResponseWriter,
	request *http.Request,
) {
	if request.Method != http.MethodPost {
		writer.Header().Set("Allow", http.MethodPost)
		err := writeRequestError(
			writer,
			http.StatusMethodNotAllowed,
			"graphql requests must use POST",
		)
		if err != nil {
			h.tb.Errorf("writing method error response: %v", err)
		}
		return
	}

	decoder := json.NewDecoder(
		http.MaxBytesReader(writer, request.Body, 8<<20),
	)
	var graphqlRequest graphqlRequest
	err := decoder.Decode(&graphqlRequest)
	if err != nil {
		writeErr := writeRequestError(
			writer,
			http.StatusBadRequest,
			"decoding graphql request: "+err.Error(),
		)
		if writeErr != nil {
			h.tb.Errorf("writing decode error response: %v", writeErr)
		}
		return
	}

	var extra any
	err = decoder.Decode(&extra)
	if !errors.Is(err, io.EOF) {
		if err == nil {
			err = fmt.Errorf("multiple json values")
		}
		writeErr := writeRequestError(
			writer,
			http.StatusBadRequest,
			"decoding graphql request: "+err.Error(),
		)
		if writeErr != nil {
			h.tb.Errorf("writing trailing data error response: %v", writeErr)
		}
		return
	}

	if graphqlRequest.OperationName == "" {
		err = writeRequestError(
			writer,
			http.StatusBadRequest,
			"graphql request is missing operationName",
		)
		if err != nil {
			h.tb.Errorf("writing missing operation error response: %v", err)
		}
		return
	}
	if len(graphqlRequest.Variables) == 0 {
		graphqlRequest.Variables = json.RawMessage("{}")
	}

	switch graphqlRequest.OperationName {
	case "CreateRepository":
		var variables CreateRepositoryVariables
		err = decodeVariables(graphqlRequest.Variables, &variables)
		if err != nil {
			h.tb.Errorf("decoding CreateRepository variables: %v", err)
			writeErr := writeRequestError(
				writer,
				http.StatusOK,
				"decoding CreateRepository variables: "+err.Error(),
			)
			if writeErr != nil {
				h.tb.Errorf("writing CreateRepository variable error response: %v", writeErr)
			}
			return
		}

		result, matchErr := h.operation0.match(
			variables,
			graphqlRequest.Variables,
		)
		if matchErr != nil {
			h.tb.Errorf("%v", matchErr)
			writeErr := writeRequestError(
				writer,
				http.StatusOK,
				matchErr.Error(),
			)
			if writeErr != nil {
				h.tb.Errorf("writing CreateRepository expectation error response: %v", writeErr)
			}
			return
		}
		err = result(variables, writer)
		if err != nil {
			h.tb.Errorf("serving CreateRepository response: %v", err)
		}
	case "EchoAny":
		var variables EchoAnyVariables
		err = decodeVariables(graphqlRequest.Variables, &variables)
		if err != nil {
			h.tb.Errorf("decoding EchoAny variables: %v", err)
			writeErr := writeRequestError(
				writer,
				http.StatusOK,
				"decoding EchoAny variables: "+err.Error(),
			)
			if writeErr != nil {
				h.tb.Errorf("writing EchoAny variable error response: %v", writeErr)
			}
			return
		}

		result, matchErr := h.operation1.match(
			variables,
			graphqlRequest.Variables,
		)
		if matchErr != nil {
			h.tb.Errorf("%v", matchErr)
			writeErr := writeRequestError(
				writer,
				http.StatusOK,
				matchErr.Error(),
			)
			if writeErr != nil {
				h.tb.Errorf("writing EchoAny expectation error response: %v", writeErr)
			}
			return
		}
		err = result(variables, writer)
		if err != nil {
			h.tb.Errorf("serving EchoAny response: %v", err)
		}
	case "EchoAt":
		var variables EchoAtVariables
		err = decodeVariables(graphqlRequest.Variables, &variables)
		if err != nil {
			h.tb.Errorf("decoding EchoAt variables: %v", err)
			writeErr := writeRequestError(
				writer,
				http.StatusOK,
				"decoding EchoAt variables: "+err.Error(),
			)
			if writeErr != nil {
				h.tb.Errorf("writing EchoAt variable error response: %v", writeErr)
			}
			return
		}

		result, matchErr := h.operation2.match(
			variables,
			graphqlRequest.Variables,
		)
		if matchErr != nil {
			h.tb.Errorf("%v", matchErr)
			writeErr := writeRequestError(
				writer,
				http.StatusOK,
				matchErr.Error(),
			)
			if writeErr != nil {
				h.tb.Errorf("writing EchoAt expectation error response: %v", writeErr)
			}
			return
		}
		err = result(variables, writer)
		if err != nil {
			h.tb.Errorf("serving EchoAt response: %v", err)
		}
	case "EchoProperty":
		var variables EchoPropertyVariables
		err = decodeVariables(graphqlRequest.Variables, &variables)
		if err != nil {
			h.tb.Errorf("decoding EchoProperty variables: %v", err)
			writeErr := writeRequestError(
				writer,
				http.StatusOK,
				"decoding EchoProperty variables: "+err.Error(),
			)
			if writeErr != nil {
				h.tb.Errorf("writing EchoProperty variable error response: %v", writeErr)
			}
			return
		}

		result, matchErr := h.operation3.match(
			variables,
			graphqlRequest.Variables,
		)
		if matchErr != nil {
			h.tb.Errorf("%v", matchErr)
			writeErr := writeRequestError(
				writer,
				http.StatusOK,
				matchErr.Error(),
			)
			if writeErr != nil {
				h.tb.Errorf("writing EchoProperty expectation error response: %v", writeErr)
			}
			return
		}
		err = result(variables, writer)
		if err != nil {
			h.tb.Errorf("serving EchoProperty response: %v", err)
		}
	case "GetNode":
		var variables GetNodeVariables
		err = decodeVariables(graphqlRequest.Variables, &variables)
		if err != nil {
			h.tb.Errorf("decoding GetNode variables: %v", err)
			writeErr := writeRequestError(
				writer,
				http.StatusOK,
				"decoding GetNode variables: "+err.Error(),
			)
			if writeErr != nil {
				h.tb.Errorf("writing GetNode variable error response: %v", writeErr)
			}
			return
		}

		result, matchErr := h.operation4.match(
			variables,
			graphqlRequest.Variables,
		)
		if matchErr != nil {
			h.tb.Errorf("%v", matchErr)
			writeErr := writeRequestError(
				writer,
				http.StatusOK,
				matchErr.Error(),
			)
			if writeErr != nil {
				h.tb.Errorf("writing GetNode expectation error response: %v", writeErr)
			}
			return
		}
		err = result(variables, writer)
		if err != nil {
			h.tb.Errorf("serving GetNode response: %v", err)
		}
	case "GetRepository":
		var variables GetRepositoryVariables
		err = decodeVariables(graphqlRequest.Variables, &variables)
		if err != nil {
			h.tb.Errorf("decoding GetRepository variables: %v", err)
			writeErr := writeRequestError(
				writer,
				http.StatusOK,
				"decoding GetRepository variables: "+err.Error(),
			)
			if writeErr != nil {
				h.tb.Errorf("writing GetRepository variable error response: %v", writeErr)
			}
			return
		}

		result, matchErr := h.operation5.match(
			variables,
			graphqlRequest.Variables,
		)
		if matchErr != nil {
			h.tb.Errorf("%v", matchErr)
			writeErr := writeRequestError(
				writer,
				http.StatusOK,
				matchErr.Error(),
			)
			if writeErr != nil {
				h.tb.Errorf("writing GetRepository expectation error response: %v", writeErr)
			}
			return
		}
		err = result(variables, writer)
		if err != nil {
			h.tb.Errorf("serving GetRepository response: %v", err)
		}
	case "Search":
		var variables SearchVariables
		err = decodeVariables(graphqlRequest.Variables, &variables)
		if err != nil {
			h.tb.Errorf("decoding Search variables: %v", err)
			writeErr := writeRequestError(
				writer,
				http.StatusOK,
				"decoding Search variables: "+err.Error(),
			)
			if writeErr != nil {
				h.tb.Errorf("writing Search variable error response: %v", writeErr)
			}
			return
		}

		result, matchErr := h.operation6.match(
			variables,
			graphqlRequest.Variables,
		)
		if matchErr != nil {
			h.tb.Errorf("%v", matchErr)
			writeErr := writeRequestError(
				writer,
				http.StatusOK,
				matchErr.Error(),
			)
			if writeErr != nil {
				h.tb.Errorf("writing Search expectation error response: %v", writeErr)
			}
			return
		}
		err = result(variables, writer)
		if err != nil {
			h.tb.Errorf("serving Search response: %v", err)
		}
	case "Viewer":
		var variables struct{}
		err = decodeVariables(graphqlRequest.Variables, &variables)
		if err != nil {
			h.tb.Errorf("decoding Viewer variables: %v", err)
			writeErr := writeRequestError(
				writer,
				http.StatusOK,
				"decoding Viewer variables: "+err.Error(),
			)
			if writeErr != nil {
				h.tb.Errorf("writing Viewer variable error response: %v", writeErr)
			}
			return
		}

		result, matchErr := h.operation7.match(
			variables,
			graphqlRequest.Variables,
		)
		if matchErr != nil {
			h.tb.Errorf("%v", matchErr)
			writeErr := writeRequestError(
				writer,
				http.StatusOK,
				matchErr.Error(),
			)
			if writeErr != nil {
				h.tb.Errorf("writing Viewer expectation error response: %v", writeErr)
			}
			return
		}
		err = result(variables, writer)
		if err != nil {
			h.tb.Errorf("serving Viewer response: %v", err)
		}
	default:
		err = writeRequestError(
			writer,
			http.StatusOK,
			"unknown operation: "+graphqlRequest.OperationName,
		)
		if err != nil {
			h.tb.Errorf("writing unknown operation response: %v", err)
		}
	}
}

type CreateRepositoryExpectation struct {
	set      *expectationSet[CreateRepositoryVariables]
	expected *expectation[CreateRepositoryVariables]
	options  []ResponseOption
}

func (h *TestHandler) ExpectCreateRepository(
	variables CreateRepositoryVariables,
	options ...ExpectOption,
) *CreateRepositoryExpectation {
	return &CreateRepositoryExpectation{
		set: &h.operation0,
		expected: h.operation0.expect(
			variables,
			options...,
		),
		options: []ResponseOption{},
	}
}

func (h *TestHandler) DefaultCreateRepository() *CreateRepositoryExpectation {
	return &CreateRepositoryExpectation{
		set:      &h.operation0,
		expected: h.operation0.expectDefault(),
		options:  []ResponseOption{},
	}
}

func (h *TestHandler) ResetCreateRepository(variables ...CreateRepositoryVariables) {
	h.operation0.reset(variables...)
}

func (b *CreateRepositoryExpectation) WithOptions(
	options ...ResponseOption,
) *CreateRepositoryExpectation {
	b.options = combineResponseOptions(b.options, options)
	return b
}

func (b *CreateRepositoryExpectation) Respond(
	data CreateRepositoryResponse,
	options ...ResponseOption,
) {
	combined := combineResponseOptions(b.options, options)
	responseConfig := buildResponseOptions(combined...)
	b.set.setResult(
		b.expected,
		func(_ CreateRepositoryVariables, writer http.ResponseWriter) error {
			return writeGraphQLResponse(writer, &data, nil, responseConfig)
		},
	)
}

func (b *CreateRepositoryExpectation) RespondError(
	graphqlError octoql.Error,
	options ...ResponseOption,
) {
	combined := combineResponseOptions(b.options, options)
	responseConfig := buildResponseOptions(combined...)
	b.set.setResult(
		b.expected,
		func(_ CreateRepositoryVariables, writer http.ResponseWriter) error {
			return writeGraphQLResponse(
				writer,
				nil,
				[]octoql.Error{graphqlError},
				responseConfig,
			)
		},
	)
}

func (b *CreateRepositoryExpectation) RespondDataAndErrors(
	data CreateRepositoryResponse,
	graphqlErrors ...octoql.Error,
) {
	responseConfig := buildResponseOptions(b.options...)
	b.set.setResult(
		b.expected,
		func(_ CreateRepositoryVariables, writer http.ResponseWriter) error {
			return writeGraphQLResponse(
				writer,
				&data,
				graphqlErrors,
				responseConfig,
			)
		},
	)
}

func (b *CreateRepositoryExpectation) Handle(
	handler func(CreateRepositoryVariables, http.ResponseWriter),
) {
	if handler == nil {
		b.set.tb.Errorf("CreateRepository dynamic handler must not be nil")
		b.set.setResult(
			b.expected,
			func(_ CreateRepositoryVariables, _ http.ResponseWriter) error {
				return fmt.Errorf("CreateRepository dynamic handler is nil")
			},
		)
		return
	}
	b.set.setResult(
		b.expected,
		func(variables CreateRepositoryVariables, writer http.ResponseWriter) error {
			handler(variables, writer)
			return nil
		},
	)
}

type EchoAnyExpectation struct {
	set      *expectationSet[EchoAnyVariables]
	expected *expectation[EchoAnyVariables]
	options  []ResponseOption
}

func (h *TestHandler) ExpectEchoAny(
	variables EchoAnyVariables,
	options ...ExpectOption,
) *EchoAnyExpectation {
	return &EchoAnyExpectation{
		set: &h.operation1,
		expected: h.operation1.expect(
			variables,
			options...,
		),
		options: []ResponseOption{},
	}
}

func (h *TestHandler) DefaultEchoAny() *EchoAnyExpectation {
	return &EchoAnyExpectation{
		set:      &h.operation1,
		expected: h.operation1.expectDefault(),
		options:  []ResponseOption{},
	}
}

func (h *TestHandler) ResetEchoAny(variables ...EchoAnyVariables) {
	h.operation1.reset(variables...)
}

func (b *EchoAnyExpectation) WithOptions(
	options ...ResponseOption,
) *EchoAnyExpectation {
	b.options = combineResponseOptions(b.options, options)
	return b
}

func (b *EchoAnyExpectation) Respond(
	data EchoAnyResponse,
	options ...ResponseOption,
) {
	combined := combineResponseOptions(b.options, options)
	responseConfig := buildResponseOptions(combined...)
	b.set.setResult(
		b.expected,
		func(_ EchoAnyVariables, writer http.ResponseWriter) error {
			return writeGraphQLResponse(writer, &data, nil, responseConfig)
		},
	)
}

func (b *EchoAnyExpectation) RespondError(
	graphqlError octoql.Error,
	options ...ResponseOption,
) {
	combined := combineResponseOptions(b.options, options)
	responseConfig := buildResponseOptions(combined...)
	b.set.setResult(
		b.expected,
		func(_ EchoAnyVariables, writer http.ResponseWriter) error {
			return writeGraphQLResponse(
				writer,
				nil,
				[]octoql.Error{graphqlError},
				responseConfig,
			)
		},
	)
}

func (b *EchoAnyExpectation) RespondDataAndErrors(
	data EchoAnyResponse,
	graphqlErrors ...octoql.Error,
) {
	responseConfig := buildResponseOptions(b.options...)
	b.set.setResult(
		b.expected,
		func(_ EchoAnyVariables, writer http.ResponseWriter) error {
			return writeGraphQLResponse(
				writer,
				&data,
				graphqlErrors,
				responseConfig,
			)
		},
	)
}

func (b *EchoAnyExpectation) Handle(
	handler func(EchoAnyVariables, http.ResponseWriter),
) {
	if handler == nil {
		b.set.tb.Errorf("EchoAny dynamic handler must not be nil")
		b.set.setResult(
			b.expected,
			func(_ EchoAnyVariables, _ http.ResponseWriter) error {
				return fmt.Errorf("EchoAny dynamic handler is nil")
			},
		)
		return
	}
	b.set.setResult(
		b.expected,
		func(variables EchoAnyVariables, writer http.ResponseWriter) error {
			handler(variables, writer)
			return nil
		},
	)
}

type EchoAtExpectation struct {
	set      *expectationSet[EchoAtVariables]
	expected *expectation[EchoAtVariables]
	options  []ResponseOption
}

func (h *TestHandler) ExpectEchoAt(
	variables EchoAtVariables,
	options ...ExpectOption,
) *EchoAtExpectation {
	return &EchoAtExpectation{
		set: &h.operation2,
		expected: h.operation2.expect(
			variables,
			options...,
		),
		options: []ResponseOption{},
	}
}

func (h *TestHandler) DefaultEchoAt() *EchoAtExpectation {
	return &EchoAtExpectation{
		set:      &h.operation2,
		expected: h.operation2.expectDefault(),
		options:  []ResponseOption{},
	}
}

func (h *TestHandler) ResetEchoAt(variables ...EchoAtVariables) {
	h.operation2.reset(variables...)
}

func (b *EchoAtExpectation) WithOptions(
	options ...ResponseOption,
) *EchoAtExpectation {
	b.options = combineResponseOptions(b.options, options)
	return b
}

func (b *EchoAtExpectation) Respond(
	data EchoAtResponse,
	options ...ResponseOption,
) {
	combined := combineResponseOptions(b.options, options)
	responseConfig := buildResponseOptions(combined...)
	b.set.setResult(
		b.expected,
		func(_ EchoAtVariables, writer http.ResponseWriter) error {
			return writeGraphQLResponse(writer, &data, nil, responseConfig)
		},
	)
}

func (b *EchoAtExpectation) RespondError(
	graphqlError octoql.Error,
	options ...ResponseOption,
) {
	combined := combineResponseOptions(b.options, options)
	responseConfig := buildResponseOptions(combined...)
	b.set.setResult(
		b.expected,
		func(_ EchoAtVariables, writer http.ResponseWriter) error {
			return writeGraphQLResponse(
				writer,
				nil,
				[]octoql.Error{graphqlError},
				responseConfig,
			)
		},
	)
}

func (b *EchoAtExpectation) RespondDataAndErrors(
	data EchoAtResponse,
	graphqlErrors ...octoql.Error,
) {
	responseConfig := buildResponseOptions(b.options...)
	b.set.setResult(
		b.expected,
		func(_ EchoAtVariables, writer http.ResponseWriter) error {
			return writeGraphQLResponse(
				writer,
				&data,
				graphqlErrors,
				responseConfig,
			)
		},
	)
}

func (b *EchoAtExpectation) Handle(
	handler func(EchoAtVariables, http.ResponseWriter),
) {
	if handler == nil {
		b.set.tb.Errorf("EchoAt dynamic handler must not be nil")
		b.set.setResult(
			b.expected,
			func(_ EchoAtVariables, _ http.ResponseWriter) error {
				return fmt.Errorf("EchoAt dynamic handler is nil")
			},
		)
		return
	}
	b.set.setResult(
		b.expected,
		func(variables EchoAtVariables, writer http.ResponseWriter) error {
			handler(variables, writer)
			return nil
		},
	)
}

type EchoPropertyExpectation struct {
	set      *expectationSet[EchoPropertyVariables]
	expected *expectation[EchoPropertyVariables]
	options  []ResponseOption
}

func (h *TestHandler) ExpectEchoProperty(
	variables EchoPropertyVariables,
	options ...ExpectOption,
) *EchoPropertyExpectation {
	return &EchoPropertyExpectation{
		set: &h.operation3,
		expected: h.operation3.expect(
			variables,
			options...,
		),
		options: []ResponseOption{},
	}
}

func (h *TestHandler) DefaultEchoProperty() *EchoPropertyExpectation {
	return &EchoPropertyExpectation{
		set:      &h.operation3,
		expected: h.operation3.expectDefault(),
		options:  []ResponseOption{},
	}
}

func (h *TestHandler) ResetEchoProperty(variables ...EchoPropertyVariables) {
	h.operation3.reset(variables...)
}

func (b *EchoPropertyExpectation) WithOptions(
	options ...ResponseOption,
) *EchoPropertyExpectation {
	b.options = combineResponseOptions(b.options, options)
	return b
}

func (b *EchoPropertyExpectation) Respond(
	data EchoPropertyResponse,
	options ...ResponseOption,
) {
	combined := combineResponseOptions(b.options, options)
	responseConfig := buildResponseOptions(combined...)
	b.set.setResult(
		b.expected,
		func(_ EchoPropertyVariables, writer http.ResponseWriter) error {
			return writeGraphQLResponse(writer, &data, nil, responseConfig)
		},
	)
}

func (b *EchoPropertyExpectation) RespondError(
	graphqlError octoql.Error,
	options ...ResponseOption,
) {
	combined := combineResponseOptions(b.options, options)
	responseConfig := buildResponseOptions(combined...)
	b.set.setResult(
		b.expected,
		func(_ EchoPropertyVariables, writer http.ResponseWriter) error {
			return writeGraphQLResponse(
				writer,
				nil,
				[]octoql.Error{graphqlError},
				responseConfig,
			)
		},
	)
}

func (b *EchoPropertyExpectation) RespondDataAndErrors(
	data EchoPropertyResponse,
	graphqlErrors ...octoql.Error,
) {
	responseConfig := buildResponseOptions(b.options...)
	b.set.setResult(
		b.expected,
		func(_ EchoPropertyVariables, writer http.ResponseWriter) error {
			return writeGraphQLResponse(
				writer,
				&data,
				graphqlErrors,
				responseConfig,
			)
		},
	)
}

func (b *EchoPropertyExpectation) Handle(
	handler func(EchoPropertyVariables, http.ResponseWriter),
) {
	if handler == nil {
		b.set.tb.Errorf("EchoProperty dynamic handler must not be nil")
		b.set.setResult(
			b.expected,
			func(_ EchoPropertyVariables, _ http.ResponseWriter) error {
				return fmt.Errorf("EchoProperty dynamic handler is nil")
			},
		)
		return
	}
	b.set.setResult(
		b.expected,
		func(variables EchoPropertyVariables, writer http.ResponseWriter) error {
			handler(variables, writer)
			return nil
		},
	)
}

type GetNodeExpectation struct {
	set      *expectationSet[GetNodeVariables]
	expected *expectation[GetNodeVariables]
	options  []ResponseOption
}

func (h *TestHandler) ExpectGetNode(
	variables GetNodeVariables,
	options ...ExpectOption,
) *GetNodeExpectation {
	return &GetNodeExpectation{
		set: &h.operation4,
		expected: h.operation4.expect(
			variables,
			options...,
		),
		options: []ResponseOption{},
	}
}

func (h *TestHandler) DefaultGetNode() *GetNodeExpectation {
	return &GetNodeExpectation{
		set:      &h.operation4,
		expected: h.operation4.expectDefault(),
		options:  []ResponseOption{},
	}
}

func (h *TestHandler) ResetGetNode(variables ...GetNodeVariables) {
	h.operation4.reset(variables...)
}

func (b *GetNodeExpectation) WithOptions(
	options ...ResponseOption,
) *GetNodeExpectation {
	b.options = combineResponseOptions(b.options, options)
	return b
}

func (b *GetNodeExpectation) Respond(
	data GetNodeResponse,
	options ...ResponseOption,
) {
	combined := combineResponseOptions(b.options, options)
	responseConfig := buildResponseOptions(combined...)
	b.set.setResult(
		b.expected,
		func(_ GetNodeVariables, writer http.ResponseWriter) error {
			return writeGraphQLResponse(writer, &data, nil, responseConfig)
		},
	)
}

func (b *GetNodeExpectation) RespondError(
	graphqlError octoql.Error,
	options ...ResponseOption,
) {
	combined := combineResponseOptions(b.options, options)
	responseConfig := buildResponseOptions(combined...)
	b.set.setResult(
		b.expected,
		func(_ GetNodeVariables, writer http.ResponseWriter) error {
			return writeGraphQLResponse(
				writer,
				nil,
				[]octoql.Error{graphqlError},
				responseConfig,
			)
		},
	)
}

func (b *GetNodeExpectation) RespondDataAndErrors(
	data GetNodeResponse,
	graphqlErrors ...octoql.Error,
) {
	responseConfig := buildResponseOptions(b.options...)
	b.set.setResult(
		b.expected,
		func(_ GetNodeVariables, writer http.ResponseWriter) error {
			return writeGraphQLResponse(
				writer,
				&data,
				graphqlErrors,
				responseConfig,
			)
		},
	)
}

func (b *GetNodeExpectation) Handle(
	handler func(GetNodeVariables, http.ResponseWriter),
) {
	if handler == nil {
		b.set.tb.Errorf("GetNode dynamic handler must not be nil")
		b.set.setResult(
			b.expected,
			func(_ GetNodeVariables, _ http.ResponseWriter) error {
				return fmt.Errorf("GetNode dynamic handler is nil")
			},
		)
		return
	}
	b.set.setResult(
		b.expected,
		func(variables GetNodeVariables, writer http.ResponseWriter) error {
			handler(variables, writer)
			return nil
		},
	)
}

type GetRepositoryExpectation struct {
	set      *expectationSet[GetRepositoryVariables]
	expected *expectation[GetRepositoryVariables]
	options  []ResponseOption
}

func (h *TestHandler) ExpectGetRepository(
	variables GetRepositoryVariables,
	options ...ExpectOption,
) *GetRepositoryExpectation {
	return &GetRepositoryExpectation{
		set: &h.operation5,
		expected: h.operation5.expect(
			variables,
			options...,
		),
		options: []ResponseOption{},
	}
}

func (h *TestHandler) DefaultGetRepository() *GetRepositoryExpectation {
	return &GetRepositoryExpectation{
		set:      &h.operation5,
		expected: h.operation5.expectDefault(),
		options:  []ResponseOption{},
	}
}

func (h *TestHandler) ResetGetRepository(variables ...GetRepositoryVariables) {
	h.operation5.reset(variables...)
}

func (b *GetRepositoryExpectation) WithOptions(
	options ...ResponseOption,
) *GetRepositoryExpectation {
	b.options = combineResponseOptions(b.options, options)
	return b
}

func (b *GetRepositoryExpectation) Respond(
	data GetRepositoryResponse,
	options ...ResponseOption,
) {
	combined := combineResponseOptions(b.options, options)
	responseConfig := buildResponseOptions(combined...)
	b.set.setResult(
		b.expected,
		func(_ GetRepositoryVariables, writer http.ResponseWriter) error {
			return writeGraphQLResponse(writer, &data, nil, responseConfig)
		},
	)
}

func (b *GetRepositoryExpectation) RespondError(
	graphqlError octoql.Error,
	options ...ResponseOption,
) {
	combined := combineResponseOptions(b.options, options)
	responseConfig := buildResponseOptions(combined...)
	b.set.setResult(
		b.expected,
		func(_ GetRepositoryVariables, writer http.ResponseWriter) error {
			return writeGraphQLResponse(
				writer,
				nil,
				[]octoql.Error{graphqlError},
				responseConfig,
			)
		},
	)
}

func (b *GetRepositoryExpectation) RespondDataAndErrors(
	data GetRepositoryResponse,
	graphqlErrors ...octoql.Error,
) {
	responseConfig := buildResponseOptions(b.options...)
	b.set.setResult(
		b.expected,
		func(_ GetRepositoryVariables, writer http.ResponseWriter) error {
			return writeGraphQLResponse(
				writer,
				&data,
				graphqlErrors,
				responseConfig,
			)
		},
	)
}

func (b *GetRepositoryExpectation) Handle(
	handler func(GetRepositoryVariables, http.ResponseWriter),
) {
	if handler == nil {
		b.set.tb.Errorf("GetRepository dynamic handler must not be nil")
		b.set.setResult(
			b.expected,
			func(_ GetRepositoryVariables, _ http.ResponseWriter) error {
				return fmt.Errorf("GetRepository dynamic handler is nil")
			},
		)
		return
	}
	b.set.setResult(
		b.expected,
		func(variables GetRepositoryVariables, writer http.ResponseWriter) error {
			handler(variables, writer)
			return nil
		},
	)
}

type SearchExpectation struct {
	set      *expectationSet[SearchVariables]
	expected *expectation[SearchVariables]
	options  []ResponseOption
}

func (h *TestHandler) ExpectSearch(
	variables SearchVariables,
	options ...ExpectOption,
) *SearchExpectation {
	return &SearchExpectation{
		set: &h.operation6,
		expected: h.operation6.expect(
			variables,
			options...,
		),
		options: []ResponseOption{},
	}
}

func (h *TestHandler) DefaultSearch() *SearchExpectation {
	return &SearchExpectation{
		set:      &h.operation6,
		expected: h.operation6.expectDefault(),
		options:  []ResponseOption{},
	}
}

func (h *TestHandler) ResetSearch(variables ...SearchVariables) {
	h.operation6.reset(variables...)
}

func (b *SearchExpectation) WithOptions(
	options ...ResponseOption,
) *SearchExpectation {
	b.options = combineResponseOptions(b.options, options)
	return b
}

func (b *SearchExpectation) Respond(
	data SearchResponse,
	options ...ResponseOption,
) {
	combined := combineResponseOptions(b.options, options)
	responseConfig := buildResponseOptions(combined...)
	b.set.setResult(
		b.expected,
		func(_ SearchVariables, writer http.ResponseWriter) error {
			return writeGraphQLResponse(writer, &data, nil, responseConfig)
		},
	)
}

func (b *SearchExpectation) RespondError(
	graphqlError octoql.Error,
	options ...ResponseOption,
) {
	combined := combineResponseOptions(b.options, options)
	responseConfig := buildResponseOptions(combined...)
	b.set.setResult(
		b.expected,
		func(_ SearchVariables, writer http.ResponseWriter) error {
			return writeGraphQLResponse(
				writer,
				nil,
				[]octoql.Error{graphqlError},
				responseConfig,
			)
		},
	)
}

func (b *SearchExpectation) RespondDataAndErrors(
	data SearchResponse,
	graphqlErrors ...octoql.Error,
) {
	responseConfig := buildResponseOptions(b.options...)
	b.set.setResult(
		b.expected,
		func(_ SearchVariables, writer http.ResponseWriter) error {
			return writeGraphQLResponse(
				writer,
				&data,
				graphqlErrors,
				responseConfig,
			)
		},
	)
}

func (b *SearchExpectation) Handle(
	handler func(SearchVariables, http.ResponseWriter),
) {
	if handler == nil {
		b.set.tb.Errorf("Search dynamic handler must not be nil")
		b.set.setResult(
			b.expected,
			func(_ SearchVariables, _ http.ResponseWriter) error {
				return fmt.Errorf("Search dynamic handler is nil")
			},
		)
		return
	}
	b.set.setResult(
		b.expected,
		func(variables SearchVariables, writer http.ResponseWriter) error {
			handler(variables, writer)
			return nil
		},
	)
}

type ViewerExpectation struct {
	set      *expectationSet[struct{}]
	expected *expectation[struct{}]
	options  []ResponseOption
}

func (h *TestHandler) ExpectViewer(
	options ...ExpectOption,
) *ViewerExpectation {
	return &ViewerExpectation{
		set: &h.operation7,
		expected: h.operation7.expect(
			struct{}{},
			options...,
		),
		options: []ResponseOption{},
	}
}

func (h *TestHandler) DefaultViewer() *ViewerExpectation {
	return &ViewerExpectation{
		set:      &h.operation7,
		expected: h.operation7.expectDefault(),
		options:  []ResponseOption{},
	}
}

func (h *TestHandler) ResetViewer() {
	h.operation7.reset()
}

func (b *ViewerExpectation) WithOptions(
	options ...ResponseOption,
) *ViewerExpectation {
	b.options = combineResponseOptions(b.options, options)
	return b
}

func (b *ViewerExpectation) Respond(
	data ViewerResponse,
	options ...ResponseOption,
) {
	combined := combineResponseOptions(b.options, options)
	responseConfig := buildResponseOptions(combined...)
	b.set.setResult(
		b.expected,
		func(_ struct{}, writer http.ResponseWriter) error {
			return writeGraphQLResponse(writer, &data, nil, responseConfig)
		},
	)
}

func (b *ViewerExpectation) RespondError(
	graphqlError octoql.Error,
	options ...ResponseOption,
) {
	combined := combineResponseOptions(b.options, options)
	responseConfig := buildResponseOptions(combined...)
	b.set.setResult(
		b.expected,
		func(_ struct{}, writer http.ResponseWriter) error {
			return writeGraphQLResponse(
				writer,
				nil,
				[]octoql.Error{graphqlError},
				responseConfig,
			)
		},
	)
}

func (b *ViewerExpectation) RespondDataAndErrors(
	data ViewerResponse,
	graphqlErrors ...octoql.Error,
) {
	responseConfig := buildResponseOptions(b.options...)
	b.set.setResult(
		b.expected,
		func(_ struct{}, writer http.ResponseWriter) error {
			return writeGraphQLResponse(
				writer,
				&data,
				graphqlErrors,
				responseConfig,
			)
		},
	)
}

func (b *ViewerExpectation) Handle(
	handler func(http.ResponseWriter),
) {
	if handler == nil {
		b.set.tb.Errorf("Viewer dynamic handler must not be nil")
		b.set.setResult(
			b.expected,
			func(_ struct{}, _ http.ResponseWriter) error {
				return fmt.Errorf("Viewer dynamic handler is nil")
			},
		)
		return
	}
	b.set.setResult(
		b.expected,
		func(variables struct{}, writer http.ResponseWriter) error {
			handler(writer)
			return nil
		},
	)
}
