name: ci

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
    types:
      - synchronize
      - opened
      - reopened
      - labeled
      - unlabeled
  workflow_dispatch:

permissions:
  contents: read

jobs:
  test:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v6
      - uses: WillAbides/setup-go-faster@v1
        id: setup-go
        with:
          go-version-file: go.mod
      - uses: actions/cache@v5
        with:
          path: |
            ${{ steps.setup-go.outputs.GOCACHE }}
            ${{ steps.setup-go.outputs.GOMODCACHE }}
          key: ${{ runner.os }}-test-${{ hashFiles('go.*', '.github/workflows/ci.yaml', 'script/*', '.bindown.yaml', '.goreleaser.yaml') }}
          restore-keys: ${{ runner.os }}-test-
      - run: script/test

  lint:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v6
      - uses: WillAbides/setup-go-faster@v1
        id: setup-go
        with:
          go-version-file: go.mod
      - uses: actions/cache@v5
        with:
          path: |
            ${{ steps.setup-go.outputs.GOCACHE }}
            ${{ steps.setup-go.outputs.GOMODCACHE }}
          key: ${{ runner.os }}-lint-${{ hashFiles('go.*', '.github/workflows/ci.yaml', 'script/*', '.bindown.yaml', '.goreleaser.yaml') }}
          restore-keys: ${{ runner.os }}-lint-
      - run: script/lint

  generate:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v6
      - uses: WillAbides/setup-go-faster@v1
        id: setup-go
        with:
          go-version-file: go.mod
      - uses: actions/cache@v5
        with:
          path: |
            ${{ steps.setup-go.outputs.GOCACHE }}
            ${{ steps.setup-go.outputs.GOMODCACHE }}
          key: ${{ runner.os }}-generate-${{ hashFiles('go.*', '.github/workflows/ci.yaml', 'script/*', '.bindown.yaml', '.goreleaser.yaml') }}
          restore-keys: ${{ runner.os }}-generate-
      - run: script/generate --check

  release:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v6
        with:
          fetch-depth: 0
      - uses: WillAbides/setup-go-faster@v1
        id: setup-go
        with:
          go-version-file: go.mod
      - uses: actions/cache@v5
        with:
          path: |
            ${{ steps.setup-go.outputs.GOCACHE }}
            ${{ steps.setup-go.outputs.GOMODCACHE }}
          key: ${{ runner.os }}-release-${{ hashFiles('go.*', '.github/workflows/ci.yaml', 'script/*', '.bindown.yaml', '.goreleaser.yaml') }}
          restore-keys: ${{ runner.os }}-release-
      - run: script/bindown -q install goreleaser
      - run: bin/goreleaser build --snapshot --clean
      - uses: WillAbides/release-train@v3.9.0
        if: github.event_name == 'pull_request'

  publish:
    if: github.event_name != 'pull_request'
    needs:
      - test
      - lint
      - generate
      - release
    runs-on: ubuntu-24.04
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v6
        with:
          fetch-depth: 0
      - uses: WillAbides/setup-go-faster@v1
        with:
          go-version-file: go.mod
      - uses: WillAbides/release-train@v3.9.0
        id: release-train
        with:
          create-release: true
          release-refs: main
          pre-tag-hook: script/release-hook
      - name: add bindown template
        env:
          RELEASE_TAG: ${{ steps.release-train.outputs.release-tag }}
          GH_TOKEN: ${{ github.token }}
          GITHUB_TOKEN: ${{ github.token }}
        if: steps.release-train.outputs.created-release == 'true'
        run: |
          #!/bin/sh
          set -e
          script/bindown -q install gh
          CONFIG_FILE="$(pwd)/tmp/add-tmpl/bindown.yaml"
          mkdir -p "$(dirname "$CONFIG_FILE")"
          echo '{}' > "$CONFIG_FILE"
          yes '' | script/bindown dependency add-by-github-release \
            "$GITHUB_REPOSITORY@$RELEASE_TAG" \
            --name octoqlgen \
            --configfile "$CONFIG_FILE" \
            --experimental
          bin/gh release upload "$RELEASE_TAG" "$CONFIG_FILE"
