// Code generated by octoqlgen, DO NOT EDIT.
// SPDX-License-Identifier: MIT

package test

import (
	"context"

	"github.com/willabides/octoql"
)

// DefaultInputsResponse is returned by DefaultInputs on success.
type DefaultInputsResponse struct {
	Default bool `json:"default"`
}

// GetDefault returns DefaultInputsResponse.Default, and is useful for accessing the field via an interface.
func (v *DefaultInputsResponse) GetDefault() bool { return v.Default }

type InputWithDefaults struct {
	Field         string  `json:"field"`
	NullableField *string `json:"nullableField"`
}

// GetField returns InputWithDefaults.Field, and is useful for accessing the field via an interface.
func (v *InputWithDefaults) GetField() string { return v.Field }

// GetNullableField returns InputWithDefaults.NullableField, and is useful for accessing the field via an interface.
func (v *InputWithDefaults) GetNullableField() *string { return v.NullableField }

// __DefaultInputsInput is used internally by genqlient
type __DefaultInputsInput struct {
	Input InputWithDefaults `json:"input"`
}

// GetInput returns __DefaultInputsInput.Input, and is useful for accessing the field via an interface.
func (v *__DefaultInputsInput) GetInput() InputWithDefaults { return v.Input }

// The query executed by DefaultInputs.
const DefaultInputs_Operation = `
query DefaultInputs ($input: InputWithDefaults!) {
	default(input: $input)
}
`

// The `InputWithDefaults.field` cannot be `pointer: true`, together with implicit `omitempty: false`, as `null` is
// not a valid value there. However, nullableField should still be ok
// (this will send null, overwriting the server's default)
func DefaultInputs(
	client_ *octoql.Client,
	input InputWithDefaults,
) (*octoql.Response[DefaultInputsResponse], error) {
	variables_ := __DefaultInputsInput{
		Input: input,
	}
	return octoql.Do[DefaultInputsResponse](
		context.Background(),
		client_,
		octoql.Operation{
			Name:  "DefaultInputs",
			Query: DefaultInputs_Operation,
		},
		&variables_,
	)
}

