// Code generated by octoqlgen, DO NOT EDIT.
// SPDX-License-Identifier: MIT

package test

import (
	"context"

	"github.com/willabides/octoql"
)

// ListOfListsOfListsResponse is returned by ListOfListsOfLists on success.
type ListOfListsOfListsResponse struct {
	ListOfListsOfLists [][][]string `json:"listOfListsOfLists"`
}

// GetListOfListsOfLists returns ListOfListsOfListsResponse.ListOfListsOfLists, and is useful for accessing the field via an interface.
func (v *ListOfListsOfListsResponse) GetListOfListsOfLists() [][][]string {
	return v.ListOfListsOfLists
}

// The query executed by ListOfListsOfLists.
const ListOfListsOfLists_Operation = `
query ListOfListsOfLists {
	listOfListsOfLists
}
`

func ListOfListsOfLists(
	client_ *octoql.Client,
) (*octoql.Response[ListOfListsOfListsResponse], error) {
	return octoql.Do[ListOfListsOfListsResponse](
		context.Background(),
		client_,
		octoql.Operation{
			Name:  "ListOfListsOfLists",
			Query: ListOfListsOfLists_Operation,
		},
		nil,
	)
}

