// Code generated by octoqlgen, DO NOT EDIT.
// SPDX-License-Identifier: MIT

package queries

import (
	context2 "context"

	octoql2 "github.com/willabides/octoql"
)

// RepositoryVariableNameCollisionsContextNameRepository includes the requested fields of the GraphQL type Repository.
type RepositoryVariableNameCollisionsContextNameRepository struct {
	NameWithOwner string `json:"nameWithOwner"`
}

// GetNameWithOwner returns RepositoryVariableNameCollisionsContextNameRepository.NameWithOwner, and is useful for accessing the field via an interface.
func (v *RepositoryVariableNameCollisionsContextNameRepository) GetNameWithOwner() string {
	return v.NameWithOwner
}

// RepositoryVariableNameCollisionsErrorsRepository includes the requested fields of the GraphQL type Repository.
type RepositoryVariableNameCollisionsErrorsRepository struct {
	NameWithOwner string `json:"nameWithOwner"`
}

// GetNameWithOwner returns RepositoryVariableNameCollisionsErrorsRepository.NameWithOwner, and is useful for accessing the field via an interface.
func (v *RepositoryVariableNameCollisionsErrorsRepository) GetNameWithOwner() string {
	return v.NameWithOwner
}

// RepositoryVariableNameCollisionsPrimaryRepository includes the requested fields of the GraphQL type Repository.
type RepositoryVariableNameCollisionsPrimaryRepository struct {
	NameWithOwner string `json:"nameWithOwner"`
}

// GetNameWithOwner returns RepositoryVariableNameCollisionsPrimaryRepository.NameWithOwner, and is useful for accessing the field via an interface.
func (v *RepositoryVariableNameCollisionsPrimaryRepository) GetNameWithOwner() string {
	return v.NameWithOwner
}

// RepositoryVariableNameCollisionsResponse is returned by RepositoryVariableNameCollisions on success.
type RepositoryVariableNameCollisionsResponse struct {
	Primary     RepositoryVariableNameCollisionsPrimaryRepository     `json:"primary"`
	Variables   RepositoryVariableNameCollisionsVariablesRepository   `json:"variables"`
	Errors      RepositoryVariableNameCollisionsErrorsRepository      `json:"errors"`
	ContextName RepositoryVariableNameCollisionsContextNameRepository `json:"contextName"`
}

// GetPrimary returns RepositoryVariableNameCollisionsResponse.Primary, and is useful for accessing the field via an interface.
func (v *RepositoryVariableNameCollisionsResponse) GetPrimary() RepositoryVariableNameCollisionsPrimaryRepository {
	return v.Primary
}

// GetVariables returns RepositoryVariableNameCollisionsResponse.Variables, and is useful for accessing the field via an interface.
func (v *RepositoryVariableNameCollisionsResponse) GetVariables() RepositoryVariableNameCollisionsVariablesRepository {
	return v.Variables
}

// GetErrors returns RepositoryVariableNameCollisionsResponse.Errors, and is useful for accessing the field via an interface.
func (v *RepositoryVariableNameCollisionsResponse) GetErrors() RepositoryVariableNameCollisionsErrorsRepository {
	return v.Errors
}

// GetContextName returns RepositoryVariableNameCollisionsResponse.ContextName, and is useful for accessing the field via an interface.
func (v *RepositoryVariableNameCollisionsResponse) GetContextName() RepositoryVariableNameCollisionsContextNameRepository {
	return v.ContextName
}

// RepositoryVariableNameCollisionsVariablesRepository includes the requested fields of the GraphQL type Repository.
type RepositoryVariableNameCollisionsVariablesRepository struct {
	NameWithOwner string `json:"nameWithOwner"`
}

// GetNameWithOwner returns RepositoryVariableNameCollisionsVariablesRepository.NameWithOwner, and is useful for accessing the field via an interface.
func (v *RepositoryVariableNameCollisionsVariablesRepository) GetNameWithOwner() string {
	return v.NameWithOwner
}

// __RepositoryVariableNameCollisionsInput is used internally by genqlient
type __RepositoryVariableNameCollisionsInput struct {
	Variables_ string `json:"variables_"`
	Octoql     string `json:"octoql"`
	Context    string `json:"context"`
	Ctx_       string `json:"ctx_"`
	Client_    string `json:"client_"`
	Err_       string `json:"err_"`
}

// GetVariables_ returns __RepositoryVariableNameCollisionsInput.Variables_, and is useful for accessing the field via an interface.
func (v *__RepositoryVariableNameCollisionsInput) GetVariables_() string { return v.Variables_ }

// GetOctoql returns __RepositoryVariableNameCollisionsInput.Octoql, and is useful for accessing the field via an interface.
func (v *__RepositoryVariableNameCollisionsInput) GetOctoql() string { return v.Octoql }

// GetContext returns __RepositoryVariableNameCollisionsInput.Context, and is useful for accessing the field via an interface.
func (v *__RepositoryVariableNameCollisionsInput) GetContext() string { return v.Context }

// GetCtx_ returns __RepositoryVariableNameCollisionsInput.Ctx_, and is useful for accessing the field via an interface.
func (v *__RepositoryVariableNameCollisionsInput) GetCtx_() string { return v.Ctx_ }

// GetClient_ returns __RepositoryVariableNameCollisionsInput.Client_, and is useful for accessing the field via an interface.
func (v *__RepositoryVariableNameCollisionsInput) GetClient_() string { return v.Client_ }

// GetErr_ returns __RepositoryVariableNameCollisionsInput.Err_, and is useful for accessing the field via an interface.
func (v *__RepositoryVariableNameCollisionsInput) GetErr_() string { return v.Err_ }

// The query executed by RepositoryVariableNameCollisions.
const RepositoryVariableNameCollisions_Operation = `
query RepositoryVariableNameCollisions ($variables_: String!, $octoql: String!, $context: String!, $ctx_: String!, $client_: String!, $err_: String!) {
	primary: repository(owner: $octoql, name: $context) {
		nameWithOwner
	}
	variables: repository(owner: $variables_, name: $client_) {
		nameWithOwner
	}
	errors: repository(owner: $err_, name: $octoql) {
		nameWithOwner
	}
	contextName: repository(owner: $ctx_, name: $context) {
		nameWithOwner
	}
}
`

func RepositoryVariableNameCollisions(
	ctx_2 context2.Context,
	client_2 *octoql2.Client,
	variables_ string,
	octoql string,
	context string,
	ctx_ string,
	client_ string,
	err_ string,
) (*octoql2.Response[RepositoryVariableNameCollisionsResponse], error) {
	variables_2 := __RepositoryVariableNameCollisionsInput{
		Variables_: variables_,
		Octoql:     octoql,
		Context:    context,
		Ctx_:       ctx_,
		Client_:    client_,
		Err_:       err_,
	}
	return octoql2.Do[RepositoryVariableNameCollisionsResponse](
		ctx_2,
		client_2,
		octoql2.Operation{
			Name:  "RepositoryVariableNameCollisions",
			Query: RepositoryVariableNameCollisions_Operation,
		},
		&variables_2,
	)
}

