// Code generated by octoqlgen, DO NOT EDIT.
// SPDX-License-Identifier: MIT

package queries

import (
	"context"

	"github.com/willabides/octoql"
	"github.com/willabides/octoql/internal/testutil"
)

// SimpleQueryResponse is returned by SimpleQuery on success.
type SimpleQueryResponse struct {
	// user looks up a user by some stuff.
	//
	// See UserQueryInput for what stuff is supported.
	// If query is null, returns the current user.
	User SimpleQueryUser `json:"user"`
}

// GetUser returns SimpleQueryResponse.User, and is useful for accessing the field via an interface.
func (v *SimpleQueryResponse) GetUser() SimpleQueryUser { return v.User }

// SimpleQueryUser includes the requested fields of the GraphQL type User.
// The GraphQL type's documentation follows.
//
// A User is a user!
type SimpleQueryUser struct {
	// id is the user's ID.
	//
	// It is stable, unique, and opaque, like all good IDs.
	Id string `json:"id"`
}

// GetId returns SimpleQueryUser.Id, and is useful for accessing the field via an interface.
func (v *SimpleQueryUser) GetId() string { return v.Id }

// The query executed by SimpleQuery.
const SimpleQuery_Operation = `
query SimpleQuery {
	user {
		id
	}
}
`

func SimpleQuery(
	ctx_ context.Context,
) (*octoql.Response[SimpleQueryResponse], error) {
	client_, err_ := testutil.GetClientFromContext(ctx_)
	if err_ != nil {
		return nil, err_
	}
	return octoql.Do[SimpleQueryResponse](
		ctx_,
		client_,
		octoql.Operation{
			Name:  "SimpleQuery",
			Query: SimpleQuery_Operation,
		},
		nil,
	)
}

