// Code generated by octoqlgen, DO NOT EDIT.
// SPDX-License-Identifier: MIT

package test

import (
	"context"

	"github.com/willabides/octoql"
)

// OmitemptyFalseResponse is returned by OmitemptyFalse on success.
type OmitemptyFalseResponse struct {
	Omitempty bool `json:"omitempty"`
}

// GetOmitempty returns OmitemptyFalseResponse.Omitempty, and is useful for accessing the field via an interface.
func (v *OmitemptyFalseResponse) GetOmitempty() bool { return v.Omitempty }

type OmitemptyInput struct {
	Field         string `json:"field"`
	NullableField string `json:"nullableField,omitempty"`
}

// GetField returns OmitemptyInput.Field, and is useful for accessing the field via an interface.
func (v *OmitemptyInput) GetField() string { return v.Field }

// GetNullableField returns OmitemptyInput.NullableField, and is useful for accessing the field via an interface.
func (v *OmitemptyInput) GetNullableField() string { return v.NullableField }

// __OmitemptyFalseInput is used internally by genqlient
type __OmitemptyFalseInput struct {
	Input OmitemptyInput `json:"input,omitempty"`
}

// GetInput returns __OmitemptyFalseInput.Input, and is useful for accessing the field via an interface.
func (v *__OmitemptyFalseInput) GetInput() OmitemptyInput { return v.Input }

// The query executed by OmitemptyFalse.
const OmitemptyFalse_Operation = `
query OmitemptyFalse ($input: OmitemptyInput) {
	omitempty(input: $input)
}
`

func OmitemptyFalse(
	client_ *octoql.Client,
	input OmitemptyInput,
) (*octoql.Response[OmitemptyFalseResponse], error) {
	variables_ := __OmitemptyFalseInput{
		Input: input,
	}
	return octoql.Do[OmitemptyFalseResponse](
		context.Background(),
		client_,
		octoql.Operation{
			Name:  "OmitemptyFalse",
			Query: OmitemptyFalse_Operation,
		},
		&variables_,
	)
}

