// Code generated by octoqlgen, DO NOT EDIT.
// SPDX-License-Identifier: MIT

package queries

import (
	"context"

	"github.com/willabides/octoql"
	"github.com/willabides/octoql/internal/testutil"
)

type InputWithDefaults struct {
	RequiredLabel string                  `json:"requiredLabel"`
	OptionalLabel testutil.Option[string] `json:"optionalLabel,omitempty"`
}

// GetRequiredLabel returns InputWithDefaults.RequiredLabel, and is useful for accessing the field via an interface.
func (v *InputWithDefaults) GetRequiredLabel() string { return v.RequiredLabel }

// GetOptionalLabel returns InputWithDefaults.OptionalLabel, and is useful for accessing the field via an interface.
func (v *InputWithDefaults) GetOptionalLabel() testutil.Option[string] { return v.OptionalLabel }

type IssueFilter struct {
	States    []IssueState         `json:"states"`
	Labels    []string             `json:"labels"`
	Assignee  *string              `json:"assignee"`
	Milestone testutil.Option[int] `json:"milestone"`
}

// GetStates returns IssueFilter.States, and is useful for accessing the field via an interface.
func (v *IssueFilter) GetStates() []IssueState { return v.States }

// GetLabels returns IssueFilter.Labels, and is useful for accessing the field via an interface.
func (v *IssueFilter) GetLabels() []string { return v.Labels }

// GetAssignee returns IssueFilter.Assignee, and is useful for accessing the field via an interface.
func (v *IssueFilter) GetAssignee() *string { return v.Assignee }

// GetMilestone returns IssueFilter.Milestone, and is useful for accessing the field via an interface.
func (v *IssueFilter) GetMilestone() testutil.Option[int] { return v.Milestone }

type IssueState string

const (
	IssueStateOpen   IssueState = "OPEN"
	IssueStateClosed IssueState = "CLOSED"
)

var AllIssueState = []IssueState{
	IssueStateOpen,
	IssueStateClosed,
}

type OmitemptyInput struct {
	RequiredLabel string                  `json:"requiredLabel"`
	OptionalLabel testutil.Option[string] `json:"optionalLabel"`
}

// GetRequiredLabel returns OmitemptyInput.RequiredLabel, and is useful for accessing the field via an interface.
func (v *OmitemptyInput) GetRequiredLabel() string { return v.RequiredLabel }

// GetOptionalLabel returns OmitemptyInput.OptionalLabel, and is useful for accessing the field via an interface.
func (v *OmitemptyInput) GetOptionalLabel() testutil.Option[string] { return v.OptionalLabel }

// OptionalGitHubInputsRepository includes the requested fields of the GraphQL type Repository.
type OptionalGitHubInputsRepository struct {
	Issues OptionalGitHubInputsRepositoryIssuesIssueConnection `json:"issues"`
}

// GetIssues returns OptionalGitHubInputsRepository.Issues, and is useful for accessing the field via an interface.
func (v *OptionalGitHubInputsRepository) GetIssues() OptionalGitHubInputsRepositoryIssuesIssueConnection {
	return v.Issues
}

// OptionalGitHubInputsRepositoryIssuesIssueConnection includes the requested fields of the GraphQL type IssueConnection.
type OptionalGitHubInputsRepositoryIssuesIssueConnection struct {
	Nodes []OptionalGitHubInputsRepositoryIssuesIssueConnectionNodesIssue `json:"nodes"`
}

// GetNodes returns OptionalGitHubInputsRepositoryIssuesIssueConnection.Nodes, and is useful for accessing the field via an interface.
func (v *OptionalGitHubInputsRepositoryIssuesIssueConnection) GetNodes() []OptionalGitHubInputsRepositoryIssuesIssueConnectionNodesIssue {
	return v.Nodes
}

// OptionalGitHubInputsRepositoryIssuesIssueConnectionNodesIssue includes the requested fields of the GraphQL type Issue.
type OptionalGitHubInputsRepositoryIssuesIssueConnectionNodesIssue struct {
	Id testutil.ID `json:"id"`
}

// GetId returns OptionalGitHubInputsRepositoryIssuesIssueConnectionNodesIssue.Id, and is useful for accessing the field via an interface.
func (v *OptionalGitHubInputsRepositoryIssuesIssueConnectionNodesIssue) GetId() testutil.ID {
	return v.Id
}

// OptionalGitHubInputsResponse is returned by OptionalGitHubInputs on success.
type OptionalGitHubInputsResponse struct {
	Repository testutil.Option[OptionalGitHubInputsRepository] `json:"repository"`
	Default    testutil.Option[bool]                           `json:"default"`
	Omitempty  testutil.Option[bool]                           `json:"omitempty"`
}

// GetRepository returns OptionalGitHubInputsResponse.Repository, and is useful for accessing the field via an interface.
func (v *OptionalGitHubInputsResponse) GetRepository() testutil.Option[OptionalGitHubInputsRepository] {
	return v.Repository
}

// GetDefault returns OptionalGitHubInputsResponse.Default, and is useful for accessing the field via an interface.
func (v *OptionalGitHubInputsResponse) GetDefault() testutil.Option[bool] { return v.Default }

// GetOmitempty returns OptionalGitHubInputsResponse.Omitempty, and is useful for accessing the field via an interface.
func (v *OptionalGitHubInputsResponse) GetOmitempty() testutil.Option[bool] { return v.Omitempty }

// UpdateIssueWithCollidingNamesCloseIssue includes the requested fields of the GraphQL type Issue.
type UpdateIssueWithCollidingNamesCloseIssue struct {
	Id testutil.ID `json:"id"`
}

// GetId returns UpdateIssueWithCollidingNamesCloseIssue.Id, and is useful for accessing the field via an interface.
func (v *UpdateIssueWithCollidingNamesCloseIssue) GetId() testutil.ID { return v.Id }

// UpdateIssueWithCollidingNamesResponse is returned by UpdateIssueWithCollidingNames on success.
type UpdateIssueWithCollidingNamesResponse struct {
	CloseIssue testutil.Option[UpdateIssueWithCollidingNamesCloseIssue] `json:"closeIssue"`
}

// GetCloseIssue returns UpdateIssueWithCollidingNamesResponse.CloseIssue, and is useful for accessing the field via an interface.
func (v *UpdateIssueWithCollidingNamesResponse) GetCloseIssue() testutil.Option[UpdateIssueWithCollidingNamesCloseIssue] {
	return v.CloseIssue
}

// __OptionalGitHubInputsInput is used internally by genqlient
type __OptionalGitHubInputsInput struct {
	Filter   testutil.Option[IssueFilter]    `json:"filter"`
	Defaults InputWithDefaults               `json:"defaults"`
	Optional testutil.Option[OmitemptyInput] `json:"optional"`
}

// GetFilter returns __OptionalGitHubInputsInput.Filter, and is useful for accessing the field via an interface.
func (v *__OptionalGitHubInputsInput) GetFilter() testutil.Option[IssueFilter] { return v.Filter }

// GetDefaults returns __OptionalGitHubInputsInput.Defaults, and is useful for accessing the field via an interface.
func (v *__OptionalGitHubInputsInput) GetDefaults() InputWithDefaults { return v.Defaults }

// GetOptional returns __OptionalGitHubInputsInput.Optional, and is useful for accessing the field via an interface.
func (v *__OptionalGitHubInputsInput) GetOptional() testutil.Option[OmitemptyInput] {
	return v.Optional
}

// __UpdateIssueWithCollidingNamesInput is used internally by genqlient
type __UpdateIssueWithCollidingNamesInput struct {
	Data   string                  `json:"data"`
	Req    testutil.Option[int]    `json:"req"`
	Resp   testutil.Option[int]    `json:"resp"`
	Client testutil.Option[string] `json:"client"`
}

// GetData returns __UpdateIssueWithCollidingNamesInput.Data, and is useful for accessing the field via an interface.
func (v *__UpdateIssueWithCollidingNamesInput) GetData() string { return v.Data }

// GetReq returns __UpdateIssueWithCollidingNamesInput.Req, and is useful for accessing the field via an interface.
func (v *__UpdateIssueWithCollidingNamesInput) GetReq() testutil.Option[int] { return v.Req }

// GetResp returns __UpdateIssueWithCollidingNamesInput.Resp, and is useful for accessing the field via an interface.
func (v *__UpdateIssueWithCollidingNamesInput) GetResp() testutil.Option[int] { return v.Resp }

// GetClient returns __UpdateIssueWithCollidingNamesInput.Client, and is useful for accessing the field via an interface.
func (v *__UpdateIssueWithCollidingNamesInput) GetClient() testutil.Option[string] { return v.Client }

// The query executed by OptionalGitHubInputs.
const OptionalGitHubInputs_Operation = `
query OptionalGitHubInputs ($filter: IssueFilter, $defaults: InputWithDefaults!, $optional: OmitemptyInput) {
	repository(owner: "octo", name: "fixture") {
		issues(filter: $filter) {
			nodes {
				id
			}
		}
	}
	default(input: $defaults)
	omitempty(input: $optional)
}
`

func OptionalGitHubInputs(
	ctx_ context.Context,
	client_ *octoql.Client,
	filter testutil.Option[IssueFilter],
	defaults InputWithDefaults,
	optional testutil.Option[OmitemptyInput],
) (*octoql.Response[OptionalGitHubInputsResponse], error) {
	variables_ := __OptionalGitHubInputsInput{
		Filter:   filter,
		Defaults: defaults,
		Optional: optional,
	}
	return octoql.Do[OptionalGitHubInputsResponse](
		ctx_,
		client_,
		octoql.Operation{
			Name:  "OptionalGitHubInputs",
			Query: OptionalGitHubInputs_Operation,
		},
		&variables_,
	)
}

// The mutation executed by UpdateIssueWithCollidingNames.
const UpdateIssueWithCollidingNames_Operation = `
mutation UpdateIssueWithCollidingNames ($data: String!, $req: Int, $resp: Int, $client: String) {
	closeIssue(data: $data, req: $req, resp: $resp, client: $client) {
		id
	}
}
`

func UpdateIssueWithCollidingNames(
	ctx_ context.Context,
	client_ *octoql.Client,
	data string,
	req testutil.Option[int],
	resp testutil.Option[int],
	client testutil.Option[string],
) (*octoql.Response[UpdateIssueWithCollidingNamesResponse], error) {
	variables_ := __UpdateIssueWithCollidingNamesInput{
		Data:   data,
		Req:    req,
		Resp:   resp,
		Client: client,
	}
	return octoql.Do[UpdateIssueWithCollidingNamesResponse](
		ctx_,
		client_,
		octoql.Operation{
			Name:  "UpdateIssueWithCollidingNames",
			Query: UpdateIssueWithCollidingNames_Operation,
		},
		&variables_,
	)
}

