// Code generated by octoqlgen, DO NOT EDIT.
// SPDX-License-Identifier: MIT

package test

import (
	"context"
	"encoding/json"
	"fmt"
	"time"

	"github.com/willabides/octoql"
	"github.com/willabides/octoql/graphql"
	"github.com/willabides/octoql/internal/testutil"
)

// CreateGitHubRepositoryCreateRepository includes the requested fields of the GraphQL type Repository.
type CreateGitHubRepositoryCreateRepository struct {
	Id            testutil.ID `json:"id"`
	NameWithOwner string      `json:"nameWithOwner"`
}

// GetId returns CreateGitHubRepositoryCreateRepository.Id, and is useful for accessing the field via an interface.
func (v *CreateGitHubRepositoryCreateRepository) GetId() testutil.ID { return v.Id }

// GetNameWithOwner returns CreateGitHubRepositoryCreateRepository.NameWithOwner, and is useful for accessing the field via an interface.
func (v *CreateGitHubRepositoryCreateRepository) GetNameWithOwner() string { return v.NameWithOwner }

// CreateGitHubRepositoryResponse is returned by CreateGitHubRepository on success.
type CreateGitHubRepositoryResponse struct {
	CreateRepository CreateGitHubRepositoryCreateRepository `json:"createRepository"`
}

// GetCreateRepository returns CreateGitHubRepositoryResponse.CreateRepository, and is useful for accessing the field via an interface.
func (v *CreateGitHubRepositoryResponse) GetCreateRepository() CreateGitHubRepositoryCreateRepository {
	return v.CreateRepository
}

type CreateRepositoryInput struct {
	Name       string               `json:"name"`
	Visibility RepositoryVisibility `json:"visibility"`
	Owner      RepositorySelector   `json:"owner"`
}

// GetName returns CreateRepositoryInput.Name, and is useful for accessing the field via an interface.
func (v *CreateRepositoryInput) GetName() string { return v.Name }

// GetVisibility returns CreateRepositoryInput.Visibility, and is useful for accessing the field via an interface.
func (v *CreateRepositoryInput) GetVisibility() RepositoryVisibility { return v.Visibility }

// GetOwner returns CreateRepositoryInput.Owner, and is useful for accessing the field via an interface.
func (v *CreateRepositoryInput) GetOwner() RepositorySelector { return v.Owner }

// GitHubInputResponse is returned by GitHubInputs on success.
type GitHubInputResponse struct {
	RepositoryBySelector        GitHubInputResponseRepositoryBySelectorRepository       `json:"repositoryBySelector"`
	LatestRelease               GitHubInputResponseLatestRelease                        `json:"latestRelease"`
	Default                     bool                                                    `json:"default"`
	Omitempty                   bool                                                    `json:"omitempty"`
	UseStructReferencesInput    bool                                                    `json:"useStructReferencesInput"`
	ReleasesPublishedOn         []GitHubInputResponseReleasesPublishedOnRelease         `json:"releasesPublishedOn"`
	ReleasesPublishedOnOptional []GitHubInputResponseReleasesPublishedOnOptionalRelease `json:"releasesPublishedOnOptional"`
}

// GetRepositoryBySelector returns GitHubInputResponse.RepositoryBySelector, and is useful for accessing the field via an interface.
func (v *GitHubInputResponse) GetRepositoryBySelector() GitHubInputResponseRepositoryBySelectorRepository {
	return v.RepositoryBySelector
}

// GetLatestRelease returns GitHubInputResponse.LatestRelease, and is useful for accessing the field via an interface.
func (v *GitHubInputResponse) GetLatestRelease() GitHubInputResponseLatestRelease {
	return v.LatestRelease
}

// GetDefault returns GitHubInputResponse.Default, and is useful for accessing the field via an interface.
func (v *GitHubInputResponse) GetDefault() bool { return v.Default }

// GetOmitempty returns GitHubInputResponse.Omitempty, and is useful for accessing the field via an interface.
func (v *GitHubInputResponse) GetOmitempty() bool { return v.Omitempty }

// GetUseStructReferencesInput returns GitHubInputResponse.UseStructReferencesInput, and is useful for accessing the field via an interface.
func (v *GitHubInputResponse) GetUseStructReferencesInput() bool { return v.UseStructReferencesInput }

// GetReleasesPublishedOn returns GitHubInputResponse.ReleasesPublishedOn, and is useful for accessing the field via an interface.
func (v *GitHubInputResponse) GetReleasesPublishedOn() []GitHubInputResponseReleasesPublishedOnRelease {
	return v.ReleasesPublishedOn
}

// GetReleasesPublishedOnOptional returns GitHubInputResponse.ReleasesPublishedOnOptional, and is useful for accessing the field via an interface.
func (v *GitHubInputResponse) GetReleasesPublishedOnOptional() []GitHubInputResponseReleasesPublishedOnOptionalRelease {
	return v.ReleasesPublishedOnOptional
}

// GitHubInputResponseLatestRelease includes the requested fields of the GraphQL type Release.
type GitHubInputResponseLatestRelease struct {
	PublishedAt time.Time `json:"-"`
}

// GetPublishedAt returns GitHubInputResponseLatestRelease.PublishedAt, and is useful for accessing the field via an interface.
func (v *GitHubInputResponseLatestRelease) GetPublishedAt() time.Time { return v.PublishedAt }

func (v *GitHubInputResponseLatestRelease) UnmarshalJSON(b []byte) error {

	if string(b) == "null" {
		return nil
	}

	var firstPass struct {
		*GitHubInputResponseLatestRelease
		PublishedAt json.RawMessage `json:"publishedAt"`
		graphql.NoUnmarshalJSON
	}
	firstPass.GitHubInputResponseLatestRelease = v

	err := json.Unmarshal(b, &firstPass)
	if err != nil {
		return err
	}

	{
		dst := &v.PublishedAt
		src := firstPass.PublishedAt
		if len(src) != 0 && string(src) != "null" {
			err = testutil.UnmarshalDate(
				src, dst)
			if err != nil {
				return fmt.Errorf(
					"unable to unmarshal GitHubInputResponseLatestRelease.PublishedAt: %w", err)
			}
		}
	}
	return nil
}

type __premarshalGitHubInputResponseLatestRelease struct {
	PublishedAt json.RawMessage `json:"publishedAt"`
}

func (v *GitHubInputResponseLatestRelease) MarshalJSON() ([]byte, error) {
	premarshaled, err := v.__premarshalJSON()
	if err != nil {
		return nil, err
	}
	return json.Marshal(premarshaled)
}

func (v *GitHubInputResponseLatestRelease) __premarshalJSON() (*__premarshalGitHubInputResponseLatestRelease, error) {
	var retval __premarshalGitHubInputResponseLatestRelease

	{

		dst := &retval.PublishedAt
		src := v.PublishedAt
		var err error
		*dst, err = testutil.MarshalDate(
			&src)
		if err != nil {
			return nil, fmt.Errorf(
				"unable to marshal GitHubInputResponseLatestRelease.PublishedAt: %w", err)
		}
	}
	return &retval, nil
}

// GitHubInputResponseReleasesPublishedOnOptionalRelease includes the requested fields of the GraphQL type Release.
type GitHubInputResponseReleasesPublishedOnOptionalRelease struct {
	PublishedAt time.Time `json:"-"`
}

// GetPublishedAt returns GitHubInputResponseReleasesPublishedOnOptionalRelease.PublishedAt, and is useful for accessing the field via an interface.
func (v *GitHubInputResponseReleasesPublishedOnOptionalRelease) GetPublishedAt() time.Time {
	return v.PublishedAt
}

func (v *GitHubInputResponseReleasesPublishedOnOptionalRelease) UnmarshalJSON(b []byte) error {

	if string(b) == "null" {
		return nil
	}

	var firstPass struct {
		*GitHubInputResponseReleasesPublishedOnOptionalRelease
		PublishedAt json.RawMessage `json:"publishedAt"`
		graphql.NoUnmarshalJSON
	}
	firstPass.GitHubInputResponseReleasesPublishedOnOptionalRelease = v

	err := json.Unmarshal(b, &firstPass)
	if err != nil {
		return err
	}

	{
		dst := &v.PublishedAt
		src := firstPass.PublishedAt
		if len(src) != 0 && string(src) != "null" {
			err = testutil.UnmarshalDate(
				src, dst)
			if err != nil {
				return fmt.Errorf(
					"unable to unmarshal GitHubInputResponseReleasesPublishedOnOptionalRelease.PublishedAt: %w", err)
			}
		}
	}
	return nil
}

type __premarshalGitHubInputResponseReleasesPublishedOnOptionalRelease struct {
	PublishedAt json.RawMessage `json:"publishedAt"`
}

func (v *GitHubInputResponseReleasesPublishedOnOptionalRelease) MarshalJSON() ([]byte, error) {
	premarshaled, err := v.__premarshalJSON()
	if err != nil {
		return nil, err
	}
	return json.Marshal(premarshaled)
}

func (v *GitHubInputResponseReleasesPublishedOnOptionalRelease) __premarshalJSON() (*__premarshalGitHubInputResponseReleasesPublishedOnOptionalRelease, error) {
	var retval __premarshalGitHubInputResponseReleasesPublishedOnOptionalRelease

	{

		dst := &retval.PublishedAt
		src := v.PublishedAt
		var err error
		*dst, err = testutil.MarshalDate(
			&src)
		if err != nil {
			return nil, fmt.Errorf(
				"unable to marshal GitHubInputResponseReleasesPublishedOnOptionalRelease.PublishedAt: %w", err)
		}
	}
	return &retval, nil
}

// GitHubInputResponseReleasesPublishedOnRelease includes the requested fields of the GraphQL type Release.
type GitHubInputResponseReleasesPublishedOnRelease struct {
	PublishedAt time.Time `json:"-"`
}

// GetPublishedAt returns GitHubInputResponseReleasesPublishedOnRelease.PublishedAt, and is useful for accessing the field via an interface.
func (v *GitHubInputResponseReleasesPublishedOnRelease) GetPublishedAt() time.Time {
	return v.PublishedAt
}

func (v *GitHubInputResponseReleasesPublishedOnRelease) UnmarshalJSON(b []byte) error {

	if string(b) == "null" {
		return nil
	}

	var firstPass struct {
		*GitHubInputResponseReleasesPublishedOnRelease
		PublishedAt json.RawMessage `json:"publishedAt"`
		graphql.NoUnmarshalJSON
	}
	firstPass.GitHubInputResponseReleasesPublishedOnRelease = v

	err := json.Unmarshal(b, &firstPass)
	if err != nil {
		return err
	}

	{
		dst := &v.PublishedAt
		src := firstPass.PublishedAt
		if len(src) != 0 && string(src) != "null" {
			err = testutil.UnmarshalDate(
				src, dst)
			if err != nil {
				return fmt.Errorf(
					"unable to unmarshal GitHubInputResponseReleasesPublishedOnRelease.PublishedAt: %w", err)
			}
		}
	}
	return nil
}

type __premarshalGitHubInputResponseReleasesPublishedOnRelease struct {
	PublishedAt json.RawMessage `json:"publishedAt"`
}

func (v *GitHubInputResponseReleasesPublishedOnRelease) MarshalJSON() ([]byte, error) {
	premarshaled, err := v.__premarshalJSON()
	if err != nil {
		return nil, err
	}
	return json.Marshal(premarshaled)
}

func (v *GitHubInputResponseReleasesPublishedOnRelease) __premarshalJSON() (*__premarshalGitHubInputResponseReleasesPublishedOnRelease, error) {
	var retval __premarshalGitHubInputResponseReleasesPublishedOnRelease

	{

		dst := &retval.PublishedAt
		src := v.PublishedAt
		var err error
		*dst, err = testutil.MarshalDate(
			&src)
		if err != nil {
			return nil, fmt.Errorf(
				"unable to marshal GitHubInputResponseReleasesPublishedOnRelease.PublishedAt: %w", err)
		}
	}
	return &retval, nil
}

// GitHubInputResponseRepositoryBySelectorRepository includes the requested fields of the GraphQL type Repository.
type GitHubInputResponseRepositoryBySelectorRepository struct {
	Id     testutil.ID                                                            `json:"id"`
	Issues GitHubInputResponseRepositoryBySelectorRepositoryIssuesIssueConnection `json:"issues"`
}

// GetId returns GitHubInputResponseRepositoryBySelectorRepository.Id, and is useful for accessing the field via an interface.
func (v *GitHubInputResponseRepositoryBySelectorRepository) GetId() testutil.ID { return v.Id }

// GetIssues returns GitHubInputResponseRepositoryBySelectorRepository.Issues, and is useful for accessing the field via an interface.
func (v *GitHubInputResponseRepositoryBySelectorRepository) GetIssues() GitHubInputResponseRepositoryBySelectorRepositoryIssuesIssueConnection {
	return v.Issues
}

// GitHubInputResponseRepositoryBySelectorRepositoryIssuesIssueConnection includes the requested fields of the GraphQL type IssueConnection.
type GitHubInputResponseRepositoryBySelectorRepositoryIssuesIssueConnection struct {
	Nodes []GitHubInputResponseRepositoryBySelectorRepositoryIssuesIssueConnectionNodesIssue `json:"nodes"`
}

// GetNodes returns GitHubInputResponseRepositoryBySelectorRepositoryIssuesIssueConnection.Nodes, and is useful for accessing the field via an interface.
func (v *GitHubInputResponseRepositoryBySelectorRepositoryIssuesIssueConnection) GetNodes() []GitHubInputResponseRepositoryBySelectorRepositoryIssuesIssueConnectionNodesIssue {
	return v.Nodes
}

// GitHubInputResponseRepositoryBySelectorRepositoryIssuesIssueConnectionNodesIssue includes the requested fields of the GraphQL type Issue.
type GitHubInputResponseRepositoryBySelectorRepositoryIssuesIssueConnectionNodesIssue struct {
	Id testutil.ID `json:"id"`
}

// GetId returns GitHubInputResponseRepositoryBySelectorRepositoryIssuesIssueConnectionNodesIssue.Id, and is useful for accessing the field via an interface.
func (v *GitHubInputResponseRepositoryBySelectorRepositoryIssuesIssueConnectionNodesIssue) GetId() testutil.ID {
	return v.Id
}

type InputWithDefaults struct {
	RequiredLabel string `json:"requiredLabel"`
	OptionalLabel string `json:"optionalLabel,omitempty"`
}

// GetRequiredLabel returns InputWithDefaults.RequiredLabel, and is useful for accessing the field via an interface.
func (v *InputWithDefaults) GetRequiredLabel() string { return v.RequiredLabel }

// GetOptionalLabel returns InputWithDefaults.OptionalLabel, and is useful for accessing the field via an interface.
func (v *InputWithDefaults) GetOptionalLabel() string { return v.OptionalLabel }

type IssueFilter struct {
	States    []IssueState `json:"states"`
	Labels    []string     `json:"labels"`
	Assignee  *string      `json:"assignee"`
	Milestone int          `json:"milestone"`
}

// GetStates returns IssueFilter.States, and is useful for accessing the field via an interface.
func (v *IssueFilter) GetStates() []IssueState { return v.States }

// GetLabels returns IssueFilter.Labels, and is useful for accessing the field via an interface.
func (v *IssueFilter) GetLabels() []string { return v.Labels }

// GetAssignee returns IssueFilter.Assignee, and is useful for accessing the field via an interface.
func (v *IssueFilter) GetAssignee() *string { return v.Assignee }

// GetMilestone returns IssueFilter.Milestone, and is useful for accessing the field via an interface.
func (v *IssueFilter) GetMilestone() int { return v.Milestone }

type IssueState string

const (
	IssueStateOpen   IssueState = "OPEN"
	IssueStateClosed IssueState = "CLOSED"
)

var AllIssueState = []IssueState{
	IssueStateOpen,
	IssueStateClosed,
}

type OmitemptyInput struct {
	RequiredLabel string `json:"requiredLabel"`
	OptionalLabel string `json:"optionalLabel"`
}

// GetRequiredLabel returns OmitemptyInput.RequiredLabel, and is useful for accessing the field via an interface.
func (v *OmitemptyInput) GetRequiredLabel() string { return v.RequiredLabel }

// GetOptionalLabel returns OmitemptyInput.OptionalLabel, and is useful for accessing the field via an interface.
func (v *OmitemptyInput) GetOptionalLabel() string { return v.OptionalLabel }

type RepositorySelector struct {
	Owner        string      `json:"owner"`
	Name         string      `json:"name"`
	DatabaseID   testutil.ID `json:"databaseID"`
	Topics       []string    `json:"topics"`
	CreatedAfter time.Time   `json:"-"`
}

// GetOwner returns RepositorySelector.Owner, and is useful for accessing the field via an interface.
func (v *RepositorySelector) GetOwner() string { return v.Owner }

// GetName returns RepositorySelector.Name, and is useful for accessing the field via an interface.
func (v *RepositorySelector) GetName() string { return v.Name }

// GetDatabaseID returns RepositorySelector.DatabaseID, and is useful for accessing the field via an interface.
func (v *RepositorySelector) GetDatabaseID() testutil.ID { return v.DatabaseID }

// GetTopics returns RepositorySelector.Topics, and is useful for accessing the field via an interface.
func (v *RepositorySelector) GetTopics() []string { return v.Topics }

// GetCreatedAfter returns RepositorySelector.CreatedAfter, and is useful for accessing the field via an interface.
func (v *RepositorySelector) GetCreatedAfter() time.Time { return v.CreatedAfter }

func (v *RepositorySelector) UnmarshalJSON(b []byte) error {

	if string(b) == "null" {
		return nil
	}

	var firstPass struct {
		*RepositorySelector
		CreatedAfter json.RawMessage `json:"createdAfter"`
		graphql.NoUnmarshalJSON
	}
	firstPass.RepositorySelector = v

	err := json.Unmarshal(b, &firstPass)
	if err != nil {
		return err
	}

	{
		dst := &v.CreatedAfter
		src := firstPass.CreatedAfter
		if len(src) != 0 && string(src) != "null" {
			err = testutil.UnmarshalDate(
				src, dst)
			if err != nil {
				return fmt.Errorf(
					"unable to unmarshal RepositorySelector.CreatedAfter: %w", err)
			}
		}
	}
	return nil
}

type __premarshalRepositorySelector struct {
	Owner string `json:"owner"`

	Name string `json:"name"`

	DatabaseID testutil.ID `json:"databaseID"`

	Topics []string `json:"topics"`

	CreatedAfter json.RawMessage `json:"createdAfter"`
}

func (v *RepositorySelector) MarshalJSON() ([]byte, error) {
	premarshaled, err := v.__premarshalJSON()
	if err != nil {
		return nil, err
	}
	return json.Marshal(premarshaled)
}

func (v *RepositorySelector) __premarshalJSON() (*__premarshalRepositorySelector, error) {
	var retval __premarshalRepositorySelector

	retval.Owner = v.Owner
	retval.Name = v.Name
	retval.DatabaseID = v.DatabaseID
	retval.Topics = v.Topics
	{

		dst := &retval.CreatedAfter
		src := v.CreatedAfter
		var err error
		*dst, err = testutil.MarshalDate(
			&src)
		if err != nil {
			return nil, fmt.Errorf(
				"unable to marshal RepositorySelector.CreatedAfter: %w", err)
		}
	}
	return &retval, nil
}

type RepositoryVisibility string

const (
	RepositoryVisibilityPublic   RepositoryVisibility = "PUBLIC"
	RepositoryVisibilityPrivate  RepositoryVisibility = "PRIVATE"
	RepositoryVisibilityInternal RepositoryVisibility = "INTERNAL"
)

var AllRepositoryVisibility = []RepositoryVisibility{
	RepositoryVisibilityPublic,
	RepositoryVisibilityPrivate,
	RepositoryVisibilityInternal,
}

type StructInput struct {
	Field string `json:"field"`
}

// GetField returns StructInput.Field, and is useful for accessing the field via an interface.
func (v *StructInput) GetField() string { return v.Field }

// UpdateIssueWithCollidingNamesCloseIssue includes the requested fields of the GraphQL type Issue.
type UpdateIssueWithCollidingNamesCloseIssue struct {
	Id testutil.ID `json:"id"`
}

// GetId returns UpdateIssueWithCollidingNamesCloseIssue.Id, and is useful for accessing the field via an interface.
func (v *UpdateIssueWithCollidingNamesCloseIssue) GetId() testutil.ID { return v.Id }

// UpdateIssueWithCollidingNamesResponse is returned by UpdateIssueWithCollidingNames on success.
type UpdateIssueWithCollidingNamesResponse struct {
	CloseIssue UpdateIssueWithCollidingNamesCloseIssue `json:"closeIssue"`
}

// GetCloseIssue returns UpdateIssueWithCollidingNamesResponse.CloseIssue, and is useful for accessing the field via an interface.
func (v *UpdateIssueWithCollidingNamesResponse) GetCloseIssue() UpdateIssueWithCollidingNamesCloseIssue {
	return v.CloseIssue
}

type UseStructReferencesInput struct {
	Struct         StructInput   `json:"struct"`
	NullableStruct StructInput   `json:"nullableStruct"`
	List           []StructInput `json:"list"`
	NullableList   []StructInput `json:"nullableList"`
}

// GetStruct returns UseStructReferencesInput.Struct, and is useful for accessing the field via an interface.
func (v *UseStructReferencesInput) GetStruct() StructInput { return v.Struct }

// GetNullableStruct returns UseStructReferencesInput.NullableStruct, and is useful for accessing the field via an interface.
func (v *UseStructReferencesInput) GetNullableStruct() StructInput { return v.NullableStruct }

// GetList returns UseStructReferencesInput.List, and is useful for accessing the field via an interface.
func (v *UseStructReferencesInput) GetList() []StructInput { return v.List }

// GetNullableList returns UseStructReferencesInput.NullableList, and is useful for accessing the field via an interface.
func (v *UseStructReferencesInput) GetNullableList() []StructInput { return v.NullableList }

// __CreateGitHubRepositoryInput is used internally by genqlient
type __CreateGitHubRepositoryInput struct {
	Input CreateRepositoryInput `json:"input"`
}

// GetInput returns __CreateGitHubRepositoryInput.Input, and is useful for accessing the field via an interface.
func (v *__CreateGitHubRepositoryInput) GetInput() CreateRepositoryInput { return v.Input }

// __GitHubInputsInput is used internally by genqlient
type __GitHubInputsInput struct {
	Repository             RepositorySelector       `json:"repository"`
	Filter                 IssueFilter              `json:"filter"`
	Date                   time.Time                `json:"-"`
	Defaults               InputWithDefaults        `json:"defaults"`
	Optional               OmitemptyInput           `json:"optional"`
	Structs                UseStructReferencesInput `json:"structs"`
	PublishedDates         [][][]time.Time          `json:"-"`
	OptionalPublishedDates [][][]*time.Time         `json:"-"`
}

// GetRepository returns __GitHubInputsInput.Repository, and is useful for accessing the field via an interface.
func (v *__GitHubInputsInput) GetRepository() RepositorySelector { return v.Repository }

// GetFilter returns __GitHubInputsInput.Filter, and is useful for accessing the field via an interface.
func (v *__GitHubInputsInput) GetFilter() IssueFilter { return v.Filter }

// GetDate returns __GitHubInputsInput.Date, and is useful for accessing the field via an interface.
func (v *__GitHubInputsInput) GetDate() time.Time { return v.Date }

// GetDefaults returns __GitHubInputsInput.Defaults, and is useful for accessing the field via an interface.
func (v *__GitHubInputsInput) GetDefaults() InputWithDefaults { return v.Defaults }

// GetOptional returns __GitHubInputsInput.Optional, and is useful for accessing the field via an interface.
func (v *__GitHubInputsInput) GetOptional() OmitemptyInput { return v.Optional }

// GetStructs returns __GitHubInputsInput.Structs, and is useful for accessing the field via an interface.
func (v *__GitHubInputsInput) GetStructs() UseStructReferencesInput { return v.Structs }

// GetPublishedDates returns __GitHubInputsInput.PublishedDates, and is useful for accessing the field via an interface.
func (v *__GitHubInputsInput) GetPublishedDates() [][][]time.Time { return v.PublishedDates }

// GetOptionalPublishedDates returns __GitHubInputsInput.OptionalPublishedDates, and is useful for accessing the field via an interface.
func (v *__GitHubInputsInput) GetOptionalPublishedDates() [][][]*time.Time {
	return v.OptionalPublishedDates
}

func (v *__GitHubInputsInput) UnmarshalJSON(b []byte) error {

	if string(b) == "null" {
		return nil
	}

	var firstPass struct {
		*__GitHubInputsInput
		Date                   json.RawMessage       `json:"date"`
		PublishedDates         [][][]json.RawMessage `json:"publishedDates"`
		OptionalPublishedDates [][][]json.RawMessage `json:"optionalPublishedDates"`
		graphql.NoUnmarshalJSON
	}
	firstPass.__GitHubInputsInput = v

	err := json.Unmarshal(b, &firstPass)
	if err != nil {
		return err
	}

	{
		dst := &v.Date
		src := firstPass.Date
		if len(src) != 0 && string(src) != "null" {
			err = testutil.UnmarshalDate(
				src, dst)
			if err != nil {
				return fmt.Errorf(
					"unable to unmarshal __GitHubInputsInput.Date: %w", err)
			}
		}
	}

	{
		dst := &v.PublishedDates
		src := firstPass.PublishedDates
		*dst = make(
			[][][]time.Time,
			len(src))
		for i, src := range src {
			dst := &(*dst)[i]
			*dst = make(
				[][]time.Time,
				len(src))
			for i, src := range src {
				dst := &(*dst)[i]
				*dst = make(
					[]time.Time,
					len(src))
				for i, src := range src {
					dst := &(*dst)[i]
					if len(src) != 0 && string(src) != "null" {
						err = testutil.UnmarshalDate(
							src, dst)
						if err != nil {
							return fmt.Errorf(
								"unable to unmarshal __GitHubInputsInput.PublishedDates: %w", err)
						}
					}
				}
			}
		}
	}

	{
		dst := &v.OptionalPublishedDates
		src := firstPass.OptionalPublishedDates
		*dst = make(
			[][][]*time.Time,
			len(src))
		for i, src := range src {
			dst := &(*dst)[i]
			*dst = make(
				[][]*time.Time,
				len(src))
			for i, src := range src {
				dst := &(*dst)[i]
				*dst = make(
					[]*time.Time,
					len(src))
				for i, src := range src {
					dst := &(*dst)[i]
					if len(src) != 0 && string(src) != "null" {
						*dst = new(time.Time)
						err = testutil.UnmarshalDate(
							src, *dst)
						if err != nil {
							return fmt.Errorf(
								"unable to unmarshal __GitHubInputsInput.OptionalPublishedDates: %w", err)
						}
					}
				}
			}
		}
	}
	return nil
}

type __premarshal__GitHubInputsInput struct {
	Repository RepositorySelector `json:"repository"`

	Filter IssueFilter `json:"filter"`

	Date json.RawMessage `json:"date"`

	Defaults InputWithDefaults `json:"defaults"`

	Optional OmitemptyInput `json:"optional"`

	Structs UseStructReferencesInput `json:"structs"`

	PublishedDates [][][]json.RawMessage `json:"publishedDates"`

	OptionalPublishedDates [][][]json.RawMessage `json:"optionalPublishedDates"`
}

func (v *__GitHubInputsInput) MarshalJSON() ([]byte, error) {
	premarshaled, err := v.__premarshalJSON()
	if err != nil {
		return nil, err
	}
	return json.Marshal(premarshaled)
}

func (v *__GitHubInputsInput) __premarshalJSON() (*__premarshal__GitHubInputsInput, error) {
	var retval __premarshal__GitHubInputsInput

	retval.Repository = v.Repository
	retval.Filter = v.Filter
	{

		dst := &retval.Date
		src := v.Date
		var err error
		*dst, err = testutil.MarshalDate(
			&src)
		if err != nil {
			return nil, fmt.Errorf(
				"unable to marshal __GitHubInputsInput.Date: %w", err)
		}
	}
	retval.Defaults = v.Defaults
	retval.Optional = v.Optional
	retval.Structs = v.Structs
	{

		dst := &retval.PublishedDates
		src := v.PublishedDates
		*dst = make(
			[][][]json.RawMessage,
			len(src))
		for i, src := range src {
			dst := &(*dst)[i]
			*dst = make(
				[][]json.RawMessage,
				len(src))
			for i, src := range src {
				dst := &(*dst)[i]
				*dst = make(
					[]json.RawMessage,
					len(src))
				for i, src := range src {
					dst := &(*dst)[i]
					var err error
					*dst, err = testutil.MarshalDate(
						&src)
					if err != nil {
						return nil, fmt.Errorf(
							"unable to marshal __GitHubInputsInput.PublishedDates: %w", err)
					}
				}
			}
		}
	}
	{

		dst := &retval.OptionalPublishedDates
		src := v.OptionalPublishedDates
		*dst = make(
			[][][]json.RawMessage,
			len(src))
		for i, src := range src {
			dst := &(*dst)[i]
			*dst = make(
				[][]json.RawMessage,
				len(src))
			for i, src := range src {
				dst := &(*dst)[i]
				*dst = make(
					[]json.RawMessage,
					len(src))
				for i, src := range src {
					dst := &(*dst)[i]
					if src != nil {
						var err error
						*dst, err = testutil.MarshalDate(
							src)
						if err != nil {
							return nil, fmt.Errorf(
								"unable to marshal __GitHubInputsInput.OptionalPublishedDates: %w", err)
						}
					}
				}
			}
		}
	}
	return &retval, nil
}

// __UpdateIssueWithCollidingNamesInput is used internally by genqlient
type __UpdateIssueWithCollidingNamesInput struct {
	Data   string `json:"data"`
	Req    int    `json:"req"`
	Resp   int    `json:"resp"`
	Client string `json:"client"`
}

// GetData returns __UpdateIssueWithCollidingNamesInput.Data, and is useful for accessing the field via an interface.
func (v *__UpdateIssueWithCollidingNamesInput) GetData() string { return v.Data }

// GetReq returns __UpdateIssueWithCollidingNamesInput.Req, and is useful for accessing the field via an interface.
func (v *__UpdateIssueWithCollidingNamesInput) GetReq() int { return v.Req }

// GetResp returns __UpdateIssueWithCollidingNamesInput.Resp, and is useful for accessing the field via an interface.
func (v *__UpdateIssueWithCollidingNamesInput) GetResp() int { return v.Resp }

// GetClient returns __UpdateIssueWithCollidingNamesInput.Client, and is useful for accessing the field via an interface.
func (v *__UpdateIssueWithCollidingNamesInput) GetClient() string { return v.Client }

// The mutation executed by CreateGitHubRepository.
const CreateGitHubRepository_Operation = `
mutation CreateGitHubRepository ($input: CreateRepositoryInput!) {
	createRepository(input: $input) {
		id
		nameWithOwner
	}
}
`

func CreateGitHubRepository(
	client_ *octoql.Client,
	input CreateRepositoryInput,
) (*octoql.Response[CreateGitHubRepositoryResponse], error) {
	variables_ := __CreateGitHubRepositoryInput{
		Input: input,
	}
	return octoql.Do[CreateGitHubRepositoryResponse](
		context.Background(),
		client_,
		octoql.Operation{
			Name:  "CreateGitHubRepository",
			Query: CreateGitHubRepository_Operation,
		},
		&variables_,
	)
}

// The query executed by GitHubInputs.
const GitHubInputs_Operation = `
query GitHubInputs ($repository: RepositorySelector!, $filter: IssueFilter, $date: Date, $defaults: InputWithDefaults!, $optional: OmitemptyInput, $structs: UseStructReferencesInput!, $publishedDates: [[[Date!]!]!]!, $optionalPublishedDates: [[[Date!]!]!]) {
	repositoryBySelector(input: $repository) {
		id
		issues(filter: $filter) {
			nodes {
				id
			}
		}
	}
	latestRelease(publishedAfter: $date) {
		publishedAt
	}
	default(input: $defaults)
	omitempty(input: $optional)
	useStructReferencesInput(input: $structs)
	releasesPublishedOn(dates: $publishedDates) {
		publishedAt
	}
	releasesPublishedOnOptional(dates: $optionalPublishedDates) {
		publishedAt
	}
}
`

func GitHubInputs(
	client_ *octoql.Client,
	repository RepositorySelector,
	filter IssueFilter,
	date time.Time,
	defaults InputWithDefaults,
	optional OmitemptyInput,
	structs UseStructReferencesInput,
	publishedDates [][][]time.Time,
	optionalPublishedDates [][][]*time.Time,
) (*octoql.Response[GitHubInputResponse], error) {
	variables_ := __GitHubInputsInput{
		Repository:             repository,
		Filter:                 filter,
		Date:                   date,
		Defaults:               defaults,
		Optional:               optional,
		Structs:                structs,
		PublishedDates:         publishedDates,
		OptionalPublishedDates: optionalPublishedDates,
	}
	return octoql.Do[GitHubInputResponse](
		context.Background(),
		client_,
		octoql.Operation{
			Name:  "GitHubInputs",
			Query: GitHubInputs_Operation,
		},
		&variables_,
	)
}

// The mutation executed by UpdateIssueWithCollidingNames.
const UpdateIssueWithCollidingNames_Operation = `
mutation UpdateIssueWithCollidingNames ($data: String!, $req: Int, $resp: Int, $client: String) {
	closeIssue(data: $data, req: $req, resp: $resp, client: $client) {
		id
	}
}
`

func UpdateIssueWithCollidingNames(
	client_ *octoql.Client,
	data string,
	req int,
	resp int,
	client string,
) (*octoql.Response[UpdateIssueWithCollidingNamesResponse], error) {
	variables_ := __UpdateIssueWithCollidingNamesInput{
		Data:   data,
		Req:    req,
		Resp:   resp,
		Client: client,
	}
	return octoql.Do[UpdateIssueWithCollidingNamesResponse](
		context.Background(),
		client_,
		octoql.Operation{
			Name:  "UpdateIssueWithCollidingNames",
			Query: UpdateIssueWithCollidingNames_Operation,
		},
		&variables_,
	)
}
