// Code generated by octoqlgen, DO NOT EDIT.
// SPDX-License-Identifier: MIT

package queries

import (
	"context"

	"github.com/willabides/octoql"
)

// ListInputOmitemptyQueryResponse is returned by ListInputOmitemptyQuery on success.
type ListInputOmitemptyQueryResponse struct {
	// user looks up a user by some stuff.
	//
	// See UserQueryInput for what stuff is supported.
	// If query is null, returns the current user.
	User *ListInputOmitemptyQueryUser `json:"user"`
}

// GetUser returns ListInputOmitemptyQueryResponse.User, and is useful for accessing the field via an interface.
func (v *ListInputOmitemptyQueryResponse) GetUser() *ListInputOmitemptyQueryUser { return v.User }

// ListInputOmitemptyQueryUser includes the requested fields of the GraphQL type User.
// The GraphQL type's documentation follows.
//
// A User is a user!
type ListInputOmitemptyQueryUser struct {
	// id is the user's ID.
	//
	// It is stable, unique, and opaque, like all good IDs.
	Id string `json:"id"`
}

// GetId returns ListInputOmitemptyQueryUser.Id, and is useful for accessing the field via an interface.
func (v *ListInputOmitemptyQueryUser) GetId() string { return v.Id }

// __ListInputOmitemptyQueryInput is used internally by genqlient
type __ListInputOmitemptyQueryInput struct {
	Names []string `json:"names,omitempty"`
}

// GetNames returns __ListInputOmitemptyQueryInput.Names, and is useful for accessing the field via an interface.
func (v *__ListInputOmitemptyQueryInput) GetNames() []string { return v.Names }

// The query executed by ListInputOmitemptyQuery.
const ListInputOmitemptyQuery_Operation = `
query ListInputOmitemptyQuery ($names: [String!]) {
	user(query: {names:$names}) {
		id
	}
}
`

func ListInputOmitemptyQuery(
	ctx_ context.Context,
	client_ *octoql.Client,
	names []string,
) (*octoql.Response[ListInputOmitemptyQueryResponse], error) {
	variables_ := __ListInputOmitemptyQueryInput{
		Names: names,
	}
	return octoql.Do[ListInputOmitemptyQueryResponse](
		ctx_,
		client_,
		octoql.Operation{
			Name:  "ListInputOmitemptyQuery",
			Query: ListInputOmitemptyQuery_Operation,
		},
		&variables_,
	)
}

