// Code generated by octoqlgen, DO NOT EDIT.
// SPDX-License-Identifier: MIT

package queries

import (
	"context"

	"github.com/willabides/octoql"
	"github.com/willabides/octoql/internal/testutil"
)

// GetBoundAccountResponse is returned by GetBoundAccount on success.
type GetBoundAccountResponse struct {
	Account testutil.Account `json:"account"`
}

// GetAccount returns GetBoundAccountResponse.Account, and is useful for accessing the field via an interface.
func (v *GetBoundAccountResponse) GetAccount() testutil.Account { return v.Account }

// The query executed by GetBoundAccount.
const GetBoundAccount_Operation = `
query GetBoundAccount {
	account {
		id
		login
	}
}
`

func GetBoundAccount(
	ctx_ context.Context,
	client_ *octoql.Client,
) (*octoql.Response[GetBoundAccountResponse], error) {
	return octoql.Do[GetBoundAccountResponse](
		ctx_,
		client_,
		octoql.Operation{
			Name:  "GetBoundAccount",
			Query: GetBoundAccount_Operation,
		},
		nil,
	)
}
